
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CareerPath` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CareerPath
 * 
 */
export type CareerPathModel = runtime.Types.Result.DefaultSelection<Prisma.$CareerPathPayload>

export type AggregateCareerPath = {
  _count: CareerPathCountAggregateOutputType | null
  _min: CareerPathMinAggregateOutputType | null
  _max: CareerPathMaxAggregateOutputType | null
}

export type CareerPathMinAggregateOutputType = {
  id: string | null
  majorId: string | null
  title: string | null
  level: string | null
  salary: string | null
  skills: string | null
}

export type CareerPathMaxAggregateOutputType = {
  id: string | null
  majorId: string | null
  title: string | null
  level: string | null
  salary: string | null
  skills: string | null
}

export type CareerPathCountAggregateOutputType = {
  id: number
  majorId: number
  title: number
  level: number
  salary: number
  skills: number
  _all: number
}


export type CareerPathMinAggregateInputType = {
  id?: true
  majorId?: true
  title?: true
  level?: true
  salary?: true
  skills?: true
}

export type CareerPathMaxAggregateInputType = {
  id?: true
  majorId?: true
  title?: true
  level?: true
  salary?: true
  skills?: true
}

export type CareerPathCountAggregateInputType = {
  id?: true
  majorId?: true
  title?: true
  level?: true
  salary?: true
  skills?: true
  _all?: true
}

export type CareerPathAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CareerPath to aggregate.
   */
  where?: Prisma.CareerPathWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CareerPaths to fetch.
   */
  orderBy?: Prisma.CareerPathOrderByWithRelationInput | Prisma.CareerPathOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CareerPathWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CareerPaths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CareerPaths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CareerPaths
  **/
  _count?: true | CareerPathCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CareerPathMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CareerPathMaxAggregateInputType
}

export type GetCareerPathAggregateType<T extends CareerPathAggregateArgs> = {
      [P in keyof T & keyof AggregateCareerPath]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCareerPath[P]>
    : Prisma.GetScalarType<T[P], AggregateCareerPath[P]>
}




export type CareerPathGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CareerPathWhereInput
  orderBy?: Prisma.CareerPathOrderByWithAggregationInput | Prisma.CareerPathOrderByWithAggregationInput[]
  by: Prisma.CareerPathScalarFieldEnum[] | Prisma.CareerPathScalarFieldEnum
  having?: Prisma.CareerPathScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CareerPathCountAggregateInputType | true
  _min?: CareerPathMinAggregateInputType
  _max?: CareerPathMaxAggregateInputType
}

export type CareerPathGroupByOutputType = {
  id: string
  majorId: string
  title: string
  level: string
  salary: string
  skills: string
  _count: CareerPathCountAggregateOutputType | null
  _min: CareerPathMinAggregateOutputType | null
  _max: CareerPathMaxAggregateOutputType | null
}

export type GetCareerPathGroupByPayload<T extends CareerPathGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CareerPathGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CareerPathGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CareerPathGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CareerPathGroupByOutputType[P]>
      }
    >
  >



export type CareerPathWhereInput = {
  AND?: Prisma.CareerPathWhereInput | Prisma.CareerPathWhereInput[]
  OR?: Prisma.CareerPathWhereInput[]
  NOT?: Prisma.CareerPathWhereInput | Prisma.CareerPathWhereInput[]
  id?: Prisma.StringFilter<"CareerPath"> | string
  majorId?: Prisma.StringFilter<"CareerPath"> | string
  title?: Prisma.StringFilter<"CareerPath"> | string
  level?: Prisma.StringFilter<"CareerPath"> | string
  salary?: Prisma.StringFilter<"CareerPath"> | string
  skills?: Prisma.StringFilter<"CareerPath"> | string
  major?: Prisma.XOR<Prisma.MajorScalarRelationFilter, Prisma.MajorWhereInput>
}

export type CareerPathOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  level?: Prisma.SortOrder
  salary?: Prisma.SortOrder
  skills?: Prisma.SortOrder
  major?: Prisma.MajorOrderByWithRelationInput
}

export type CareerPathWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CareerPathWhereInput | Prisma.CareerPathWhereInput[]
  OR?: Prisma.CareerPathWhereInput[]
  NOT?: Prisma.CareerPathWhereInput | Prisma.CareerPathWhereInput[]
  majorId?: Prisma.StringFilter<"CareerPath"> | string
  title?: Prisma.StringFilter<"CareerPath"> | string
  level?: Prisma.StringFilter<"CareerPath"> | string
  salary?: Prisma.StringFilter<"CareerPath"> | string
  skills?: Prisma.StringFilter<"CareerPath"> | string
  major?: Prisma.XOR<Prisma.MajorScalarRelationFilter, Prisma.MajorWhereInput>
}, "id">

export type CareerPathOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  level?: Prisma.SortOrder
  salary?: Prisma.SortOrder
  skills?: Prisma.SortOrder
  _count?: Prisma.CareerPathCountOrderByAggregateInput
  _max?: Prisma.CareerPathMaxOrderByAggregateInput
  _min?: Prisma.CareerPathMinOrderByAggregateInput
}

export type CareerPathScalarWhereWithAggregatesInput = {
  AND?: Prisma.CareerPathScalarWhereWithAggregatesInput | Prisma.CareerPathScalarWhereWithAggregatesInput[]
  OR?: Prisma.CareerPathScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CareerPathScalarWhereWithAggregatesInput | Prisma.CareerPathScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CareerPath"> | string
  majorId?: Prisma.StringWithAggregatesFilter<"CareerPath"> | string
  title?: Prisma.StringWithAggregatesFilter<"CareerPath"> | string
  level?: Prisma.StringWithAggregatesFilter<"CareerPath"> | string
  salary?: Prisma.StringWithAggregatesFilter<"CareerPath"> | string
  skills?: Prisma.StringWithAggregatesFilter<"CareerPath"> | string
}

export type CareerPathCreateInput = {
  id?: string
  title: string
  level: string
  salary: string
  skills: string
  major: Prisma.MajorCreateNestedOneWithoutCareerPathsInput
}

export type CareerPathUncheckedCreateInput = {
  id?: string
  majorId: string
  title: string
  level: string
  salary: string
  skills: string
}

export type CareerPathUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  salary?: Prisma.StringFieldUpdateOperationsInput | string
  skills?: Prisma.StringFieldUpdateOperationsInput | string
  major?: Prisma.MajorUpdateOneRequiredWithoutCareerPathsNestedInput
}

export type CareerPathUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  majorId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  salary?: Prisma.StringFieldUpdateOperationsInput | string
  skills?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CareerPathCreateManyInput = {
  id?: string
  majorId: string
  title: string
  level: string
  salary: string
  skills: string
}

export type CareerPathUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  salary?: Prisma.StringFieldUpdateOperationsInput | string
  skills?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CareerPathUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  majorId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  salary?: Prisma.StringFieldUpdateOperationsInput | string
  skills?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CareerPathListRelationFilter = {
  every?: Prisma.CareerPathWhereInput
  some?: Prisma.CareerPathWhereInput
  none?: Prisma.CareerPathWhereInput
}

export type CareerPathOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CareerPathCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  level?: Prisma.SortOrder
  salary?: Prisma.SortOrder
  skills?: Prisma.SortOrder
}

export type CareerPathMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  level?: Prisma.SortOrder
  salary?: Prisma.SortOrder
  skills?: Prisma.SortOrder
}

export type CareerPathMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  level?: Prisma.SortOrder
  salary?: Prisma.SortOrder
  skills?: Prisma.SortOrder
}

export type CareerPathCreateNestedManyWithoutMajorInput = {
  create?: Prisma.XOR<Prisma.CareerPathCreateWithoutMajorInput, Prisma.CareerPathUncheckedCreateWithoutMajorInput> | Prisma.CareerPathCreateWithoutMajorInput[] | Prisma.CareerPathUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.CareerPathCreateOrConnectWithoutMajorInput | Prisma.CareerPathCreateOrConnectWithoutMajorInput[]
  createMany?: Prisma.CareerPathCreateManyMajorInputEnvelope
  connect?: Prisma.CareerPathWhereUniqueInput | Prisma.CareerPathWhereUniqueInput[]
}

export type CareerPathUncheckedCreateNestedManyWithoutMajorInput = {
  create?: Prisma.XOR<Prisma.CareerPathCreateWithoutMajorInput, Prisma.CareerPathUncheckedCreateWithoutMajorInput> | Prisma.CareerPathCreateWithoutMajorInput[] | Prisma.CareerPathUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.CareerPathCreateOrConnectWithoutMajorInput | Prisma.CareerPathCreateOrConnectWithoutMajorInput[]
  createMany?: Prisma.CareerPathCreateManyMajorInputEnvelope
  connect?: Prisma.CareerPathWhereUniqueInput | Prisma.CareerPathWhereUniqueInput[]
}

export type CareerPathUpdateManyWithoutMajorNestedInput = {
  create?: Prisma.XOR<Prisma.CareerPathCreateWithoutMajorInput, Prisma.CareerPathUncheckedCreateWithoutMajorInput> | Prisma.CareerPathCreateWithoutMajorInput[] | Prisma.CareerPathUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.CareerPathCreateOrConnectWithoutMajorInput | Prisma.CareerPathCreateOrConnectWithoutMajorInput[]
  upsert?: Prisma.CareerPathUpsertWithWhereUniqueWithoutMajorInput | Prisma.CareerPathUpsertWithWhereUniqueWithoutMajorInput[]
  createMany?: Prisma.CareerPathCreateManyMajorInputEnvelope
  set?: Prisma.CareerPathWhereUniqueInput | Prisma.CareerPathWhereUniqueInput[]
  disconnect?: Prisma.CareerPathWhereUniqueInput | Prisma.CareerPathWhereUniqueInput[]
  delete?: Prisma.CareerPathWhereUniqueInput | Prisma.CareerPathWhereUniqueInput[]
  connect?: Prisma.CareerPathWhereUniqueInput | Prisma.CareerPathWhereUniqueInput[]
  update?: Prisma.CareerPathUpdateWithWhereUniqueWithoutMajorInput | Prisma.CareerPathUpdateWithWhereUniqueWithoutMajorInput[]
  updateMany?: Prisma.CareerPathUpdateManyWithWhereWithoutMajorInput | Prisma.CareerPathUpdateManyWithWhereWithoutMajorInput[]
  deleteMany?: Prisma.CareerPathScalarWhereInput | Prisma.CareerPathScalarWhereInput[]
}

export type CareerPathUncheckedUpdateManyWithoutMajorNestedInput = {
  create?: Prisma.XOR<Prisma.CareerPathCreateWithoutMajorInput, Prisma.CareerPathUncheckedCreateWithoutMajorInput> | Prisma.CareerPathCreateWithoutMajorInput[] | Prisma.CareerPathUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.CareerPathCreateOrConnectWithoutMajorInput | Prisma.CareerPathCreateOrConnectWithoutMajorInput[]
  upsert?: Prisma.CareerPathUpsertWithWhereUniqueWithoutMajorInput | Prisma.CareerPathUpsertWithWhereUniqueWithoutMajorInput[]
  createMany?: Prisma.CareerPathCreateManyMajorInputEnvelope
  set?: Prisma.CareerPathWhereUniqueInput | Prisma.CareerPathWhereUniqueInput[]
  disconnect?: Prisma.CareerPathWhereUniqueInput | Prisma.CareerPathWhereUniqueInput[]
  delete?: Prisma.CareerPathWhereUniqueInput | Prisma.CareerPathWhereUniqueInput[]
  connect?: Prisma.CareerPathWhereUniqueInput | Prisma.CareerPathWhereUniqueInput[]
  update?: Prisma.CareerPathUpdateWithWhereUniqueWithoutMajorInput | Prisma.CareerPathUpdateWithWhereUniqueWithoutMajorInput[]
  updateMany?: Prisma.CareerPathUpdateManyWithWhereWithoutMajorInput | Prisma.CareerPathUpdateManyWithWhereWithoutMajorInput[]
  deleteMany?: Prisma.CareerPathScalarWhereInput | Prisma.CareerPathScalarWhereInput[]
}

export type CareerPathCreateWithoutMajorInput = {
  id?: string
  title: string
  level: string
  salary: string
  skills: string
}

export type CareerPathUncheckedCreateWithoutMajorInput = {
  id?: string
  title: string
  level: string
  salary: string
  skills: string
}

export type CareerPathCreateOrConnectWithoutMajorInput = {
  where: Prisma.CareerPathWhereUniqueInput
  create: Prisma.XOR<Prisma.CareerPathCreateWithoutMajorInput, Prisma.CareerPathUncheckedCreateWithoutMajorInput>
}

export type CareerPathCreateManyMajorInputEnvelope = {
  data: Prisma.CareerPathCreateManyMajorInput | Prisma.CareerPathCreateManyMajorInput[]
}

export type CareerPathUpsertWithWhereUniqueWithoutMajorInput = {
  where: Prisma.CareerPathWhereUniqueInput
  update: Prisma.XOR<Prisma.CareerPathUpdateWithoutMajorInput, Prisma.CareerPathUncheckedUpdateWithoutMajorInput>
  create: Prisma.XOR<Prisma.CareerPathCreateWithoutMajorInput, Prisma.CareerPathUncheckedCreateWithoutMajorInput>
}

export type CareerPathUpdateWithWhereUniqueWithoutMajorInput = {
  where: Prisma.CareerPathWhereUniqueInput
  data: Prisma.XOR<Prisma.CareerPathUpdateWithoutMajorInput, Prisma.CareerPathUncheckedUpdateWithoutMajorInput>
}

export type CareerPathUpdateManyWithWhereWithoutMajorInput = {
  where: Prisma.CareerPathScalarWhereInput
  data: Prisma.XOR<Prisma.CareerPathUpdateManyMutationInput, Prisma.CareerPathUncheckedUpdateManyWithoutMajorInput>
}

export type CareerPathScalarWhereInput = {
  AND?: Prisma.CareerPathScalarWhereInput | Prisma.CareerPathScalarWhereInput[]
  OR?: Prisma.CareerPathScalarWhereInput[]
  NOT?: Prisma.CareerPathScalarWhereInput | Prisma.CareerPathScalarWhereInput[]
  id?: Prisma.StringFilter<"CareerPath"> | string
  majorId?: Prisma.StringFilter<"CareerPath"> | string
  title?: Prisma.StringFilter<"CareerPath"> | string
  level?: Prisma.StringFilter<"CareerPath"> | string
  salary?: Prisma.StringFilter<"CareerPath"> | string
  skills?: Prisma.StringFilter<"CareerPath"> | string
}

export type CareerPathCreateManyMajorInput = {
  id?: string
  title: string
  level: string
  salary: string
  skills: string
}

export type CareerPathUpdateWithoutMajorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  salary?: Prisma.StringFieldUpdateOperationsInput | string
  skills?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CareerPathUncheckedUpdateWithoutMajorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  salary?: Prisma.StringFieldUpdateOperationsInput | string
  skills?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CareerPathUncheckedUpdateManyWithoutMajorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.StringFieldUpdateOperationsInput | string
  salary?: Prisma.StringFieldUpdateOperationsInput | string
  skills?: Prisma.StringFieldUpdateOperationsInput | string
}



export type CareerPathSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  majorId?: boolean
  title?: boolean
  level?: boolean
  salary?: boolean
  skills?: boolean
  major?: boolean | Prisma.MajorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["careerPath"]>

export type CareerPathSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  majorId?: boolean
  title?: boolean
  level?: boolean
  salary?: boolean
  skills?: boolean
  major?: boolean | Prisma.MajorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["careerPath"]>

export type CareerPathSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  majorId?: boolean
  title?: boolean
  level?: boolean
  salary?: boolean
  skills?: boolean
  major?: boolean | Prisma.MajorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["careerPath"]>

export type CareerPathSelectScalar = {
  id?: boolean
  majorId?: boolean
  title?: boolean
  level?: boolean
  salary?: boolean
  skills?: boolean
}

export type CareerPathOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "majorId" | "title" | "level" | "salary" | "skills", ExtArgs["result"]["careerPath"]>
export type CareerPathInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  major?: boolean | Prisma.MajorDefaultArgs<ExtArgs>
}
export type CareerPathIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  major?: boolean | Prisma.MajorDefaultArgs<ExtArgs>
}
export type CareerPathIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  major?: boolean | Prisma.MajorDefaultArgs<ExtArgs>
}

export type $CareerPathPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CareerPath"
  objects: {
    major: Prisma.$MajorPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    majorId: string
    title: string
    level: string
    salary: string
    skills: string
  }, ExtArgs["result"]["careerPath"]>
  composites: {}
}

export type CareerPathGetPayload<S extends boolean | null | undefined | CareerPathDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CareerPathPayload, S>

export type CareerPathCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CareerPathFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CareerPathCountAggregateInputType | true
  }

export interface CareerPathDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CareerPath'], meta: { name: 'CareerPath' } }
  /**
   * Find zero or one CareerPath that matches the filter.
   * @param {CareerPathFindUniqueArgs} args - Arguments to find a CareerPath
   * @example
   * // Get one CareerPath
   * const careerPath = await prisma.careerPath.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CareerPathFindUniqueArgs>(args: Prisma.SelectSubset<T, CareerPathFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CareerPathClient<runtime.Types.Result.GetResult<Prisma.$CareerPathPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CareerPath that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CareerPathFindUniqueOrThrowArgs} args - Arguments to find a CareerPath
   * @example
   * // Get one CareerPath
   * const careerPath = await prisma.careerPath.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CareerPathFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CareerPathFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CareerPathClient<runtime.Types.Result.GetResult<Prisma.$CareerPathPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CareerPath that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CareerPathFindFirstArgs} args - Arguments to find a CareerPath
   * @example
   * // Get one CareerPath
   * const careerPath = await prisma.careerPath.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CareerPathFindFirstArgs>(args?: Prisma.SelectSubset<T, CareerPathFindFirstArgs<ExtArgs>>): Prisma.Prisma__CareerPathClient<runtime.Types.Result.GetResult<Prisma.$CareerPathPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CareerPath that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CareerPathFindFirstOrThrowArgs} args - Arguments to find a CareerPath
   * @example
   * // Get one CareerPath
   * const careerPath = await prisma.careerPath.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CareerPathFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CareerPathFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CareerPathClient<runtime.Types.Result.GetResult<Prisma.$CareerPathPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CareerPaths that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CareerPathFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CareerPaths
   * const careerPaths = await prisma.careerPath.findMany()
   * 
   * // Get first 10 CareerPaths
   * const careerPaths = await prisma.careerPath.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const careerPathWithIdOnly = await prisma.careerPath.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CareerPathFindManyArgs>(args?: Prisma.SelectSubset<T, CareerPathFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CareerPathPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CareerPath.
   * @param {CareerPathCreateArgs} args - Arguments to create a CareerPath.
   * @example
   * // Create one CareerPath
   * const CareerPath = await prisma.careerPath.create({
   *   data: {
   *     // ... data to create a CareerPath
   *   }
   * })
   * 
   */
  create<T extends CareerPathCreateArgs>(args: Prisma.SelectSubset<T, CareerPathCreateArgs<ExtArgs>>): Prisma.Prisma__CareerPathClient<runtime.Types.Result.GetResult<Prisma.$CareerPathPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CareerPaths.
   * @param {CareerPathCreateManyArgs} args - Arguments to create many CareerPaths.
   * @example
   * // Create many CareerPaths
   * const careerPath = await prisma.careerPath.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CareerPathCreateManyArgs>(args?: Prisma.SelectSubset<T, CareerPathCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CareerPaths and returns the data saved in the database.
   * @param {CareerPathCreateManyAndReturnArgs} args - Arguments to create many CareerPaths.
   * @example
   * // Create many CareerPaths
   * const careerPath = await prisma.careerPath.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CareerPaths and only return the `id`
   * const careerPathWithIdOnly = await prisma.careerPath.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CareerPathCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CareerPathCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CareerPathPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CareerPath.
   * @param {CareerPathDeleteArgs} args - Arguments to delete one CareerPath.
   * @example
   * // Delete one CareerPath
   * const CareerPath = await prisma.careerPath.delete({
   *   where: {
   *     // ... filter to delete one CareerPath
   *   }
   * })
   * 
   */
  delete<T extends CareerPathDeleteArgs>(args: Prisma.SelectSubset<T, CareerPathDeleteArgs<ExtArgs>>): Prisma.Prisma__CareerPathClient<runtime.Types.Result.GetResult<Prisma.$CareerPathPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CareerPath.
   * @param {CareerPathUpdateArgs} args - Arguments to update one CareerPath.
   * @example
   * // Update one CareerPath
   * const careerPath = await prisma.careerPath.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CareerPathUpdateArgs>(args: Prisma.SelectSubset<T, CareerPathUpdateArgs<ExtArgs>>): Prisma.Prisma__CareerPathClient<runtime.Types.Result.GetResult<Prisma.$CareerPathPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CareerPaths.
   * @param {CareerPathDeleteManyArgs} args - Arguments to filter CareerPaths to delete.
   * @example
   * // Delete a few CareerPaths
   * const { count } = await prisma.careerPath.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CareerPathDeleteManyArgs>(args?: Prisma.SelectSubset<T, CareerPathDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CareerPaths.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CareerPathUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CareerPaths
   * const careerPath = await prisma.careerPath.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CareerPathUpdateManyArgs>(args: Prisma.SelectSubset<T, CareerPathUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CareerPaths and returns the data updated in the database.
   * @param {CareerPathUpdateManyAndReturnArgs} args - Arguments to update many CareerPaths.
   * @example
   * // Update many CareerPaths
   * const careerPath = await prisma.careerPath.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CareerPaths and only return the `id`
   * const careerPathWithIdOnly = await prisma.careerPath.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CareerPathUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CareerPathUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CareerPathPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CareerPath.
   * @param {CareerPathUpsertArgs} args - Arguments to update or create a CareerPath.
   * @example
   * // Update or create a CareerPath
   * const careerPath = await prisma.careerPath.upsert({
   *   create: {
   *     // ... data to create a CareerPath
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CareerPath we want to update
   *   }
   * })
   */
  upsert<T extends CareerPathUpsertArgs>(args: Prisma.SelectSubset<T, CareerPathUpsertArgs<ExtArgs>>): Prisma.Prisma__CareerPathClient<runtime.Types.Result.GetResult<Prisma.$CareerPathPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CareerPaths.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CareerPathCountArgs} args - Arguments to filter CareerPaths to count.
   * @example
   * // Count the number of CareerPaths
   * const count = await prisma.careerPath.count({
   *   where: {
   *     // ... the filter for the CareerPaths we want to count
   *   }
   * })
  **/
  count<T extends CareerPathCountArgs>(
    args?: Prisma.Subset<T, CareerPathCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CareerPathCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CareerPath.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CareerPathAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CareerPathAggregateArgs>(args: Prisma.Subset<T, CareerPathAggregateArgs>): Prisma.PrismaPromise<GetCareerPathAggregateType<T>>

  /**
   * Group by CareerPath.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CareerPathGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CareerPathGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CareerPathGroupByArgs['orderBy'] }
      : { orderBy?: CareerPathGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CareerPathGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCareerPathGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CareerPath model
 */
readonly fields: CareerPathFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CareerPath.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CareerPathClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  major<T extends Prisma.MajorDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MajorDefaultArgs<ExtArgs>>): Prisma.Prisma__MajorClient<runtime.Types.Result.GetResult<Prisma.$MajorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CareerPath model
 */
export interface CareerPathFieldRefs {
  readonly id: Prisma.FieldRef<"CareerPath", 'String'>
  readonly majorId: Prisma.FieldRef<"CareerPath", 'String'>
  readonly title: Prisma.FieldRef<"CareerPath", 'String'>
  readonly level: Prisma.FieldRef<"CareerPath", 'String'>
  readonly salary: Prisma.FieldRef<"CareerPath", 'String'>
  readonly skills: Prisma.FieldRef<"CareerPath", 'String'>
}
    

// Custom InputTypes
/**
 * CareerPath findUnique
 */
export type CareerPathFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerPath
   */
  select?: Prisma.CareerPathSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerPath
   */
  omit?: Prisma.CareerPathOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerPathInclude<ExtArgs> | null
  /**
   * Filter, which CareerPath to fetch.
   */
  where: Prisma.CareerPathWhereUniqueInput
}

/**
 * CareerPath findUniqueOrThrow
 */
export type CareerPathFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerPath
   */
  select?: Prisma.CareerPathSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerPath
   */
  omit?: Prisma.CareerPathOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerPathInclude<ExtArgs> | null
  /**
   * Filter, which CareerPath to fetch.
   */
  where: Prisma.CareerPathWhereUniqueInput
}

/**
 * CareerPath findFirst
 */
export type CareerPathFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerPath
   */
  select?: Prisma.CareerPathSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerPath
   */
  omit?: Prisma.CareerPathOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerPathInclude<ExtArgs> | null
  /**
   * Filter, which CareerPath to fetch.
   */
  where?: Prisma.CareerPathWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CareerPaths to fetch.
   */
  orderBy?: Prisma.CareerPathOrderByWithRelationInput | Prisma.CareerPathOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CareerPaths.
   */
  cursor?: Prisma.CareerPathWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CareerPaths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CareerPaths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CareerPaths.
   */
  distinct?: Prisma.CareerPathScalarFieldEnum | Prisma.CareerPathScalarFieldEnum[]
}

/**
 * CareerPath findFirstOrThrow
 */
export type CareerPathFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerPath
   */
  select?: Prisma.CareerPathSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerPath
   */
  omit?: Prisma.CareerPathOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerPathInclude<ExtArgs> | null
  /**
   * Filter, which CareerPath to fetch.
   */
  where?: Prisma.CareerPathWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CareerPaths to fetch.
   */
  orderBy?: Prisma.CareerPathOrderByWithRelationInput | Prisma.CareerPathOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CareerPaths.
   */
  cursor?: Prisma.CareerPathWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CareerPaths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CareerPaths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CareerPaths.
   */
  distinct?: Prisma.CareerPathScalarFieldEnum | Prisma.CareerPathScalarFieldEnum[]
}

/**
 * CareerPath findMany
 */
export type CareerPathFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerPath
   */
  select?: Prisma.CareerPathSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerPath
   */
  omit?: Prisma.CareerPathOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerPathInclude<ExtArgs> | null
  /**
   * Filter, which CareerPaths to fetch.
   */
  where?: Prisma.CareerPathWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CareerPaths to fetch.
   */
  orderBy?: Prisma.CareerPathOrderByWithRelationInput | Prisma.CareerPathOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CareerPaths.
   */
  cursor?: Prisma.CareerPathWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CareerPaths from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CareerPaths.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CareerPaths.
   */
  distinct?: Prisma.CareerPathScalarFieldEnum | Prisma.CareerPathScalarFieldEnum[]
}

/**
 * CareerPath create
 */
export type CareerPathCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerPath
   */
  select?: Prisma.CareerPathSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerPath
   */
  omit?: Prisma.CareerPathOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerPathInclude<ExtArgs> | null
  /**
   * The data needed to create a CareerPath.
   */
  data: Prisma.XOR<Prisma.CareerPathCreateInput, Prisma.CareerPathUncheckedCreateInput>
}

/**
 * CareerPath createMany
 */
export type CareerPathCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CareerPaths.
   */
  data: Prisma.CareerPathCreateManyInput | Prisma.CareerPathCreateManyInput[]
}

/**
 * CareerPath createManyAndReturn
 */
export type CareerPathCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerPath
   */
  select?: Prisma.CareerPathSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CareerPath
   */
  omit?: Prisma.CareerPathOmit<ExtArgs> | null
  /**
   * The data used to create many CareerPaths.
   */
  data: Prisma.CareerPathCreateManyInput | Prisma.CareerPathCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerPathIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CareerPath update
 */
export type CareerPathUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerPath
   */
  select?: Prisma.CareerPathSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerPath
   */
  omit?: Prisma.CareerPathOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerPathInclude<ExtArgs> | null
  /**
   * The data needed to update a CareerPath.
   */
  data: Prisma.XOR<Prisma.CareerPathUpdateInput, Prisma.CareerPathUncheckedUpdateInput>
  /**
   * Choose, which CareerPath to update.
   */
  where: Prisma.CareerPathWhereUniqueInput
}

/**
 * CareerPath updateMany
 */
export type CareerPathUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CareerPaths.
   */
  data: Prisma.XOR<Prisma.CareerPathUpdateManyMutationInput, Prisma.CareerPathUncheckedUpdateManyInput>
  /**
   * Filter which CareerPaths to update
   */
  where?: Prisma.CareerPathWhereInput
  /**
   * Limit how many CareerPaths to update.
   */
  limit?: number
}

/**
 * CareerPath updateManyAndReturn
 */
export type CareerPathUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerPath
   */
  select?: Prisma.CareerPathSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CareerPath
   */
  omit?: Prisma.CareerPathOmit<ExtArgs> | null
  /**
   * The data used to update CareerPaths.
   */
  data: Prisma.XOR<Prisma.CareerPathUpdateManyMutationInput, Prisma.CareerPathUncheckedUpdateManyInput>
  /**
   * Filter which CareerPaths to update
   */
  where?: Prisma.CareerPathWhereInput
  /**
   * Limit how many CareerPaths to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerPathIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CareerPath upsert
 */
export type CareerPathUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerPath
   */
  select?: Prisma.CareerPathSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerPath
   */
  omit?: Prisma.CareerPathOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerPathInclude<ExtArgs> | null
  /**
   * The filter to search for the CareerPath to update in case it exists.
   */
  where: Prisma.CareerPathWhereUniqueInput
  /**
   * In case the CareerPath found by the `where` argument doesn't exist, create a new CareerPath with this data.
   */
  create: Prisma.XOR<Prisma.CareerPathCreateInput, Prisma.CareerPathUncheckedCreateInput>
  /**
   * In case the CareerPath was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CareerPathUpdateInput, Prisma.CareerPathUncheckedUpdateInput>
}

/**
 * CareerPath delete
 */
export type CareerPathDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerPath
   */
  select?: Prisma.CareerPathSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerPath
   */
  omit?: Prisma.CareerPathOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerPathInclude<ExtArgs> | null
  /**
   * Filter which CareerPath to delete.
   */
  where: Prisma.CareerPathWhereUniqueInput
}

/**
 * CareerPath deleteMany
 */
export type CareerPathDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CareerPaths to delete
   */
  where?: Prisma.CareerPathWhereInput
  /**
   * Limit how many CareerPaths to delete.
   */
  limit?: number
}

/**
 * CareerPath without action
 */
export type CareerPathDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerPath
   */
  select?: Prisma.CareerPathSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerPath
   */
  omit?: Prisma.CareerPathOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerPathInclude<ExtArgs> | null
}
