
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CareerDay` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CareerDay
 * 
 */
export type CareerDayModel = runtime.Types.Result.DefaultSelection<Prisma.$CareerDayPayload>

export type AggregateCareerDay = {
  _count: CareerDayCountAggregateOutputType | null
  _avg: CareerDayAvgAggregateOutputType | null
  _sum: CareerDaySumAggregateOutputType | null
  _min: CareerDayMinAggregateOutputType | null
  _max: CareerDayMaxAggregateOutputType | null
}

export type CareerDayAvgAggregateOutputType = {
  satisfaction: number | null
}

export type CareerDaySumAggregateOutputType = {
  satisfaction: number | null
}

export type CareerDayMinAggregateOutputType = {
  id: string | null
  title: string | null
  industry: string | null
  city: string | null
  experience: string | null
  education: string | null
  timeline: string | null
  salary: string | null
  expense: string | null
  monthlyJoy: string | null
  monthlyWorry: string | null
  adviceToSelf: string | null
  satisfaction: number | null
  majorId: string | null
}

export type CareerDayMaxAggregateOutputType = {
  id: string | null
  title: string | null
  industry: string | null
  city: string | null
  experience: string | null
  education: string | null
  timeline: string | null
  salary: string | null
  expense: string | null
  monthlyJoy: string | null
  monthlyWorry: string | null
  adviceToSelf: string | null
  satisfaction: number | null
  majorId: string | null
}

export type CareerDayCountAggregateOutputType = {
  id: number
  title: number
  industry: number
  city: number
  experience: number
  education: number
  timeline: number
  salary: number
  expense: number
  monthlyJoy: number
  monthlyWorry: number
  adviceToSelf: number
  satisfaction: number
  majorId: number
  _all: number
}


export type CareerDayAvgAggregateInputType = {
  satisfaction?: true
}

export type CareerDaySumAggregateInputType = {
  satisfaction?: true
}

export type CareerDayMinAggregateInputType = {
  id?: true
  title?: true
  industry?: true
  city?: true
  experience?: true
  education?: true
  timeline?: true
  salary?: true
  expense?: true
  monthlyJoy?: true
  monthlyWorry?: true
  adviceToSelf?: true
  satisfaction?: true
  majorId?: true
}

export type CareerDayMaxAggregateInputType = {
  id?: true
  title?: true
  industry?: true
  city?: true
  experience?: true
  education?: true
  timeline?: true
  salary?: true
  expense?: true
  monthlyJoy?: true
  monthlyWorry?: true
  adviceToSelf?: true
  satisfaction?: true
  majorId?: true
}

export type CareerDayCountAggregateInputType = {
  id?: true
  title?: true
  industry?: true
  city?: true
  experience?: true
  education?: true
  timeline?: true
  salary?: true
  expense?: true
  monthlyJoy?: true
  monthlyWorry?: true
  adviceToSelf?: true
  satisfaction?: true
  majorId?: true
  _all?: true
}

export type CareerDayAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CareerDay to aggregate.
   */
  where?: Prisma.CareerDayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CareerDays to fetch.
   */
  orderBy?: Prisma.CareerDayOrderByWithRelationInput | Prisma.CareerDayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CareerDayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CareerDays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CareerDays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CareerDays
  **/
  _count?: true | CareerDayCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CareerDayAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CareerDaySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CareerDayMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CareerDayMaxAggregateInputType
}

export type GetCareerDayAggregateType<T extends CareerDayAggregateArgs> = {
      [P in keyof T & keyof AggregateCareerDay]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCareerDay[P]>
    : Prisma.GetScalarType<T[P], AggregateCareerDay[P]>
}




export type CareerDayGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CareerDayWhereInput
  orderBy?: Prisma.CareerDayOrderByWithAggregationInput | Prisma.CareerDayOrderByWithAggregationInput[]
  by: Prisma.CareerDayScalarFieldEnum[] | Prisma.CareerDayScalarFieldEnum
  having?: Prisma.CareerDayScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CareerDayCountAggregateInputType | true
  _avg?: CareerDayAvgAggregateInputType
  _sum?: CareerDaySumAggregateInputType
  _min?: CareerDayMinAggregateInputType
  _max?: CareerDayMaxAggregateInputType
}

export type CareerDayGroupByOutputType = {
  id: string
  title: string
  industry: string
  city: string
  experience: string
  education: string
  timeline: string
  salary: string
  expense: string
  monthlyJoy: string
  monthlyWorry: string
  adviceToSelf: string
  satisfaction: number
  majorId: string | null
  _count: CareerDayCountAggregateOutputType | null
  _avg: CareerDayAvgAggregateOutputType | null
  _sum: CareerDaySumAggregateOutputType | null
  _min: CareerDayMinAggregateOutputType | null
  _max: CareerDayMaxAggregateOutputType | null
}

export type GetCareerDayGroupByPayload<T extends CareerDayGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CareerDayGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CareerDayGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CareerDayGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CareerDayGroupByOutputType[P]>
      }
    >
  >



export type CareerDayWhereInput = {
  AND?: Prisma.CareerDayWhereInput | Prisma.CareerDayWhereInput[]
  OR?: Prisma.CareerDayWhereInput[]
  NOT?: Prisma.CareerDayWhereInput | Prisma.CareerDayWhereInput[]
  id?: Prisma.StringFilter<"CareerDay"> | string
  title?: Prisma.StringFilter<"CareerDay"> | string
  industry?: Prisma.StringFilter<"CareerDay"> | string
  city?: Prisma.StringFilter<"CareerDay"> | string
  experience?: Prisma.StringFilter<"CareerDay"> | string
  education?: Prisma.StringFilter<"CareerDay"> | string
  timeline?: Prisma.StringFilter<"CareerDay"> | string
  salary?: Prisma.StringFilter<"CareerDay"> | string
  expense?: Prisma.StringFilter<"CareerDay"> | string
  monthlyJoy?: Prisma.StringFilter<"CareerDay"> | string
  monthlyWorry?: Prisma.StringFilter<"CareerDay"> | string
  adviceToSelf?: Prisma.StringFilter<"CareerDay"> | string
  satisfaction?: Prisma.IntFilter<"CareerDay"> | number
  majorId?: Prisma.StringNullableFilter<"CareerDay"> | string | null
  major?: Prisma.XOR<Prisma.MajorNullableScalarRelationFilter, Prisma.MajorWhereInput> | null
}

export type CareerDayOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  industry?: Prisma.SortOrder
  city?: Prisma.SortOrder
  experience?: Prisma.SortOrder
  education?: Prisma.SortOrder
  timeline?: Prisma.SortOrder
  salary?: Prisma.SortOrder
  expense?: Prisma.SortOrder
  monthlyJoy?: Prisma.SortOrder
  monthlyWorry?: Prisma.SortOrder
  adviceToSelf?: Prisma.SortOrder
  satisfaction?: Prisma.SortOrder
  majorId?: Prisma.SortOrderInput | Prisma.SortOrder
  major?: Prisma.MajorOrderByWithRelationInput
}

export type CareerDayWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CareerDayWhereInput | Prisma.CareerDayWhereInput[]
  OR?: Prisma.CareerDayWhereInput[]
  NOT?: Prisma.CareerDayWhereInput | Prisma.CareerDayWhereInput[]
  title?: Prisma.StringFilter<"CareerDay"> | string
  industry?: Prisma.StringFilter<"CareerDay"> | string
  city?: Prisma.StringFilter<"CareerDay"> | string
  experience?: Prisma.StringFilter<"CareerDay"> | string
  education?: Prisma.StringFilter<"CareerDay"> | string
  timeline?: Prisma.StringFilter<"CareerDay"> | string
  salary?: Prisma.StringFilter<"CareerDay"> | string
  expense?: Prisma.StringFilter<"CareerDay"> | string
  monthlyJoy?: Prisma.StringFilter<"CareerDay"> | string
  monthlyWorry?: Prisma.StringFilter<"CareerDay"> | string
  adviceToSelf?: Prisma.StringFilter<"CareerDay"> | string
  satisfaction?: Prisma.IntFilter<"CareerDay"> | number
  majorId?: Prisma.StringNullableFilter<"CareerDay"> | string | null
  major?: Prisma.XOR<Prisma.MajorNullableScalarRelationFilter, Prisma.MajorWhereInput> | null
}, "id">

export type CareerDayOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  industry?: Prisma.SortOrder
  city?: Prisma.SortOrder
  experience?: Prisma.SortOrder
  education?: Prisma.SortOrder
  timeline?: Prisma.SortOrder
  salary?: Prisma.SortOrder
  expense?: Prisma.SortOrder
  monthlyJoy?: Prisma.SortOrder
  monthlyWorry?: Prisma.SortOrder
  adviceToSelf?: Prisma.SortOrder
  satisfaction?: Prisma.SortOrder
  majorId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.CareerDayCountOrderByAggregateInput
  _avg?: Prisma.CareerDayAvgOrderByAggregateInput
  _max?: Prisma.CareerDayMaxOrderByAggregateInput
  _min?: Prisma.CareerDayMinOrderByAggregateInput
  _sum?: Prisma.CareerDaySumOrderByAggregateInput
}

export type CareerDayScalarWhereWithAggregatesInput = {
  AND?: Prisma.CareerDayScalarWhereWithAggregatesInput | Prisma.CareerDayScalarWhereWithAggregatesInput[]
  OR?: Prisma.CareerDayScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CareerDayScalarWhereWithAggregatesInput | Prisma.CareerDayScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CareerDay"> | string
  title?: Prisma.StringWithAggregatesFilter<"CareerDay"> | string
  industry?: Prisma.StringWithAggregatesFilter<"CareerDay"> | string
  city?: Prisma.StringWithAggregatesFilter<"CareerDay"> | string
  experience?: Prisma.StringWithAggregatesFilter<"CareerDay"> | string
  education?: Prisma.StringWithAggregatesFilter<"CareerDay"> | string
  timeline?: Prisma.StringWithAggregatesFilter<"CareerDay"> | string
  salary?: Prisma.StringWithAggregatesFilter<"CareerDay"> | string
  expense?: Prisma.StringWithAggregatesFilter<"CareerDay"> | string
  monthlyJoy?: Prisma.StringWithAggregatesFilter<"CareerDay"> | string
  monthlyWorry?: Prisma.StringWithAggregatesFilter<"CareerDay"> | string
  adviceToSelf?: Prisma.StringWithAggregatesFilter<"CareerDay"> | string
  satisfaction?: Prisma.IntWithAggregatesFilter<"CareerDay"> | number
  majorId?: Prisma.StringNullableWithAggregatesFilter<"CareerDay"> | string | null
}

export type CareerDayCreateInput = {
  id?: string
  title: string
  industry: string
  city: string
  experience: string
  education: string
  timeline: string
  salary: string
  expense: string
  monthlyJoy: string
  monthlyWorry: string
  adviceToSelf: string
  satisfaction: number
  major?: Prisma.MajorCreateNestedOneWithoutCareerDaysInput
}

export type CareerDayUncheckedCreateInput = {
  id?: string
  title: string
  industry: string
  city: string
  experience: string
  education: string
  timeline: string
  salary: string
  expense: string
  monthlyJoy: string
  monthlyWorry: string
  adviceToSelf: string
  satisfaction: number
  majorId?: string | null
}

export type CareerDayUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  industry?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  experience?: Prisma.StringFieldUpdateOperationsInput | string
  education?: Prisma.StringFieldUpdateOperationsInput | string
  timeline?: Prisma.StringFieldUpdateOperationsInput | string
  salary?: Prisma.StringFieldUpdateOperationsInput | string
  expense?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyJoy?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyWorry?: Prisma.StringFieldUpdateOperationsInput | string
  adviceToSelf?: Prisma.StringFieldUpdateOperationsInput | string
  satisfaction?: Prisma.IntFieldUpdateOperationsInput | number
  major?: Prisma.MajorUpdateOneWithoutCareerDaysNestedInput
}

export type CareerDayUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  industry?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  experience?: Prisma.StringFieldUpdateOperationsInput | string
  education?: Prisma.StringFieldUpdateOperationsInput | string
  timeline?: Prisma.StringFieldUpdateOperationsInput | string
  salary?: Prisma.StringFieldUpdateOperationsInput | string
  expense?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyJoy?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyWorry?: Prisma.StringFieldUpdateOperationsInput | string
  adviceToSelf?: Prisma.StringFieldUpdateOperationsInput | string
  satisfaction?: Prisma.IntFieldUpdateOperationsInput | number
  majorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type CareerDayCreateManyInput = {
  id?: string
  title: string
  industry: string
  city: string
  experience: string
  education: string
  timeline: string
  salary: string
  expense: string
  monthlyJoy: string
  monthlyWorry: string
  adviceToSelf: string
  satisfaction: number
  majorId?: string | null
}

export type CareerDayUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  industry?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  experience?: Prisma.StringFieldUpdateOperationsInput | string
  education?: Prisma.StringFieldUpdateOperationsInput | string
  timeline?: Prisma.StringFieldUpdateOperationsInput | string
  salary?: Prisma.StringFieldUpdateOperationsInput | string
  expense?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyJoy?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyWorry?: Prisma.StringFieldUpdateOperationsInput | string
  adviceToSelf?: Prisma.StringFieldUpdateOperationsInput | string
  satisfaction?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CareerDayUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  industry?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  experience?: Prisma.StringFieldUpdateOperationsInput | string
  education?: Prisma.StringFieldUpdateOperationsInput | string
  timeline?: Prisma.StringFieldUpdateOperationsInput | string
  salary?: Prisma.StringFieldUpdateOperationsInput | string
  expense?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyJoy?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyWorry?: Prisma.StringFieldUpdateOperationsInput | string
  adviceToSelf?: Prisma.StringFieldUpdateOperationsInput | string
  satisfaction?: Prisma.IntFieldUpdateOperationsInput | number
  majorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type CareerDayListRelationFilter = {
  every?: Prisma.CareerDayWhereInput
  some?: Prisma.CareerDayWhereInput
  none?: Prisma.CareerDayWhereInput
}

export type CareerDayOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CareerDayCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  industry?: Prisma.SortOrder
  city?: Prisma.SortOrder
  experience?: Prisma.SortOrder
  education?: Prisma.SortOrder
  timeline?: Prisma.SortOrder
  salary?: Prisma.SortOrder
  expense?: Prisma.SortOrder
  monthlyJoy?: Prisma.SortOrder
  monthlyWorry?: Prisma.SortOrder
  adviceToSelf?: Prisma.SortOrder
  satisfaction?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
}

export type CareerDayAvgOrderByAggregateInput = {
  satisfaction?: Prisma.SortOrder
}

export type CareerDayMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  industry?: Prisma.SortOrder
  city?: Prisma.SortOrder
  experience?: Prisma.SortOrder
  education?: Prisma.SortOrder
  timeline?: Prisma.SortOrder
  salary?: Prisma.SortOrder
  expense?: Prisma.SortOrder
  monthlyJoy?: Prisma.SortOrder
  monthlyWorry?: Prisma.SortOrder
  adviceToSelf?: Prisma.SortOrder
  satisfaction?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
}

export type CareerDayMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  industry?: Prisma.SortOrder
  city?: Prisma.SortOrder
  experience?: Prisma.SortOrder
  education?: Prisma.SortOrder
  timeline?: Prisma.SortOrder
  salary?: Prisma.SortOrder
  expense?: Prisma.SortOrder
  monthlyJoy?: Prisma.SortOrder
  monthlyWorry?: Prisma.SortOrder
  adviceToSelf?: Prisma.SortOrder
  satisfaction?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
}

export type CareerDaySumOrderByAggregateInput = {
  satisfaction?: Prisma.SortOrder
}

export type CareerDayCreateNestedManyWithoutMajorInput = {
  create?: Prisma.XOR<Prisma.CareerDayCreateWithoutMajorInput, Prisma.CareerDayUncheckedCreateWithoutMajorInput> | Prisma.CareerDayCreateWithoutMajorInput[] | Prisma.CareerDayUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.CareerDayCreateOrConnectWithoutMajorInput | Prisma.CareerDayCreateOrConnectWithoutMajorInput[]
  createMany?: Prisma.CareerDayCreateManyMajorInputEnvelope
  connect?: Prisma.CareerDayWhereUniqueInput | Prisma.CareerDayWhereUniqueInput[]
}

export type CareerDayUncheckedCreateNestedManyWithoutMajorInput = {
  create?: Prisma.XOR<Prisma.CareerDayCreateWithoutMajorInput, Prisma.CareerDayUncheckedCreateWithoutMajorInput> | Prisma.CareerDayCreateWithoutMajorInput[] | Prisma.CareerDayUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.CareerDayCreateOrConnectWithoutMajorInput | Prisma.CareerDayCreateOrConnectWithoutMajorInput[]
  createMany?: Prisma.CareerDayCreateManyMajorInputEnvelope
  connect?: Prisma.CareerDayWhereUniqueInput | Prisma.CareerDayWhereUniqueInput[]
}

export type CareerDayUpdateManyWithoutMajorNestedInput = {
  create?: Prisma.XOR<Prisma.CareerDayCreateWithoutMajorInput, Prisma.CareerDayUncheckedCreateWithoutMajorInput> | Prisma.CareerDayCreateWithoutMajorInput[] | Prisma.CareerDayUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.CareerDayCreateOrConnectWithoutMajorInput | Prisma.CareerDayCreateOrConnectWithoutMajorInput[]
  upsert?: Prisma.CareerDayUpsertWithWhereUniqueWithoutMajorInput | Prisma.CareerDayUpsertWithWhereUniqueWithoutMajorInput[]
  createMany?: Prisma.CareerDayCreateManyMajorInputEnvelope
  set?: Prisma.CareerDayWhereUniqueInput | Prisma.CareerDayWhereUniqueInput[]
  disconnect?: Prisma.CareerDayWhereUniqueInput | Prisma.CareerDayWhereUniqueInput[]
  delete?: Prisma.CareerDayWhereUniqueInput | Prisma.CareerDayWhereUniqueInput[]
  connect?: Prisma.CareerDayWhereUniqueInput | Prisma.CareerDayWhereUniqueInput[]
  update?: Prisma.CareerDayUpdateWithWhereUniqueWithoutMajorInput | Prisma.CareerDayUpdateWithWhereUniqueWithoutMajorInput[]
  updateMany?: Prisma.CareerDayUpdateManyWithWhereWithoutMajorInput | Prisma.CareerDayUpdateManyWithWhereWithoutMajorInput[]
  deleteMany?: Prisma.CareerDayScalarWhereInput | Prisma.CareerDayScalarWhereInput[]
}

export type CareerDayUncheckedUpdateManyWithoutMajorNestedInput = {
  create?: Prisma.XOR<Prisma.CareerDayCreateWithoutMajorInput, Prisma.CareerDayUncheckedCreateWithoutMajorInput> | Prisma.CareerDayCreateWithoutMajorInput[] | Prisma.CareerDayUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.CareerDayCreateOrConnectWithoutMajorInput | Prisma.CareerDayCreateOrConnectWithoutMajorInput[]
  upsert?: Prisma.CareerDayUpsertWithWhereUniqueWithoutMajorInput | Prisma.CareerDayUpsertWithWhereUniqueWithoutMajorInput[]
  createMany?: Prisma.CareerDayCreateManyMajorInputEnvelope
  set?: Prisma.CareerDayWhereUniqueInput | Prisma.CareerDayWhereUniqueInput[]
  disconnect?: Prisma.CareerDayWhereUniqueInput | Prisma.CareerDayWhereUniqueInput[]
  delete?: Prisma.CareerDayWhereUniqueInput | Prisma.CareerDayWhereUniqueInput[]
  connect?: Prisma.CareerDayWhereUniqueInput | Prisma.CareerDayWhereUniqueInput[]
  update?: Prisma.CareerDayUpdateWithWhereUniqueWithoutMajorInput | Prisma.CareerDayUpdateWithWhereUniqueWithoutMajorInput[]
  updateMany?: Prisma.CareerDayUpdateManyWithWhereWithoutMajorInput | Prisma.CareerDayUpdateManyWithWhereWithoutMajorInput[]
  deleteMany?: Prisma.CareerDayScalarWhereInput | Prisma.CareerDayScalarWhereInput[]
}

export type CareerDayCreateWithoutMajorInput = {
  id?: string
  title: string
  industry: string
  city: string
  experience: string
  education: string
  timeline: string
  salary: string
  expense: string
  monthlyJoy: string
  monthlyWorry: string
  adviceToSelf: string
  satisfaction: number
}

export type CareerDayUncheckedCreateWithoutMajorInput = {
  id?: string
  title: string
  industry: string
  city: string
  experience: string
  education: string
  timeline: string
  salary: string
  expense: string
  monthlyJoy: string
  monthlyWorry: string
  adviceToSelf: string
  satisfaction: number
}

export type CareerDayCreateOrConnectWithoutMajorInput = {
  where: Prisma.CareerDayWhereUniqueInput
  create: Prisma.XOR<Prisma.CareerDayCreateWithoutMajorInput, Prisma.CareerDayUncheckedCreateWithoutMajorInput>
}

export type CareerDayCreateManyMajorInputEnvelope = {
  data: Prisma.CareerDayCreateManyMajorInput | Prisma.CareerDayCreateManyMajorInput[]
}

export type CareerDayUpsertWithWhereUniqueWithoutMajorInput = {
  where: Prisma.CareerDayWhereUniqueInput
  update: Prisma.XOR<Prisma.CareerDayUpdateWithoutMajorInput, Prisma.CareerDayUncheckedUpdateWithoutMajorInput>
  create: Prisma.XOR<Prisma.CareerDayCreateWithoutMajorInput, Prisma.CareerDayUncheckedCreateWithoutMajorInput>
}

export type CareerDayUpdateWithWhereUniqueWithoutMajorInput = {
  where: Prisma.CareerDayWhereUniqueInput
  data: Prisma.XOR<Prisma.CareerDayUpdateWithoutMajorInput, Prisma.CareerDayUncheckedUpdateWithoutMajorInput>
}

export type CareerDayUpdateManyWithWhereWithoutMajorInput = {
  where: Prisma.CareerDayScalarWhereInput
  data: Prisma.XOR<Prisma.CareerDayUpdateManyMutationInput, Prisma.CareerDayUncheckedUpdateManyWithoutMajorInput>
}

export type CareerDayScalarWhereInput = {
  AND?: Prisma.CareerDayScalarWhereInput | Prisma.CareerDayScalarWhereInput[]
  OR?: Prisma.CareerDayScalarWhereInput[]
  NOT?: Prisma.CareerDayScalarWhereInput | Prisma.CareerDayScalarWhereInput[]
  id?: Prisma.StringFilter<"CareerDay"> | string
  title?: Prisma.StringFilter<"CareerDay"> | string
  industry?: Prisma.StringFilter<"CareerDay"> | string
  city?: Prisma.StringFilter<"CareerDay"> | string
  experience?: Prisma.StringFilter<"CareerDay"> | string
  education?: Prisma.StringFilter<"CareerDay"> | string
  timeline?: Prisma.StringFilter<"CareerDay"> | string
  salary?: Prisma.StringFilter<"CareerDay"> | string
  expense?: Prisma.StringFilter<"CareerDay"> | string
  monthlyJoy?: Prisma.StringFilter<"CareerDay"> | string
  monthlyWorry?: Prisma.StringFilter<"CareerDay"> | string
  adviceToSelf?: Prisma.StringFilter<"CareerDay"> | string
  satisfaction?: Prisma.IntFilter<"CareerDay"> | number
  majorId?: Prisma.StringNullableFilter<"CareerDay"> | string | null
}

export type CareerDayCreateManyMajorInput = {
  id?: string
  title: string
  industry: string
  city: string
  experience: string
  education: string
  timeline: string
  salary: string
  expense: string
  monthlyJoy: string
  monthlyWorry: string
  adviceToSelf: string
  satisfaction: number
}

export type CareerDayUpdateWithoutMajorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  industry?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  experience?: Prisma.StringFieldUpdateOperationsInput | string
  education?: Prisma.StringFieldUpdateOperationsInput | string
  timeline?: Prisma.StringFieldUpdateOperationsInput | string
  salary?: Prisma.StringFieldUpdateOperationsInput | string
  expense?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyJoy?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyWorry?: Prisma.StringFieldUpdateOperationsInput | string
  adviceToSelf?: Prisma.StringFieldUpdateOperationsInput | string
  satisfaction?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CareerDayUncheckedUpdateWithoutMajorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  industry?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  experience?: Prisma.StringFieldUpdateOperationsInput | string
  education?: Prisma.StringFieldUpdateOperationsInput | string
  timeline?: Prisma.StringFieldUpdateOperationsInput | string
  salary?: Prisma.StringFieldUpdateOperationsInput | string
  expense?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyJoy?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyWorry?: Prisma.StringFieldUpdateOperationsInput | string
  adviceToSelf?: Prisma.StringFieldUpdateOperationsInput | string
  satisfaction?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CareerDayUncheckedUpdateManyWithoutMajorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  industry?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  experience?: Prisma.StringFieldUpdateOperationsInput | string
  education?: Prisma.StringFieldUpdateOperationsInput | string
  timeline?: Prisma.StringFieldUpdateOperationsInput | string
  salary?: Prisma.StringFieldUpdateOperationsInput | string
  expense?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyJoy?: Prisma.StringFieldUpdateOperationsInput | string
  monthlyWorry?: Prisma.StringFieldUpdateOperationsInput | string
  adviceToSelf?: Prisma.StringFieldUpdateOperationsInput | string
  satisfaction?: Prisma.IntFieldUpdateOperationsInput | number
}



export type CareerDaySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  industry?: boolean
  city?: boolean
  experience?: boolean
  education?: boolean
  timeline?: boolean
  salary?: boolean
  expense?: boolean
  monthlyJoy?: boolean
  monthlyWorry?: boolean
  adviceToSelf?: boolean
  satisfaction?: boolean
  majorId?: boolean
  major?: boolean | Prisma.CareerDay$majorArgs<ExtArgs>
}, ExtArgs["result"]["careerDay"]>

export type CareerDaySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  industry?: boolean
  city?: boolean
  experience?: boolean
  education?: boolean
  timeline?: boolean
  salary?: boolean
  expense?: boolean
  monthlyJoy?: boolean
  monthlyWorry?: boolean
  adviceToSelf?: boolean
  satisfaction?: boolean
  majorId?: boolean
  major?: boolean | Prisma.CareerDay$majorArgs<ExtArgs>
}, ExtArgs["result"]["careerDay"]>

export type CareerDaySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  industry?: boolean
  city?: boolean
  experience?: boolean
  education?: boolean
  timeline?: boolean
  salary?: boolean
  expense?: boolean
  monthlyJoy?: boolean
  monthlyWorry?: boolean
  adviceToSelf?: boolean
  satisfaction?: boolean
  majorId?: boolean
  major?: boolean | Prisma.CareerDay$majorArgs<ExtArgs>
}, ExtArgs["result"]["careerDay"]>

export type CareerDaySelectScalar = {
  id?: boolean
  title?: boolean
  industry?: boolean
  city?: boolean
  experience?: boolean
  education?: boolean
  timeline?: boolean
  salary?: boolean
  expense?: boolean
  monthlyJoy?: boolean
  monthlyWorry?: boolean
  adviceToSelf?: boolean
  satisfaction?: boolean
  majorId?: boolean
}

export type CareerDayOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "industry" | "city" | "experience" | "education" | "timeline" | "salary" | "expense" | "monthlyJoy" | "monthlyWorry" | "adviceToSelf" | "satisfaction" | "majorId", ExtArgs["result"]["careerDay"]>
export type CareerDayInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  major?: boolean | Prisma.CareerDay$majorArgs<ExtArgs>
}
export type CareerDayIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  major?: boolean | Prisma.CareerDay$majorArgs<ExtArgs>
}
export type CareerDayIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  major?: boolean | Prisma.CareerDay$majorArgs<ExtArgs>
}

export type $CareerDayPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CareerDay"
  objects: {
    major: Prisma.$MajorPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    industry: string
    city: string
    experience: string
    education: string
    timeline: string
    salary: string
    expense: string
    monthlyJoy: string
    monthlyWorry: string
    adviceToSelf: string
    satisfaction: number
    majorId: string | null
  }, ExtArgs["result"]["careerDay"]>
  composites: {}
}

export type CareerDayGetPayload<S extends boolean | null | undefined | CareerDayDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CareerDayPayload, S>

export type CareerDayCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CareerDayFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CareerDayCountAggregateInputType | true
  }

export interface CareerDayDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CareerDay'], meta: { name: 'CareerDay' } }
  /**
   * Find zero or one CareerDay that matches the filter.
   * @param {CareerDayFindUniqueArgs} args - Arguments to find a CareerDay
   * @example
   * // Get one CareerDay
   * const careerDay = await prisma.careerDay.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CareerDayFindUniqueArgs>(args: Prisma.SelectSubset<T, CareerDayFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CareerDayClient<runtime.Types.Result.GetResult<Prisma.$CareerDayPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CareerDay that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CareerDayFindUniqueOrThrowArgs} args - Arguments to find a CareerDay
   * @example
   * // Get one CareerDay
   * const careerDay = await prisma.careerDay.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CareerDayFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CareerDayFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CareerDayClient<runtime.Types.Result.GetResult<Prisma.$CareerDayPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CareerDay that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CareerDayFindFirstArgs} args - Arguments to find a CareerDay
   * @example
   * // Get one CareerDay
   * const careerDay = await prisma.careerDay.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CareerDayFindFirstArgs>(args?: Prisma.SelectSubset<T, CareerDayFindFirstArgs<ExtArgs>>): Prisma.Prisma__CareerDayClient<runtime.Types.Result.GetResult<Prisma.$CareerDayPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CareerDay that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CareerDayFindFirstOrThrowArgs} args - Arguments to find a CareerDay
   * @example
   * // Get one CareerDay
   * const careerDay = await prisma.careerDay.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CareerDayFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CareerDayFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CareerDayClient<runtime.Types.Result.GetResult<Prisma.$CareerDayPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CareerDays that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CareerDayFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CareerDays
   * const careerDays = await prisma.careerDay.findMany()
   * 
   * // Get first 10 CareerDays
   * const careerDays = await prisma.careerDay.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const careerDayWithIdOnly = await prisma.careerDay.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CareerDayFindManyArgs>(args?: Prisma.SelectSubset<T, CareerDayFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CareerDayPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CareerDay.
   * @param {CareerDayCreateArgs} args - Arguments to create a CareerDay.
   * @example
   * // Create one CareerDay
   * const CareerDay = await prisma.careerDay.create({
   *   data: {
   *     // ... data to create a CareerDay
   *   }
   * })
   * 
   */
  create<T extends CareerDayCreateArgs>(args: Prisma.SelectSubset<T, CareerDayCreateArgs<ExtArgs>>): Prisma.Prisma__CareerDayClient<runtime.Types.Result.GetResult<Prisma.$CareerDayPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CareerDays.
   * @param {CareerDayCreateManyArgs} args - Arguments to create many CareerDays.
   * @example
   * // Create many CareerDays
   * const careerDay = await prisma.careerDay.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CareerDayCreateManyArgs>(args?: Prisma.SelectSubset<T, CareerDayCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CareerDays and returns the data saved in the database.
   * @param {CareerDayCreateManyAndReturnArgs} args - Arguments to create many CareerDays.
   * @example
   * // Create many CareerDays
   * const careerDay = await prisma.careerDay.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CareerDays and only return the `id`
   * const careerDayWithIdOnly = await prisma.careerDay.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CareerDayCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CareerDayCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CareerDayPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CareerDay.
   * @param {CareerDayDeleteArgs} args - Arguments to delete one CareerDay.
   * @example
   * // Delete one CareerDay
   * const CareerDay = await prisma.careerDay.delete({
   *   where: {
   *     // ... filter to delete one CareerDay
   *   }
   * })
   * 
   */
  delete<T extends CareerDayDeleteArgs>(args: Prisma.SelectSubset<T, CareerDayDeleteArgs<ExtArgs>>): Prisma.Prisma__CareerDayClient<runtime.Types.Result.GetResult<Prisma.$CareerDayPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CareerDay.
   * @param {CareerDayUpdateArgs} args - Arguments to update one CareerDay.
   * @example
   * // Update one CareerDay
   * const careerDay = await prisma.careerDay.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CareerDayUpdateArgs>(args: Prisma.SelectSubset<T, CareerDayUpdateArgs<ExtArgs>>): Prisma.Prisma__CareerDayClient<runtime.Types.Result.GetResult<Prisma.$CareerDayPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CareerDays.
   * @param {CareerDayDeleteManyArgs} args - Arguments to filter CareerDays to delete.
   * @example
   * // Delete a few CareerDays
   * const { count } = await prisma.careerDay.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CareerDayDeleteManyArgs>(args?: Prisma.SelectSubset<T, CareerDayDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CareerDays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CareerDayUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CareerDays
   * const careerDay = await prisma.careerDay.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CareerDayUpdateManyArgs>(args: Prisma.SelectSubset<T, CareerDayUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CareerDays and returns the data updated in the database.
   * @param {CareerDayUpdateManyAndReturnArgs} args - Arguments to update many CareerDays.
   * @example
   * // Update many CareerDays
   * const careerDay = await prisma.careerDay.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CareerDays and only return the `id`
   * const careerDayWithIdOnly = await prisma.careerDay.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CareerDayUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CareerDayUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CareerDayPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CareerDay.
   * @param {CareerDayUpsertArgs} args - Arguments to update or create a CareerDay.
   * @example
   * // Update or create a CareerDay
   * const careerDay = await prisma.careerDay.upsert({
   *   create: {
   *     // ... data to create a CareerDay
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CareerDay we want to update
   *   }
   * })
   */
  upsert<T extends CareerDayUpsertArgs>(args: Prisma.SelectSubset<T, CareerDayUpsertArgs<ExtArgs>>): Prisma.Prisma__CareerDayClient<runtime.Types.Result.GetResult<Prisma.$CareerDayPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CareerDays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CareerDayCountArgs} args - Arguments to filter CareerDays to count.
   * @example
   * // Count the number of CareerDays
   * const count = await prisma.careerDay.count({
   *   where: {
   *     // ... the filter for the CareerDays we want to count
   *   }
   * })
  **/
  count<T extends CareerDayCountArgs>(
    args?: Prisma.Subset<T, CareerDayCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CareerDayCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CareerDay.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CareerDayAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CareerDayAggregateArgs>(args: Prisma.Subset<T, CareerDayAggregateArgs>): Prisma.PrismaPromise<GetCareerDayAggregateType<T>>

  /**
   * Group by CareerDay.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CareerDayGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CareerDayGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CareerDayGroupByArgs['orderBy'] }
      : { orderBy?: CareerDayGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CareerDayGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCareerDayGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CareerDay model
 */
readonly fields: CareerDayFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CareerDay.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CareerDayClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  major<T extends Prisma.CareerDay$majorArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CareerDay$majorArgs<ExtArgs>>): Prisma.Prisma__MajorClient<runtime.Types.Result.GetResult<Prisma.$MajorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CareerDay model
 */
export interface CareerDayFieldRefs {
  readonly id: Prisma.FieldRef<"CareerDay", 'String'>
  readonly title: Prisma.FieldRef<"CareerDay", 'String'>
  readonly industry: Prisma.FieldRef<"CareerDay", 'String'>
  readonly city: Prisma.FieldRef<"CareerDay", 'String'>
  readonly experience: Prisma.FieldRef<"CareerDay", 'String'>
  readonly education: Prisma.FieldRef<"CareerDay", 'String'>
  readonly timeline: Prisma.FieldRef<"CareerDay", 'String'>
  readonly salary: Prisma.FieldRef<"CareerDay", 'String'>
  readonly expense: Prisma.FieldRef<"CareerDay", 'String'>
  readonly monthlyJoy: Prisma.FieldRef<"CareerDay", 'String'>
  readonly monthlyWorry: Prisma.FieldRef<"CareerDay", 'String'>
  readonly adviceToSelf: Prisma.FieldRef<"CareerDay", 'String'>
  readonly satisfaction: Prisma.FieldRef<"CareerDay", 'Int'>
  readonly majorId: Prisma.FieldRef<"CareerDay", 'String'>
}
    

// Custom InputTypes
/**
 * CareerDay findUnique
 */
export type CareerDayFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerDay
   */
  select?: Prisma.CareerDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerDay
   */
  omit?: Prisma.CareerDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerDayInclude<ExtArgs> | null
  /**
   * Filter, which CareerDay to fetch.
   */
  where: Prisma.CareerDayWhereUniqueInput
}

/**
 * CareerDay findUniqueOrThrow
 */
export type CareerDayFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerDay
   */
  select?: Prisma.CareerDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerDay
   */
  omit?: Prisma.CareerDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerDayInclude<ExtArgs> | null
  /**
   * Filter, which CareerDay to fetch.
   */
  where: Prisma.CareerDayWhereUniqueInput
}

/**
 * CareerDay findFirst
 */
export type CareerDayFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerDay
   */
  select?: Prisma.CareerDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerDay
   */
  omit?: Prisma.CareerDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerDayInclude<ExtArgs> | null
  /**
   * Filter, which CareerDay to fetch.
   */
  where?: Prisma.CareerDayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CareerDays to fetch.
   */
  orderBy?: Prisma.CareerDayOrderByWithRelationInput | Prisma.CareerDayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CareerDays.
   */
  cursor?: Prisma.CareerDayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CareerDays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CareerDays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CareerDays.
   */
  distinct?: Prisma.CareerDayScalarFieldEnum | Prisma.CareerDayScalarFieldEnum[]
}

/**
 * CareerDay findFirstOrThrow
 */
export type CareerDayFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerDay
   */
  select?: Prisma.CareerDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerDay
   */
  omit?: Prisma.CareerDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerDayInclude<ExtArgs> | null
  /**
   * Filter, which CareerDay to fetch.
   */
  where?: Prisma.CareerDayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CareerDays to fetch.
   */
  orderBy?: Prisma.CareerDayOrderByWithRelationInput | Prisma.CareerDayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CareerDays.
   */
  cursor?: Prisma.CareerDayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CareerDays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CareerDays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CareerDays.
   */
  distinct?: Prisma.CareerDayScalarFieldEnum | Prisma.CareerDayScalarFieldEnum[]
}

/**
 * CareerDay findMany
 */
export type CareerDayFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerDay
   */
  select?: Prisma.CareerDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerDay
   */
  omit?: Prisma.CareerDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerDayInclude<ExtArgs> | null
  /**
   * Filter, which CareerDays to fetch.
   */
  where?: Prisma.CareerDayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CareerDays to fetch.
   */
  orderBy?: Prisma.CareerDayOrderByWithRelationInput | Prisma.CareerDayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CareerDays.
   */
  cursor?: Prisma.CareerDayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CareerDays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CareerDays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CareerDays.
   */
  distinct?: Prisma.CareerDayScalarFieldEnum | Prisma.CareerDayScalarFieldEnum[]
}

/**
 * CareerDay create
 */
export type CareerDayCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerDay
   */
  select?: Prisma.CareerDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerDay
   */
  omit?: Prisma.CareerDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerDayInclude<ExtArgs> | null
  /**
   * The data needed to create a CareerDay.
   */
  data: Prisma.XOR<Prisma.CareerDayCreateInput, Prisma.CareerDayUncheckedCreateInput>
}

/**
 * CareerDay createMany
 */
export type CareerDayCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CareerDays.
   */
  data: Prisma.CareerDayCreateManyInput | Prisma.CareerDayCreateManyInput[]
}

/**
 * CareerDay createManyAndReturn
 */
export type CareerDayCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerDay
   */
  select?: Prisma.CareerDaySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CareerDay
   */
  omit?: Prisma.CareerDayOmit<ExtArgs> | null
  /**
   * The data used to create many CareerDays.
   */
  data: Prisma.CareerDayCreateManyInput | Prisma.CareerDayCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerDayIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CareerDay update
 */
export type CareerDayUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerDay
   */
  select?: Prisma.CareerDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerDay
   */
  omit?: Prisma.CareerDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerDayInclude<ExtArgs> | null
  /**
   * The data needed to update a CareerDay.
   */
  data: Prisma.XOR<Prisma.CareerDayUpdateInput, Prisma.CareerDayUncheckedUpdateInput>
  /**
   * Choose, which CareerDay to update.
   */
  where: Prisma.CareerDayWhereUniqueInput
}

/**
 * CareerDay updateMany
 */
export type CareerDayUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CareerDays.
   */
  data: Prisma.XOR<Prisma.CareerDayUpdateManyMutationInput, Prisma.CareerDayUncheckedUpdateManyInput>
  /**
   * Filter which CareerDays to update
   */
  where?: Prisma.CareerDayWhereInput
  /**
   * Limit how many CareerDays to update.
   */
  limit?: number
}

/**
 * CareerDay updateManyAndReturn
 */
export type CareerDayUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerDay
   */
  select?: Prisma.CareerDaySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CareerDay
   */
  omit?: Prisma.CareerDayOmit<ExtArgs> | null
  /**
   * The data used to update CareerDays.
   */
  data: Prisma.XOR<Prisma.CareerDayUpdateManyMutationInput, Prisma.CareerDayUncheckedUpdateManyInput>
  /**
   * Filter which CareerDays to update
   */
  where?: Prisma.CareerDayWhereInput
  /**
   * Limit how many CareerDays to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerDayIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CareerDay upsert
 */
export type CareerDayUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerDay
   */
  select?: Prisma.CareerDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerDay
   */
  omit?: Prisma.CareerDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerDayInclude<ExtArgs> | null
  /**
   * The filter to search for the CareerDay to update in case it exists.
   */
  where: Prisma.CareerDayWhereUniqueInput
  /**
   * In case the CareerDay found by the `where` argument doesn't exist, create a new CareerDay with this data.
   */
  create: Prisma.XOR<Prisma.CareerDayCreateInput, Prisma.CareerDayUncheckedCreateInput>
  /**
   * In case the CareerDay was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CareerDayUpdateInput, Prisma.CareerDayUncheckedUpdateInput>
}

/**
 * CareerDay delete
 */
export type CareerDayDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerDay
   */
  select?: Prisma.CareerDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerDay
   */
  omit?: Prisma.CareerDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerDayInclude<ExtArgs> | null
  /**
   * Filter which CareerDay to delete.
   */
  where: Prisma.CareerDayWhereUniqueInput
}

/**
 * CareerDay deleteMany
 */
export type CareerDayDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CareerDays to delete
   */
  where?: Prisma.CareerDayWhereInput
  /**
   * Limit how many CareerDays to delete.
   */
  limit?: number
}

/**
 * CareerDay.major
 */
export type CareerDay$majorArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Major
   */
  select?: Prisma.MajorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Major
   */
  omit?: Prisma.MajorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorInclude<ExtArgs> | null
  where?: Prisma.MajorWhereInput
}

/**
 * CareerDay without action
 */
export type CareerDayDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerDay
   */
  select?: Prisma.CareerDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerDay
   */
  omit?: Prisma.CareerDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerDayInclude<ExtArgs> | null
}
