
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `EmploymentStat` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model EmploymentStat
 * 
 */
export type EmploymentStatModel = runtime.Types.Result.DefaultSelection<Prisma.$EmploymentStatPayload>

export type AggregateEmploymentStat = {
  _count: EmploymentStatCountAggregateOutputType | null
  _avg: EmploymentStatAvgAggregateOutputType | null
  _sum: EmploymentStatSumAggregateOutputType | null
  _min: EmploymentStatMinAggregateOutputType | null
  _max: EmploymentStatMaxAggregateOutputType | null
}

export type EmploymentStatAvgAggregateOutputType = {
  ratio: number | null
}

export type EmploymentStatSumAggregateOutputType = {
  ratio: number | null
}

export type EmploymentStatMinAggregateOutputType = {
  id: string | null
  majorId: string | null
  industry: string | null
  ratio: number | null
  cityDistribution: string | null
}

export type EmploymentStatMaxAggregateOutputType = {
  id: string | null
  majorId: string | null
  industry: string | null
  ratio: number | null
  cityDistribution: string | null
}

export type EmploymentStatCountAggregateOutputType = {
  id: number
  majorId: number
  industry: number
  ratio: number
  cityDistribution: number
  _all: number
}


export type EmploymentStatAvgAggregateInputType = {
  ratio?: true
}

export type EmploymentStatSumAggregateInputType = {
  ratio?: true
}

export type EmploymentStatMinAggregateInputType = {
  id?: true
  majorId?: true
  industry?: true
  ratio?: true
  cityDistribution?: true
}

export type EmploymentStatMaxAggregateInputType = {
  id?: true
  majorId?: true
  industry?: true
  ratio?: true
  cityDistribution?: true
}

export type EmploymentStatCountAggregateInputType = {
  id?: true
  majorId?: true
  industry?: true
  ratio?: true
  cityDistribution?: true
  _all?: true
}

export type EmploymentStatAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EmploymentStat to aggregate.
   */
  where?: Prisma.EmploymentStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmploymentStats to fetch.
   */
  orderBy?: Prisma.EmploymentStatOrderByWithRelationInput | Prisma.EmploymentStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EmploymentStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmploymentStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmploymentStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned EmploymentStats
  **/
  _count?: true | EmploymentStatCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EmploymentStatAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EmploymentStatSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmploymentStatMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmploymentStatMaxAggregateInputType
}

export type GetEmploymentStatAggregateType<T extends EmploymentStatAggregateArgs> = {
      [P in keyof T & keyof AggregateEmploymentStat]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmploymentStat[P]>
    : Prisma.GetScalarType<T[P], AggregateEmploymentStat[P]>
}




export type EmploymentStatGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmploymentStatWhereInput
  orderBy?: Prisma.EmploymentStatOrderByWithAggregationInput | Prisma.EmploymentStatOrderByWithAggregationInput[]
  by: Prisma.EmploymentStatScalarFieldEnum[] | Prisma.EmploymentStatScalarFieldEnum
  having?: Prisma.EmploymentStatScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmploymentStatCountAggregateInputType | true
  _avg?: EmploymentStatAvgAggregateInputType
  _sum?: EmploymentStatSumAggregateInputType
  _min?: EmploymentStatMinAggregateInputType
  _max?: EmploymentStatMaxAggregateInputType
}

export type EmploymentStatGroupByOutputType = {
  id: string
  majorId: string
  industry: string
  ratio: number
  cityDistribution: string | null
  _count: EmploymentStatCountAggregateOutputType | null
  _avg: EmploymentStatAvgAggregateOutputType | null
  _sum: EmploymentStatSumAggregateOutputType | null
  _min: EmploymentStatMinAggregateOutputType | null
  _max: EmploymentStatMaxAggregateOutputType | null
}

export type GetEmploymentStatGroupByPayload<T extends EmploymentStatGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmploymentStatGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmploymentStatGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmploymentStatGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmploymentStatGroupByOutputType[P]>
      }
    >
  >



export type EmploymentStatWhereInput = {
  AND?: Prisma.EmploymentStatWhereInput | Prisma.EmploymentStatWhereInput[]
  OR?: Prisma.EmploymentStatWhereInput[]
  NOT?: Prisma.EmploymentStatWhereInput | Prisma.EmploymentStatWhereInput[]
  id?: Prisma.StringFilter<"EmploymentStat"> | string
  majorId?: Prisma.StringFilter<"EmploymentStat"> | string
  industry?: Prisma.StringFilter<"EmploymentStat"> | string
  ratio?: Prisma.FloatFilter<"EmploymentStat"> | number
  cityDistribution?: Prisma.StringNullableFilter<"EmploymentStat"> | string | null
  major?: Prisma.XOR<Prisma.MajorScalarRelationFilter, Prisma.MajorWhereInput>
}

export type EmploymentStatOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
  industry?: Prisma.SortOrder
  ratio?: Prisma.SortOrder
  cityDistribution?: Prisma.SortOrderInput | Prisma.SortOrder
  major?: Prisma.MajorOrderByWithRelationInput
}

export type EmploymentStatWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.EmploymentStatWhereInput | Prisma.EmploymentStatWhereInput[]
  OR?: Prisma.EmploymentStatWhereInput[]
  NOT?: Prisma.EmploymentStatWhereInput | Prisma.EmploymentStatWhereInput[]
  majorId?: Prisma.StringFilter<"EmploymentStat"> | string
  industry?: Prisma.StringFilter<"EmploymentStat"> | string
  ratio?: Prisma.FloatFilter<"EmploymentStat"> | number
  cityDistribution?: Prisma.StringNullableFilter<"EmploymentStat"> | string | null
  major?: Prisma.XOR<Prisma.MajorScalarRelationFilter, Prisma.MajorWhereInput>
}, "id">

export type EmploymentStatOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
  industry?: Prisma.SortOrder
  ratio?: Prisma.SortOrder
  cityDistribution?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.EmploymentStatCountOrderByAggregateInput
  _avg?: Prisma.EmploymentStatAvgOrderByAggregateInput
  _max?: Prisma.EmploymentStatMaxOrderByAggregateInput
  _min?: Prisma.EmploymentStatMinOrderByAggregateInput
  _sum?: Prisma.EmploymentStatSumOrderByAggregateInput
}

export type EmploymentStatScalarWhereWithAggregatesInput = {
  AND?: Prisma.EmploymentStatScalarWhereWithAggregatesInput | Prisma.EmploymentStatScalarWhereWithAggregatesInput[]
  OR?: Prisma.EmploymentStatScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EmploymentStatScalarWhereWithAggregatesInput | Prisma.EmploymentStatScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"EmploymentStat"> | string
  majorId?: Prisma.StringWithAggregatesFilter<"EmploymentStat"> | string
  industry?: Prisma.StringWithAggregatesFilter<"EmploymentStat"> | string
  ratio?: Prisma.FloatWithAggregatesFilter<"EmploymentStat"> | number
  cityDistribution?: Prisma.StringNullableWithAggregatesFilter<"EmploymentStat"> | string | null
}

export type EmploymentStatCreateInput = {
  id?: string
  industry: string
  ratio: number
  cityDistribution?: string | null
  major: Prisma.MajorCreateNestedOneWithoutEmploymentStatsInput
}

export type EmploymentStatUncheckedCreateInput = {
  id?: string
  majorId: string
  industry: string
  ratio: number
  cityDistribution?: string | null
}

export type EmploymentStatUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  industry?: Prisma.StringFieldUpdateOperationsInput | string
  ratio?: Prisma.FloatFieldUpdateOperationsInput | number
  cityDistribution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  major?: Prisma.MajorUpdateOneRequiredWithoutEmploymentStatsNestedInput
}

export type EmploymentStatUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  majorId?: Prisma.StringFieldUpdateOperationsInput | string
  industry?: Prisma.StringFieldUpdateOperationsInput | string
  ratio?: Prisma.FloatFieldUpdateOperationsInput | number
  cityDistribution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type EmploymentStatCreateManyInput = {
  id?: string
  majorId: string
  industry: string
  ratio: number
  cityDistribution?: string | null
}

export type EmploymentStatUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  industry?: Prisma.StringFieldUpdateOperationsInput | string
  ratio?: Prisma.FloatFieldUpdateOperationsInput | number
  cityDistribution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type EmploymentStatUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  majorId?: Prisma.StringFieldUpdateOperationsInput | string
  industry?: Prisma.StringFieldUpdateOperationsInput | string
  ratio?: Prisma.FloatFieldUpdateOperationsInput | number
  cityDistribution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type EmploymentStatListRelationFilter = {
  every?: Prisma.EmploymentStatWhereInput
  some?: Prisma.EmploymentStatWhereInput
  none?: Prisma.EmploymentStatWhereInput
}

export type EmploymentStatOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EmploymentStatCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
  industry?: Prisma.SortOrder
  ratio?: Prisma.SortOrder
  cityDistribution?: Prisma.SortOrder
}

export type EmploymentStatAvgOrderByAggregateInput = {
  ratio?: Prisma.SortOrder
}

export type EmploymentStatMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
  industry?: Prisma.SortOrder
  ratio?: Prisma.SortOrder
  cityDistribution?: Prisma.SortOrder
}

export type EmploymentStatMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
  industry?: Prisma.SortOrder
  ratio?: Prisma.SortOrder
  cityDistribution?: Prisma.SortOrder
}

export type EmploymentStatSumOrderByAggregateInput = {
  ratio?: Prisma.SortOrder
}

export type EmploymentStatCreateNestedManyWithoutMajorInput = {
  create?: Prisma.XOR<Prisma.EmploymentStatCreateWithoutMajorInput, Prisma.EmploymentStatUncheckedCreateWithoutMajorInput> | Prisma.EmploymentStatCreateWithoutMajorInput[] | Prisma.EmploymentStatUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.EmploymentStatCreateOrConnectWithoutMajorInput | Prisma.EmploymentStatCreateOrConnectWithoutMajorInput[]
  createMany?: Prisma.EmploymentStatCreateManyMajorInputEnvelope
  connect?: Prisma.EmploymentStatWhereUniqueInput | Prisma.EmploymentStatWhereUniqueInput[]
}

export type EmploymentStatUncheckedCreateNestedManyWithoutMajorInput = {
  create?: Prisma.XOR<Prisma.EmploymentStatCreateWithoutMajorInput, Prisma.EmploymentStatUncheckedCreateWithoutMajorInput> | Prisma.EmploymentStatCreateWithoutMajorInput[] | Prisma.EmploymentStatUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.EmploymentStatCreateOrConnectWithoutMajorInput | Prisma.EmploymentStatCreateOrConnectWithoutMajorInput[]
  createMany?: Prisma.EmploymentStatCreateManyMajorInputEnvelope
  connect?: Prisma.EmploymentStatWhereUniqueInput | Prisma.EmploymentStatWhereUniqueInput[]
}

export type EmploymentStatUpdateManyWithoutMajorNestedInput = {
  create?: Prisma.XOR<Prisma.EmploymentStatCreateWithoutMajorInput, Prisma.EmploymentStatUncheckedCreateWithoutMajorInput> | Prisma.EmploymentStatCreateWithoutMajorInput[] | Prisma.EmploymentStatUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.EmploymentStatCreateOrConnectWithoutMajorInput | Prisma.EmploymentStatCreateOrConnectWithoutMajorInput[]
  upsert?: Prisma.EmploymentStatUpsertWithWhereUniqueWithoutMajorInput | Prisma.EmploymentStatUpsertWithWhereUniqueWithoutMajorInput[]
  createMany?: Prisma.EmploymentStatCreateManyMajorInputEnvelope
  set?: Prisma.EmploymentStatWhereUniqueInput | Prisma.EmploymentStatWhereUniqueInput[]
  disconnect?: Prisma.EmploymentStatWhereUniqueInput | Prisma.EmploymentStatWhereUniqueInput[]
  delete?: Prisma.EmploymentStatWhereUniqueInput | Prisma.EmploymentStatWhereUniqueInput[]
  connect?: Prisma.EmploymentStatWhereUniqueInput | Prisma.EmploymentStatWhereUniqueInput[]
  update?: Prisma.EmploymentStatUpdateWithWhereUniqueWithoutMajorInput | Prisma.EmploymentStatUpdateWithWhereUniqueWithoutMajorInput[]
  updateMany?: Prisma.EmploymentStatUpdateManyWithWhereWithoutMajorInput | Prisma.EmploymentStatUpdateManyWithWhereWithoutMajorInput[]
  deleteMany?: Prisma.EmploymentStatScalarWhereInput | Prisma.EmploymentStatScalarWhereInput[]
}

export type EmploymentStatUncheckedUpdateManyWithoutMajorNestedInput = {
  create?: Prisma.XOR<Prisma.EmploymentStatCreateWithoutMajorInput, Prisma.EmploymentStatUncheckedCreateWithoutMajorInput> | Prisma.EmploymentStatCreateWithoutMajorInput[] | Prisma.EmploymentStatUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.EmploymentStatCreateOrConnectWithoutMajorInput | Prisma.EmploymentStatCreateOrConnectWithoutMajorInput[]
  upsert?: Prisma.EmploymentStatUpsertWithWhereUniqueWithoutMajorInput | Prisma.EmploymentStatUpsertWithWhereUniqueWithoutMajorInput[]
  createMany?: Prisma.EmploymentStatCreateManyMajorInputEnvelope
  set?: Prisma.EmploymentStatWhereUniqueInput | Prisma.EmploymentStatWhereUniqueInput[]
  disconnect?: Prisma.EmploymentStatWhereUniqueInput | Prisma.EmploymentStatWhereUniqueInput[]
  delete?: Prisma.EmploymentStatWhereUniqueInput | Prisma.EmploymentStatWhereUniqueInput[]
  connect?: Prisma.EmploymentStatWhereUniqueInput | Prisma.EmploymentStatWhereUniqueInput[]
  update?: Prisma.EmploymentStatUpdateWithWhereUniqueWithoutMajorInput | Prisma.EmploymentStatUpdateWithWhereUniqueWithoutMajorInput[]
  updateMany?: Prisma.EmploymentStatUpdateManyWithWhereWithoutMajorInput | Prisma.EmploymentStatUpdateManyWithWhereWithoutMajorInput[]
  deleteMany?: Prisma.EmploymentStatScalarWhereInput | Prisma.EmploymentStatScalarWhereInput[]
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type EmploymentStatCreateWithoutMajorInput = {
  id?: string
  industry: string
  ratio: number
  cityDistribution?: string | null
}

export type EmploymentStatUncheckedCreateWithoutMajorInput = {
  id?: string
  industry: string
  ratio: number
  cityDistribution?: string | null
}

export type EmploymentStatCreateOrConnectWithoutMajorInput = {
  where: Prisma.EmploymentStatWhereUniqueInput
  create: Prisma.XOR<Prisma.EmploymentStatCreateWithoutMajorInput, Prisma.EmploymentStatUncheckedCreateWithoutMajorInput>
}

export type EmploymentStatCreateManyMajorInputEnvelope = {
  data: Prisma.EmploymentStatCreateManyMajorInput | Prisma.EmploymentStatCreateManyMajorInput[]
}

export type EmploymentStatUpsertWithWhereUniqueWithoutMajorInput = {
  where: Prisma.EmploymentStatWhereUniqueInput
  update: Prisma.XOR<Prisma.EmploymentStatUpdateWithoutMajorInput, Prisma.EmploymentStatUncheckedUpdateWithoutMajorInput>
  create: Prisma.XOR<Prisma.EmploymentStatCreateWithoutMajorInput, Prisma.EmploymentStatUncheckedCreateWithoutMajorInput>
}

export type EmploymentStatUpdateWithWhereUniqueWithoutMajorInput = {
  where: Prisma.EmploymentStatWhereUniqueInput
  data: Prisma.XOR<Prisma.EmploymentStatUpdateWithoutMajorInput, Prisma.EmploymentStatUncheckedUpdateWithoutMajorInput>
}

export type EmploymentStatUpdateManyWithWhereWithoutMajorInput = {
  where: Prisma.EmploymentStatScalarWhereInput
  data: Prisma.XOR<Prisma.EmploymentStatUpdateManyMutationInput, Prisma.EmploymentStatUncheckedUpdateManyWithoutMajorInput>
}

export type EmploymentStatScalarWhereInput = {
  AND?: Prisma.EmploymentStatScalarWhereInput | Prisma.EmploymentStatScalarWhereInput[]
  OR?: Prisma.EmploymentStatScalarWhereInput[]
  NOT?: Prisma.EmploymentStatScalarWhereInput | Prisma.EmploymentStatScalarWhereInput[]
  id?: Prisma.StringFilter<"EmploymentStat"> | string
  majorId?: Prisma.StringFilter<"EmploymentStat"> | string
  industry?: Prisma.StringFilter<"EmploymentStat"> | string
  ratio?: Prisma.FloatFilter<"EmploymentStat"> | number
  cityDistribution?: Prisma.StringNullableFilter<"EmploymentStat"> | string | null
}

export type EmploymentStatCreateManyMajorInput = {
  id?: string
  industry: string
  ratio: number
  cityDistribution?: string | null
}

export type EmploymentStatUpdateWithoutMajorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  industry?: Prisma.StringFieldUpdateOperationsInput | string
  ratio?: Prisma.FloatFieldUpdateOperationsInput | number
  cityDistribution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type EmploymentStatUncheckedUpdateWithoutMajorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  industry?: Prisma.StringFieldUpdateOperationsInput | string
  ratio?: Prisma.FloatFieldUpdateOperationsInput | number
  cityDistribution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type EmploymentStatUncheckedUpdateManyWithoutMajorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  industry?: Prisma.StringFieldUpdateOperationsInput | string
  ratio?: Prisma.FloatFieldUpdateOperationsInput | number
  cityDistribution?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type EmploymentStatSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  majorId?: boolean
  industry?: boolean
  ratio?: boolean
  cityDistribution?: boolean
  major?: boolean | Prisma.MajorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["employmentStat"]>

export type EmploymentStatSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  majorId?: boolean
  industry?: boolean
  ratio?: boolean
  cityDistribution?: boolean
  major?: boolean | Prisma.MajorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["employmentStat"]>

export type EmploymentStatSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  majorId?: boolean
  industry?: boolean
  ratio?: boolean
  cityDistribution?: boolean
  major?: boolean | Prisma.MajorDefaultArgs<ExtArgs>
}, ExtArgs["result"]["employmentStat"]>

export type EmploymentStatSelectScalar = {
  id?: boolean
  majorId?: boolean
  industry?: boolean
  ratio?: boolean
  cityDistribution?: boolean
}

export type EmploymentStatOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "majorId" | "industry" | "ratio" | "cityDistribution", ExtArgs["result"]["employmentStat"]>
export type EmploymentStatInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  major?: boolean | Prisma.MajorDefaultArgs<ExtArgs>
}
export type EmploymentStatIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  major?: boolean | Prisma.MajorDefaultArgs<ExtArgs>
}
export type EmploymentStatIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  major?: boolean | Prisma.MajorDefaultArgs<ExtArgs>
}

export type $EmploymentStatPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "EmploymentStat"
  objects: {
    major: Prisma.$MajorPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    majorId: string
    industry: string
    ratio: number
    cityDistribution: string | null
  }, ExtArgs["result"]["employmentStat"]>
  composites: {}
}

export type EmploymentStatGetPayload<S extends boolean | null | undefined | EmploymentStatDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EmploymentStatPayload, S>

export type EmploymentStatCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EmploymentStatFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmploymentStatCountAggregateInputType | true
  }

export interface EmploymentStatDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['EmploymentStat'], meta: { name: 'EmploymentStat' } }
  /**
   * Find zero or one EmploymentStat that matches the filter.
   * @param {EmploymentStatFindUniqueArgs} args - Arguments to find a EmploymentStat
   * @example
   * // Get one EmploymentStat
   * const employmentStat = await prisma.employmentStat.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EmploymentStatFindUniqueArgs>(args: Prisma.SelectSubset<T, EmploymentStatFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EmploymentStatClient<runtime.Types.Result.GetResult<Prisma.$EmploymentStatPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one EmploymentStat that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EmploymentStatFindUniqueOrThrowArgs} args - Arguments to find a EmploymentStat
   * @example
   * // Get one EmploymentStat
   * const employmentStat = await prisma.employmentStat.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EmploymentStatFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EmploymentStatFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmploymentStatClient<runtime.Types.Result.GetResult<Prisma.$EmploymentStatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EmploymentStat that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmploymentStatFindFirstArgs} args - Arguments to find a EmploymentStat
   * @example
   * // Get one EmploymentStat
   * const employmentStat = await prisma.employmentStat.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EmploymentStatFindFirstArgs>(args?: Prisma.SelectSubset<T, EmploymentStatFindFirstArgs<ExtArgs>>): Prisma.Prisma__EmploymentStatClient<runtime.Types.Result.GetResult<Prisma.$EmploymentStatPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first EmploymentStat that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmploymentStatFindFirstOrThrowArgs} args - Arguments to find a EmploymentStat
   * @example
   * // Get one EmploymentStat
   * const employmentStat = await prisma.employmentStat.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EmploymentStatFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EmploymentStatFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmploymentStatClient<runtime.Types.Result.GetResult<Prisma.$EmploymentStatPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more EmploymentStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmploymentStatFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all EmploymentStats
   * const employmentStats = await prisma.employmentStat.findMany()
   * 
   * // Get first 10 EmploymentStats
   * const employmentStats = await prisma.employmentStat.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const employmentStatWithIdOnly = await prisma.employmentStat.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EmploymentStatFindManyArgs>(args?: Prisma.SelectSubset<T, EmploymentStatFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmploymentStatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a EmploymentStat.
   * @param {EmploymentStatCreateArgs} args - Arguments to create a EmploymentStat.
   * @example
   * // Create one EmploymentStat
   * const EmploymentStat = await prisma.employmentStat.create({
   *   data: {
   *     // ... data to create a EmploymentStat
   *   }
   * })
   * 
   */
  create<T extends EmploymentStatCreateArgs>(args: Prisma.SelectSubset<T, EmploymentStatCreateArgs<ExtArgs>>): Prisma.Prisma__EmploymentStatClient<runtime.Types.Result.GetResult<Prisma.$EmploymentStatPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many EmploymentStats.
   * @param {EmploymentStatCreateManyArgs} args - Arguments to create many EmploymentStats.
   * @example
   * // Create many EmploymentStats
   * const employmentStat = await prisma.employmentStat.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EmploymentStatCreateManyArgs>(args?: Prisma.SelectSubset<T, EmploymentStatCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many EmploymentStats and returns the data saved in the database.
   * @param {EmploymentStatCreateManyAndReturnArgs} args - Arguments to create many EmploymentStats.
   * @example
   * // Create many EmploymentStats
   * const employmentStat = await prisma.employmentStat.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many EmploymentStats and only return the `id`
   * const employmentStatWithIdOnly = await prisma.employmentStat.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EmploymentStatCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EmploymentStatCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmploymentStatPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a EmploymentStat.
   * @param {EmploymentStatDeleteArgs} args - Arguments to delete one EmploymentStat.
   * @example
   * // Delete one EmploymentStat
   * const EmploymentStat = await prisma.employmentStat.delete({
   *   where: {
   *     // ... filter to delete one EmploymentStat
   *   }
   * })
   * 
   */
  delete<T extends EmploymentStatDeleteArgs>(args: Prisma.SelectSubset<T, EmploymentStatDeleteArgs<ExtArgs>>): Prisma.Prisma__EmploymentStatClient<runtime.Types.Result.GetResult<Prisma.$EmploymentStatPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one EmploymentStat.
   * @param {EmploymentStatUpdateArgs} args - Arguments to update one EmploymentStat.
   * @example
   * // Update one EmploymentStat
   * const employmentStat = await prisma.employmentStat.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EmploymentStatUpdateArgs>(args: Prisma.SelectSubset<T, EmploymentStatUpdateArgs<ExtArgs>>): Prisma.Prisma__EmploymentStatClient<runtime.Types.Result.GetResult<Prisma.$EmploymentStatPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more EmploymentStats.
   * @param {EmploymentStatDeleteManyArgs} args - Arguments to filter EmploymentStats to delete.
   * @example
   * // Delete a few EmploymentStats
   * const { count } = await prisma.employmentStat.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EmploymentStatDeleteManyArgs>(args?: Prisma.SelectSubset<T, EmploymentStatDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EmploymentStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmploymentStatUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many EmploymentStats
   * const employmentStat = await prisma.employmentStat.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EmploymentStatUpdateManyArgs>(args: Prisma.SelectSubset<T, EmploymentStatUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more EmploymentStats and returns the data updated in the database.
   * @param {EmploymentStatUpdateManyAndReturnArgs} args - Arguments to update many EmploymentStats.
   * @example
   * // Update many EmploymentStats
   * const employmentStat = await prisma.employmentStat.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more EmploymentStats and only return the `id`
   * const employmentStatWithIdOnly = await prisma.employmentStat.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EmploymentStatUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EmploymentStatUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmploymentStatPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one EmploymentStat.
   * @param {EmploymentStatUpsertArgs} args - Arguments to update or create a EmploymentStat.
   * @example
   * // Update or create a EmploymentStat
   * const employmentStat = await prisma.employmentStat.upsert({
   *   create: {
   *     // ... data to create a EmploymentStat
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the EmploymentStat we want to update
   *   }
   * })
   */
  upsert<T extends EmploymentStatUpsertArgs>(args: Prisma.SelectSubset<T, EmploymentStatUpsertArgs<ExtArgs>>): Prisma.Prisma__EmploymentStatClient<runtime.Types.Result.GetResult<Prisma.$EmploymentStatPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of EmploymentStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmploymentStatCountArgs} args - Arguments to filter EmploymentStats to count.
   * @example
   * // Count the number of EmploymentStats
   * const count = await prisma.employmentStat.count({
   *   where: {
   *     // ... the filter for the EmploymentStats we want to count
   *   }
   * })
  **/
  count<T extends EmploymentStatCountArgs>(
    args?: Prisma.Subset<T, EmploymentStatCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmploymentStatCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a EmploymentStat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmploymentStatAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmploymentStatAggregateArgs>(args: Prisma.Subset<T, EmploymentStatAggregateArgs>): Prisma.PrismaPromise<GetEmploymentStatAggregateType<T>>

  /**
   * Group by EmploymentStat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmploymentStatGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EmploymentStatGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EmploymentStatGroupByArgs['orderBy'] }
      : { orderBy?: EmploymentStatGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EmploymentStatGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmploymentStatGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the EmploymentStat model
 */
readonly fields: EmploymentStatFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for EmploymentStat.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EmploymentStatClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  major<T extends Prisma.MajorDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MajorDefaultArgs<ExtArgs>>): Prisma.Prisma__MajorClient<runtime.Types.Result.GetResult<Prisma.$MajorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the EmploymentStat model
 */
export interface EmploymentStatFieldRefs {
  readonly id: Prisma.FieldRef<"EmploymentStat", 'String'>
  readonly majorId: Prisma.FieldRef<"EmploymentStat", 'String'>
  readonly industry: Prisma.FieldRef<"EmploymentStat", 'String'>
  readonly ratio: Prisma.FieldRef<"EmploymentStat", 'Float'>
  readonly cityDistribution: Prisma.FieldRef<"EmploymentStat", 'String'>
}
    

// Custom InputTypes
/**
 * EmploymentStat findUnique
 */
export type EmploymentStatFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmploymentStat
   */
  select?: Prisma.EmploymentStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmploymentStat
   */
  omit?: Prisma.EmploymentStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmploymentStatInclude<ExtArgs> | null
  /**
   * Filter, which EmploymentStat to fetch.
   */
  where: Prisma.EmploymentStatWhereUniqueInput
}

/**
 * EmploymentStat findUniqueOrThrow
 */
export type EmploymentStatFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmploymentStat
   */
  select?: Prisma.EmploymentStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmploymentStat
   */
  omit?: Prisma.EmploymentStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmploymentStatInclude<ExtArgs> | null
  /**
   * Filter, which EmploymentStat to fetch.
   */
  where: Prisma.EmploymentStatWhereUniqueInput
}

/**
 * EmploymentStat findFirst
 */
export type EmploymentStatFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmploymentStat
   */
  select?: Prisma.EmploymentStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmploymentStat
   */
  omit?: Prisma.EmploymentStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmploymentStatInclude<ExtArgs> | null
  /**
   * Filter, which EmploymentStat to fetch.
   */
  where?: Prisma.EmploymentStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmploymentStats to fetch.
   */
  orderBy?: Prisma.EmploymentStatOrderByWithRelationInput | Prisma.EmploymentStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EmploymentStats.
   */
  cursor?: Prisma.EmploymentStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmploymentStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmploymentStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmploymentStats.
   */
  distinct?: Prisma.EmploymentStatScalarFieldEnum | Prisma.EmploymentStatScalarFieldEnum[]
}

/**
 * EmploymentStat findFirstOrThrow
 */
export type EmploymentStatFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmploymentStat
   */
  select?: Prisma.EmploymentStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmploymentStat
   */
  omit?: Prisma.EmploymentStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmploymentStatInclude<ExtArgs> | null
  /**
   * Filter, which EmploymentStat to fetch.
   */
  where?: Prisma.EmploymentStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmploymentStats to fetch.
   */
  orderBy?: Prisma.EmploymentStatOrderByWithRelationInput | Prisma.EmploymentStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for EmploymentStats.
   */
  cursor?: Prisma.EmploymentStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmploymentStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmploymentStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmploymentStats.
   */
  distinct?: Prisma.EmploymentStatScalarFieldEnum | Prisma.EmploymentStatScalarFieldEnum[]
}

/**
 * EmploymentStat findMany
 */
export type EmploymentStatFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmploymentStat
   */
  select?: Prisma.EmploymentStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmploymentStat
   */
  omit?: Prisma.EmploymentStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmploymentStatInclude<ExtArgs> | null
  /**
   * Filter, which EmploymentStats to fetch.
   */
  where?: Prisma.EmploymentStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of EmploymentStats to fetch.
   */
  orderBy?: Prisma.EmploymentStatOrderByWithRelationInput | Prisma.EmploymentStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing EmploymentStats.
   */
  cursor?: Prisma.EmploymentStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` EmploymentStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` EmploymentStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of EmploymentStats.
   */
  distinct?: Prisma.EmploymentStatScalarFieldEnum | Prisma.EmploymentStatScalarFieldEnum[]
}

/**
 * EmploymentStat create
 */
export type EmploymentStatCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmploymentStat
   */
  select?: Prisma.EmploymentStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmploymentStat
   */
  omit?: Prisma.EmploymentStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmploymentStatInclude<ExtArgs> | null
  /**
   * The data needed to create a EmploymentStat.
   */
  data: Prisma.XOR<Prisma.EmploymentStatCreateInput, Prisma.EmploymentStatUncheckedCreateInput>
}

/**
 * EmploymentStat createMany
 */
export type EmploymentStatCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many EmploymentStats.
   */
  data: Prisma.EmploymentStatCreateManyInput | Prisma.EmploymentStatCreateManyInput[]
}

/**
 * EmploymentStat createManyAndReturn
 */
export type EmploymentStatCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmploymentStat
   */
  select?: Prisma.EmploymentStatSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EmploymentStat
   */
  omit?: Prisma.EmploymentStatOmit<ExtArgs> | null
  /**
   * The data used to create many EmploymentStats.
   */
  data: Prisma.EmploymentStatCreateManyInput | Prisma.EmploymentStatCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmploymentStatIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * EmploymentStat update
 */
export type EmploymentStatUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmploymentStat
   */
  select?: Prisma.EmploymentStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmploymentStat
   */
  omit?: Prisma.EmploymentStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmploymentStatInclude<ExtArgs> | null
  /**
   * The data needed to update a EmploymentStat.
   */
  data: Prisma.XOR<Prisma.EmploymentStatUpdateInput, Prisma.EmploymentStatUncheckedUpdateInput>
  /**
   * Choose, which EmploymentStat to update.
   */
  where: Prisma.EmploymentStatWhereUniqueInput
}

/**
 * EmploymentStat updateMany
 */
export type EmploymentStatUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update EmploymentStats.
   */
  data: Prisma.XOR<Prisma.EmploymentStatUpdateManyMutationInput, Prisma.EmploymentStatUncheckedUpdateManyInput>
  /**
   * Filter which EmploymentStats to update
   */
  where?: Prisma.EmploymentStatWhereInput
  /**
   * Limit how many EmploymentStats to update.
   */
  limit?: number
}

/**
 * EmploymentStat updateManyAndReturn
 */
export type EmploymentStatUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmploymentStat
   */
  select?: Prisma.EmploymentStatSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the EmploymentStat
   */
  omit?: Prisma.EmploymentStatOmit<ExtArgs> | null
  /**
   * The data used to update EmploymentStats.
   */
  data: Prisma.XOR<Prisma.EmploymentStatUpdateManyMutationInput, Prisma.EmploymentStatUncheckedUpdateManyInput>
  /**
   * Filter which EmploymentStats to update
   */
  where?: Prisma.EmploymentStatWhereInput
  /**
   * Limit how many EmploymentStats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmploymentStatIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * EmploymentStat upsert
 */
export type EmploymentStatUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmploymentStat
   */
  select?: Prisma.EmploymentStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmploymentStat
   */
  omit?: Prisma.EmploymentStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmploymentStatInclude<ExtArgs> | null
  /**
   * The filter to search for the EmploymentStat to update in case it exists.
   */
  where: Prisma.EmploymentStatWhereUniqueInput
  /**
   * In case the EmploymentStat found by the `where` argument doesn't exist, create a new EmploymentStat with this data.
   */
  create: Prisma.XOR<Prisma.EmploymentStatCreateInput, Prisma.EmploymentStatUncheckedCreateInput>
  /**
   * In case the EmploymentStat was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EmploymentStatUpdateInput, Prisma.EmploymentStatUncheckedUpdateInput>
}

/**
 * EmploymentStat delete
 */
export type EmploymentStatDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmploymentStat
   */
  select?: Prisma.EmploymentStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmploymentStat
   */
  omit?: Prisma.EmploymentStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmploymentStatInclude<ExtArgs> | null
  /**
   * Filter which EmploymentStat to delete.
   */
  where: Prisma.EmploymentStatWhereUniqueInput
}

/**
 * EmploymentStat deleteMany
 */
export type EmploymentStatDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which EmploymentStats to delete
   */
  where?: Prisma.EmploymentStatWhereInput
  /**
   * Limit how many EmploymentStats to delete.
   */
  limit?: number
}

/**
 * EmploymentStat without action
 */
export type EmploymentStatDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmploymentStat
   */
  select?: Prisma.EmploymentStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmploymentStat
   */
  omit?: Prisma.EmploymentStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmploymentStatInclude<ExtArgs> | null
}
