
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GuideProgress` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model GuideProgress
 * 
 */
export type GuideProgressModel = runtime.Types.Result.DefaultSelection<Prisma.$GuideProgressPayload>

export type AggregateGuideProgress = {
  _count: GuideProgressCountAggregateOutputType | null
  _min: GuideProgressMinAggregateOutputType | null
  _max: GuideProgressMaxAggregateOutputType | null
}

export type GuideProgressMinAggregateOutputType = {
  id: string | null
  userId: string | null
  phase: string | null
  taskId: string | null
  completed: boolean | null
  completedAt: Date | null
}

export type GuideProgressMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  phase: string | null
  taskId: string | null
  completed: boolean | null
  completedAt: Date | null
}

export type GuideProgressCountAggregateOutputType = {
  id: number
  userId: number
  phase: number
  taskId: number
  completed: number
  completedAt: number
  _all: number
}


export type GuideProgressMinAggregateInputType = {
  id?: true
  userId?: true
  phase?: true
  taskId?: true
  completed?: true
  completedAt?: true
}

export type GuideProgressMaxAggregateInputType = {
  id?: true
  userId?: true
  phase?: true
  taskId?: true
  completed?: true
  completedAt?: true
}

export type GuideProgressCountAggregateInputType = {
  id?: true
  userId?: true
  phase?: true
  taskId?: true
  completed?: true
  completedAt?: true
  _all?: true
}

export type GuideProgressAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GuideProgress to aggregate.
   */
  where?: Prisma.GuideProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuideProgresses to fetch.
   */
  orderBy?: Prisma.GuideProgressOrderByWithRelationInput | Prisma.GuideProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GuideProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuideProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuideProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GuideProgresses
  **/
  _count?: true | GuideProgressCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GuideProgressMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GuideProgressMaxAggregateInputType
}

export type GetGuideProgressAggregateType<T extends GuideProgressAggregateArgs> = {
      [P in keyof T & keyof AggregateGuideProgress]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGuideProgress[P]>
    : Prisma.GetScalarType<T[P], AggregateGuideProgress[P]>
}




export type GuideProgressGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GuideProgressWhereInput
  orderBy?: Prisma.GuideProgressOrderByWithAggregationInput | Prisma.GuideProgressOrderByWithAggregationInput[]
  by: Prisma.GuideProgressScalarFieldEnum[] | Prisma.GuideProgressScalarFieldEnum
  having?: Prisma.GuideProgressScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GuideProgressCountAggregateInputType | true
  _min?: GuideProgressMinAggregateInputType
  _max?: GuideProgressMaxAggregateInputType
}

export type GuideProgressGroupByOutputType = {
  id: string
  userId: string
  phase: string
  taskId: string
  completed: boolean
  completedAt: Date | null
  _count: GuideProgressCountAggregateOutputType | null
  _min: GuideProgressMinAggregateOutputType | null
  _max: GuideProgressMaxAggregateOutputType | null
}

export type GetGuideProgressGroupByPayload<T extends GuideProgressGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GuideProgressGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GuideProgressGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GuideProgressGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GuideProgressGroupByOutputType[P]>
      }
    >
  >



export type GuideProgressWhereInput = {
  AND?: Prisma.GuideProgressWhereInput | Prisma.GuideProgressWhereInput[]
  OR?: Prisma.GuideProgressWhereInput[]
  NOT?: Prisma.GuideProgressWhereInput | Prisma.GuideProgressWhereInput[]
  id?: Prisma.StringFilter<"GuideProgress"> | string
  userId?: Prisma.StringFilter<"GuideProgress"> | string
  phase?: Prisma.StringFilter<"GuideProgress"> | string
  taskId?: Prisma.StringFilter<"GuideProgress"> | string
  completed?: Prisma.BoolFilter<"GuideProgress"> | boolean
  completedAt?: Prisma.DateTimeNullableFilter<"GuideProgress"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type GuideProgressOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  phase?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  completed?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type GuideProgressWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.GuideProgressWhereInput | Prisma.GuideProgressWhereInput[]
  OR?: Prisma.GuideProgressWhereInput[]
  NOT?: Prisma.GuideProgressWhereInput | Prisma.GuideProgressWhereInput[]
  userId?: Prisma.StringFilter<"GuideProgress"> | string
  phase?: Prisma.StringFilter<"GuideProgress"> | string
  taskId?: Prisma.StringFilter<"GuideProgress"> | string
  completed?: Prisma.BoolFilter<"GuideProgress"> | boolean
  completedAt?: Prisma.DateTimeNullableFilter<"GuideProgress"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type GuideProgressOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  phase?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  completed?: Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.GuideProgressCountOrderByAggregateInput
  _max?: Prisma.GuideProgressMaxOrderByAggregateInput
  _min?: Prisma.GuideProgressMinOrderByAggregateInput
}

export type GuideProgressScalarWhereWithAggregatesInput = {
  AND?: Prisma.GuideProgressScalarWhereWithAggregatesInput | Prisma.GuideProgressScalarWhereWithAggregatesInput[]
  OR?: Prisma.GuideProgressScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GuideProgressScalarWhereWithAggregatesInput | Prisma.GuideProgressScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GuideProgress"> | string
  userId?: Prisma.StringWithAggregatesFilter<"GuideProgress"> | string
  phase?: Prisma.StringWithAggregatesFilter<"GuideProgress"> | string
  taskId?: Prisma.StringWithAggregatesFilter<"GuideProgress"> | string
  completed?: Prisma.BoolWithAggregatesFilter<"GuideProgress"> | boolean
  completedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"GuideProgress"> | Date | string | null
}

export type GuideProgressCreateInput = {
  id?: string
  phase: string
  taskId: string
  completed?: boolean
  completedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutGuideProgressInput
}

export type GuideProgressUncheckedCreateInput = {
  id?: string
  userId: string
  phase: string
  taskId: string
  completed?: boolean
  completedAt?: Date | string | null
}

export type GuideProgressUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  phase?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutGuideProgressNestedInput
}

export type GuideProgressUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  phase?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GuideProgressCreateManyInput = {
  id?: string
  userId: string
  phase: string
  taskId: string
  completed?: boolean
  completedAt?: Date | string | null
}

export type GuideProgressUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  phase?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GuideProgressUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  phase?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GuideProgressListRelationFilter = {
  every?: Prisma.GuideProgressWhereInput
  some?: Prisma.GuideProgressWhereInput
  none?: Prisma.GuideProgressWhereInput
}

export type GuideProgressOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type GuideProgressCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  phase?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  completed?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type GuideProgressMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  phase?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  completed?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type GuideProgressMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  phase?: Prisma.SortOrder
  taskId?: Prisma.SortOrder
  completed?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
}

export type GuideProgressCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.GuideProgressCreateWithoutUserInput, Prisma.GuideProgressUncheckedCreateWithoutUserInput> | Prisma.GuideProgressCreateWithoutUserInput[] | Prisma.GuideProgressUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GuideProgressCreateOrConnectWithoutUserInput | Prisma.GuideProgressCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.GuideProgressCreateManyUserInputEnvelope
  connect?: Prisma.GuideProgressWhereUniqueInput | Prisma.GuideProgressWhereUniqueInput[]
}

export type GuideProgressUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.GuideProgressCreateWithoutUserInput, Prisma.GuideProgressUncheckedCreateWithoutUserInput> | Prisma.GuideProgressCreateWithoutUserInput[] | Prisma.GuideProgressUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GuideProgressCreateOrConnectWithoutUserInput | Prisma.GuideProgressCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.GuideProgressCreateManyUserInputEnvelope
  connect?: Prisma.GuideProgressWhereUniqueInput | Prisma.GuideProgressWhereUniqueInput[]
}

export type GuideProgressUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.GuideProgressCreateWithoutUserInput, Prisma.GuideProgressUncheckedCreateWithoutUserInput> | Prisma.GuideProgressCreateWithoutUserInput[] | Prisma.GuideProgressUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GuideProgressCreateOrConnectWithoutUserInput | Prisma.GuideProgressCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.GuideProgressUpsertWithWhereUniqueWithoutUserInput | Prisma.GuideProgressUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.GuideProgressCreateManyUserInputEnvelope
  set?: Prisma.GuideProgressWhereUniqueInput | Prisma.GuideProgressWhereUniqueInput[]
  disconnect?: Prisma.GuideProgressWhereUniqueInput | Prisma.GuideProgressWhereUniqueInput[]
  delete?: Prisma.GuideProgressWhereUniqueInput | Prisma.GuideProgressWhereUniqueInput[]
  connect?: Prisma.GuideProgressWhereUniqueInput | Prisma.GuideProgressWhereUniqueInput[]
  update?: Prisma.GuideProgressUpdateWithWhereUniqueWithoutUserInput | Prisma.GuideProgressUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.GuideProgressUpdateManyWithWhereWithoutUserInput | Prisma.GuideProgressUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.GuideProgressScalarWhereInput | Prisma.GuideProgressScalarWhereInput[]
}

export type GuideProgressUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.GuideProgressCreateWithoutUserInput, Prisma.GuideProgressUncheckedCreateWithoutUserInput> | Prisma.GuideProgressCreateWithoutUserInput[] | Prisma.GuideProgressUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GuideProgressCreateOrConnectWithoutUserInput | Prisma.GuideProgressCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.GuideProgressUpsertWithWhereUniqueWithoutUserInput | Prisma.GuideProgressUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.GuideProgressCreateManyUserInputEnvelope
  set?: Prisma.GuideProgressWhereUniqueInput | Prisma.GuideProgressWhereUniqueInput[]
  disconnect?: Prisma.GuideProgressWhereUniqueInput | Prisma.GuideProgressWhereUniqueInput[]
  delete?: Prisma.GuideProgressWhereUniqueInput | Prisma.GuideProgressWhereUniqueInput[]
  connect?: Prisma.GuideProgressWhereUniqueInput | Prisma.GuideProgressWhereUniqueInput[]
  update?: Prisma.GuideProgressUpdateWithWhereUniqueWithoutUserInput | Prisma.GuideProgressUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.GuideProgressUpdateManyWithWhereWithoutUserInput | Prisma.GuideProgressUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.GuideProgressScalarWhereInput | Prisma.GuideProgressScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type GuideProgressCreateWithoutUserInput = {
  id?: string
  phase: string
  taskId: string
  completed?: boolean
  completedAt?: Date | string | null
}

export type GuideProgressUncheckedCreateWithoutUserInput = {
  id?: string
  phase: string
  taskId: string
  completed?: boolean
  completedAt?: Date | string | null
}

export type GuideProgressCreateOrConnectWithoutUserInput = {
  where: Prisma.GuideProgressWhereUniqueInput
  create: Prisma.XOR<Prisma.GuideProgressCreateWithoutUserInput, Prisma.GuideProgressUncheckedCreateWithoutUserInput>
}

export type GuideProgressCreateManyUserInputEnvelope = {
  data: Prisma.GuideProgressCreateManyUserInput | Prisma.GuideProgressCreateManyUserInput[]
}

export type GuideProgressUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.GuideProgressWhereUniqueInput
  update: Prisma.XOR<Prisma.GuideProgressUpdateWithoutUserInput, Prisma.GuideProgressUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.GuideProgressCreateWithoutUserInput, Prisma.GuideProgressUncheckedCreateWithoutUserInput>
}

export type GuideProgressUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.GuideProgressWhereUniqueInput
  data: Prisma.XOR<Prisma.GuideProgressUpdateWithoutUserInput, Prisma.GuideProgressUncheckedUpdateWithoutUserInput>
}

export type GuideProgressUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.GuideProgressScalarWhereInput
  data: Prisma.XOR<Prisma.GuideProgressUpdateManyMutationInput, Prisma.GuideProgressUncheckedUpdateManyWithoutUserInput>
}

export type GuideProgressScalarWhereInput = {
  AND?: Prisma.GuideProgressScalarWhereInput | Prisma.GuideProgressScalarWhereInput[]
  OR?: Prisma.GuideProgressScalarWhereInput[]
  NOT?: Prisma.GuideProgressScalarWhereInput | Prisma.GuideProgressScalarWhereInput[]
  id?: Prisma.StringFilter<"GuideProgress"> | string
  userId?: Prisma.StringFilter<"GuideProgress"> | string
  phase?: Prisma.StringFilter<"GuideProgress"> | string
  taskId?: Prisma.StringFilter<"GuideProgress"> | string
  completed?: Prisma.BoolFilter<"GuideProgress"> | boolean
  completedAt?: Prisma.DateTimeNullableFilter<"GuideProgress"> | Date | string | null
}

export type GuideProgressCreateManyUserInput = {
  id?: string
  phase: string
  taskId: string
  completed?: boolean
  completedAt?: Date | string | null
}

export type GuideProgressUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  phase?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GuideProgressUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  phase?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GuideProgressUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  phase?: Prisma.StringFieldUpdateOperationsInput | string
  taskId?: Prisma.StringFieldUpdateOperationsInput | string
  completed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type GuideProgressSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  phase?: boolean
  taskId?: boolean
  completed?: boolean
  completedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guideProgress"]>

export type GuideProgressSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  phase?: boolean
  taskId?: boolean
  completed?: boolean
  completedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guideProgress"]>

export type GuideProgressSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  phase?: boolean
  taskId?: boolean
  completed?: boolean
  completedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["guideProgress"]>

export type GuideProgressSelectScalar = {
  id?: boolean
  userId?: boolean
  phase?: boolean
  taskId?: boolean
  completed?: boolean
  completedAt?: boolean
}

export type GuideProgressOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "phase" | "taskId" | "completed" | "completedAt", ExtArgs["result"]["guideProgress"]>
export type GuideProgressInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type GuideProgressIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type GuideProgressIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $GuideProgressPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GuideProgress"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    phase: string
    taskId: string
    completed: boolean
    completedAt: Date | null
  }, ExtArgs["result"]["guideProgress"]>
  composites: {}
}

export type GuideProgressGetPayload<S extends boolean | null | undefined | GuideProgressDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GuideProgressPayload, S>

export type GuideProgressCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GuideProgressFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GuideProgressCountAggregateInputType | true
  }

export interface GuideProgressDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GuideProgress'], meta: { name: 'GuideProgress' } }
  /**
   * Find zero or one GuideProgress that matches the filter.
   * @param {GuideProgressFindUniqueArgs} args - Arguments to find a GuideProgress
   * @example
   * // Get one GuideProgress
   * const guideProgress = await prisma.guideProgress.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GuideProgressFindUniqueArgs>(args: Prisma.SelectSubset<T, GuideProgressFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GuideProgressClient<runtime.Types.Result.GetResult<Prisma.$GuideProgressPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GuideProgress that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GuideProgressFindUniqueOrThrowArgs} args - Arguments to find a GuideProgress
   * @example
   * // Get one GuideProgress
   * const guideProgress = await prisma.guideProgress.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GuideProgressFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GuideProgressFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GuideProgressClient<runtime.Types.Result.GetResult<Prisma.$GuideProgressPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GuideProgress that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuideProgressFindFirstArgs} args - Arguments to find a GuideProgress
   * @example
   * // Get one GuideProgress
   * const guideProgress = await prisma.guideProgress.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GuideProgressFindFirstArgs>(args?: Prisma.SelectSubset<T, GuideProgressFindFirstArgs<ExtArgs>>): Prisma.Prisma__GuideProgressClient<runtime.Types.Result.GetResult<Prisma.$GuideProgressPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GuideProgress that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuideProgressFindFirstOrThrowArgs} args - Arguments to find a GuideProgress
   * @example
   * // Get one GuideProgress
   * const guideProgress = await prisma.guideProgress.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GuideProgressFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GuideProgressFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GuideProgressClient<runtime.Types.Result.GetResult<Prisma.$GuideProgressPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GuideProgresses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuideProgressFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GuideProgresses
   * const guideProgresses = await prisma.guideProgress.findMany()
   * 
   * // Get first 10 GuideProgresses
   * const guideProgresses = await prisma.guideProgress.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const guideProgressWithIdOnly = await prisma.guideProgress.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GuideProgressFindManyArgs>(args?: Prisma.SelectSubset<T, GuideProgressFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuideProgressPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GuideProgress.
   * @param {GuideProgressCreateArgs} args - Arguments to create a GuideProgress.
   * @example
   * // Create one GuideProgress
   * const GuideProgress = await prisma.guideProgress.create({
   *   data: {
   *     // ... data to create a GuideProgress
   *   }
   * })
   * 
   */
  create<T extends GuideProgressCreateArgs>(args: Prisma.SelectSubset<T, GuideProgressCreateArgs<ExtArgs>>): Prisma.Prisma__GuideProgressClient<runtime.Types.Result.GetResult<Prisma.$GuideProgressPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GuideProgresses.
   * @param {GuideProgressCreateManyArgs} args - Arguments to create many GuideProgresses.
   * @example
   * // Create many GuideProgresses
   * const guideProgress = await prisma.guideProgress.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GuideProgressCreateManyArgs>(args?: Prisma.SelectSubset<T, GuideProgressCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GuideProgresses and returns the data saved in the database.
   * @param {GuideProgressCreateManyAndReturnArgs} args - Arguments to create many GuideProgresses.
   * @example
   * // Create many GuideProgresses
   * const guideProgress = await prisma.guideProgress.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GuideProgresses and only return the `id`
   * const guideProgressWithIdOnly = await prisma.guideProgress.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GuideProgressCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GuideProgressCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuideProgressPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GuideProgress.
   * @param {GuideProgressDeleteArgs} args - Arguments to delete one GuideProgress.
   * @example
   * // Delete one GuideProgress
   * const GuideProgress = await prisma.guideProgress.delete({
   *   where: {
   *     // ... filter to delete one GuideProgress
   *   }
   * })
   * 
   */
  delete<T extends GuideProgressDeleteArgs>(args: Prisma.SelectSubset<T, GuideProgressDeleteArgs<ExtArgs>>): Prisma.Prisma__GuideProgressClient<runtime.Types.Result.GetResult<Prisma.$GuideProgressPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GuideProgress.
   * @param {GuideProgressUpdateArgs} args - Arguments to update one GuideProgress.
   * @example
   * // Update one GuideProgress
   * const guideProgress = await prisma.guideProgress.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GuideProgressUpdateArgs>(args: Prisma.SelectSubset<T, GuideProgressUpdateArgs<ExtArgs>>): Prisma.Prisma__GuideProgressClient<runtime.Types.Result.GetResult<Prisma.$GuideProgressPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GuideProgresses.
   * @param {GuideProgressDeleteManyArgs} args - Arguments to filter GuideProgresses to delete.
   * @example
   * // Delete a few GuideProgresses
   * const { count } = await prisma.guideProgress.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GuideProgressDeleteManyArgs>(args?: Prisma.SelectSubset<T, GuideProgressDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GuideProgresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuideProgressUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GuideProgresses
   * const guideProgress = await prisma.guideProgress.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GuideProgressUpdateManyArgs>(args: Prisma.SelectSubset<T, GuideProgressUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GuideProgresses and returns the data updated in the database.
   * @param {GuideProgressUpdateManyAndReturnArgs} args - Arguments to update many GuideProgresses.
   * @example
   * // Update many GuideProgresses
   * const guideProgress = await prisma.guideProgress.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GuideProgresses and only return the `id`
   * const guideProgressWithIdOnly = await prisma.guideProgress.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GuideProgressUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GuideProgressUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GuideProgressPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GuideProgress.
   * @param {GuideProgressUpsertArgs} args - Arguments to update or create a GuideProgress.
   * @example
   * // Update or create a GuideProgress
   * const guideProgress = await prisma.guideProgress.upsert({
   *   create: {
   *     // ... data to create a GuideProgress
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GuideProgress we want to update
   *   }
   * })
   */
  upsert<T extends GuideProgressUpsertArgs>(args: Prisma.SelectSubset<T, GuideProgressUpsertArgs<ExtArgs>>): Prisma.Prisma__GuideProgressClient<runtime.Types.Result.GetResult<Prisma.$GuideProgressPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GuideProgresses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuideProgressCountArgs} args - Arguments to filter GuideProgresses to count.
   * @example
   * // Count the number of GuideProgresses
   * const count = await prisma.guideProgress.count({
   *   where: {
   *     // ... the filter for the GuideProgresses we want to count
   *   }
   * })
  **/
  count<T extends GuideProgressCountArgs>(
    args?: Prisma.Subset<T, GuideProgressCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GuideProgressCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GuideProgress.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuideProgressAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GuideProgressAggregateArgs>(args: Prisma.Subset<T, GuideProgressAggregateArgs>): Prisma.PrismaPromise<GetGuideProgressAggregateType<T>>

  /**
   * Group by GuideProgress.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GuideProgressGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GuideProgressGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GuideProgressGroupByArgs['orderBy'] }
      : { orderBy?: GuideProgressGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GuideProgressGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGuideProgressGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GuideProgress model
 */
readonly fields: GuideProgressFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GuideProgress.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GuideProgressClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GuideProgress model
 */
export interface GuideProgressFieldRefs {
  readonly id: Prisma.FieldRef<"GuideProgress", 'String'>
  readonly userId: Prisma.FieldRef<"GuideProgress", 'String'>
  readonly phase: Prisma.FieldRef<"GuideProgress", 'String'>
  readonly taskId: Prisma.FieldRef<"GuideProgress", 'String'>
  readonly completed: Prisma.FieldRef<"GuideProgress", 'Boolean'>
  readonly completedAt: Prisma.FieldRef<"GuideProgress", 'DateTime'>
}
    

// Custom InputTypes
/**
 * GuideProgress findUnique
 */
export type GuideProgressFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideProgress
   */
  select?: Prisma.GuideProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideProgress
   */
  omit?: Prisma.GuideProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideProgressInclude<ExtArgs> | null
  /**
   * Filter, which GuideProgress to fetch.
   */
  where: Prisma.GuideProgressWhereUniqueInput
}

/**
 * GuideProgress findUniqueOrThrow
 */
export type GuideProgressFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideProgress
   */
  select?: Prisma.GuideProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideProgress
   */
  omit?: Prisma.GuideProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideProgressInclude<ExtArgs> | null
  /**
   * Filter, which GuideProgress to fetch.
   */
  where: Prisma.GuideProgressWhereUniqueInput
}

/**
 * GuideProgress findFirst
 */
export type GuideProgressFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideProgress
   */
  select?: Prisma.GuideProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideProgress
   */
  omit?: Prisma.GuideProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideProgressInclude<ExtArgs> | null
  /**
   * Filter, which GuideProgress to fetch.
   */
  where?: Prisma.GuideProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuideProgresses to fetch.
   */
  orderBy?: Prisma.GuideProgressOrderByWithRelationInput | Prisma.GuideProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GuideProgresses.
   */
  cursor?: Prisma.GuideProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuideProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuideProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GuideProgresses.
   */
  distinct?: Prisma.GuideProgressScalarFieldEnum | Prisma.GuideProgressScalarFieldEnum[]
}

/**
 * GuideProgress findFirstOrThrow
 */
export type GuideProgressFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideProgress
   */
  select?: Prisma.GuideProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideProgress
   */
  omit?: Prisma.GuideProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideProgressInclude<ExtArgs> | null
  /**
   * Filter, which GuideProgress to fetch.
   */
  where?: Prisma.GuideProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuideProgresses to fetch.
   */
  orderBy?: Prisma.GuideProgressOrderByWithRelationInput | Prisma.GuideProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GuideProgresses.
   */
  cursor?: Prisma.GuideProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuideProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuideProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GuideProgresses.
   */
  distinct?: Prisma.GuideProgressScalarFieldEnum | Prisma.GuideProgressScalarFieldEnum[]
}

/**
 * GuideProgress findMany
 */
export type GuideProgressFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideProgress
   */
  select?: Prisma.GuideProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideProgress
   */
  omit?: Prisma.GuideProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideProgressInclude<ExtArgs> | null
  /**
   * Filter, which GuideProgresses to fetch.
   */
  where?: Prisma.GuideProgressWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GuideProgresses to fetch.
   */
  orderBy?: Prisma.GuideProgressOrderByWithRelationInput | Prisma.GuideProgressOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GuideProgresses.
   */
  cursor?: Prisma.GuideProgressWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GuideProgresses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GuideProgresses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GuideProgresses.
   */
  distinct?: Prisma.GuideProgressScalarFieldEnum | Prisma.GuideProgressScalarFieldEnum[]
}

/**
 * GuideProgress create
 */
export type GuideProgressCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideProgress
   */
  select?: Prisma.GuideProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideProgress
   */
  omit?: Prisma.GuideProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideProgressInclude<ExtArgs> | null
  /**
   * The data needed to create a GuideProgress.
   */
  data: Prisma.XOR<Prisma.GuideProgressCreateInput, Prisma.GuideProgressUncheckedCreateInput>
}

/**
 * GuideProgress createMany
 */
export type GuideProgressCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GuideProgresses.
   */
  data: Prisma.GuideProgressCreateManyInput | Prisma.GuideProgressCreateManyInput[]
}

/**
 * GuideProgress createManyAndReturn
 */
export type GuideProgressCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideProgress
   */
  select?: Prisma.GuideProgressSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GuideProgress
   */
  omit?: Prisma.GuideProgressOmit<ExtArgs> | null
  /**
   * The data used to create many GuideProgresses.
   */
  data: Prisma.GuideProgressCreateManyInput | Prisma.GuideProgressCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideProgressIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * GuideProgress update
 */
export type GuideProgressUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideProgress
   */
  select?: Prisma.GuideProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideProgress
   */
  omit?: Prisma.GuideProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideProgressInclude<ExtArgs> | null
  /**
   * The data needed to update a GuideProgress.
   */
  data: Prisma.XOR<Prisma.GuideProgressUpdateInput, Prisma.GuideProgressUncheckedUpdateInput>
  /**
   * Choose, which GuideProgress to update.
   */
  where: Prisma.GuideProgressWhereUniqueInput
}

/**
 * GuideProgress updateMany
 */
export type GuideProgressUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GuideProgresses.
   */
  data: Prisma.XOR<Prisma.GuideProgressUpdateManyMutationInput, Prisma.GuideProgressUncheckedUpdateManyInput>
  /**
   * Filter which GuideProgresses to update
   */
  where?: Prisma.GuideProgressWhereInput
  /**
   * Limit how many GuideProgresses to update.
   */
  limit?: number
}

/**
 * GuideProgress updateManyAndReturn
 */
export type GuideProgressUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideProgress
   */
  select?: Prisma.GuideProgressSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GuideProgress
   */
  omit?: Prisma.GuideProgressOmit<ExtArgs> | null
  /**
   * The data used to update GuideProgresses.
   */
  data: Prisma.XOR<Prisma.GuideProgressUpdateManyMutationInput, Prisma.GuideProgressUncheckedUpdateManyInput>
  /**
   * Filter which GuideProgresses to update
   */
  where?: Prisma.GuideProgressWhereInput
  /**
   * Limit how many GuideProgresses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideProgressIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * GuideProgress upsert
 */
export type GuideProgressUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideProgress
   */
  select?: Prisma.GuideProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideProgress
   */
  omit?: Prisma.GuideProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideProgressInclude<ExtArgs> | null
  /**
   * The filter to search for the GuideProgress to update in case it exists.
   */
  where: Prisma.GuideProgressWhereUniqueInput
  /**
   * In case the GuideProgress found by the `where` argument doesn't exist, create a new GuideProgress with this data.
   */
  create: Prisma.XOR<Prisma.GuideProgressCreateInput, Prisma.GuideProgressUncheckedCreateInput>
  /**
   * In case the GuideProgress was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GuideProgressUpdateInput, Prisma.GuideProgressUncheckedUpdateInput>
}

/**
 * GuideProgress delete
 */
export type GuideProgressDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideProgress
   */
  select?: Prisma.GuideProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideProgress
   */
  omit?: Prisma.GuideProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideProgressInclude<ExtArgs> | null
  /**
   * Filter which GuideProgress to delete.
   */
  where: Prisma.GuideProgressWhereUniqueInput
}

/**
 * GuideProgress deleteMany
 */
export type GuideProgressDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GuideProgresses to delete
   */
  where?: Prisma.GuideProgressWhereInput
  /**
   * Limit how many GuideProgresses to delete.
   */
  limit?: number
}

/**
 * GuideProgress without action
 */
export type GuideProgressDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GuideProgress
   */
  select?: Prisma.GuideProgressSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GuideProgress
   */
  omit?: Prisma.GuideProgressOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GuideProgressInclude<ExtArgs> | null
}
