
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Major` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Major
 * 
 */
export type MajorModel = runtime.Types.Result.DefaultSelection<Prisma.$MajorPayload>

export type AggregateMajor = {
  _count: MajorCountAggregateOutputType | null
  _avg: MajorAvgAggregateOutputType | null
  _sum: MajorSumAggregateOutputType | null
  _min: MajorMinAggregateOutputType | null
  _max: MajorMaxAggregateOutputType | null
}

export type MajorAvgAggregateOutputType = {
  aiRiskLevel: number | null
  employmentRate: number | null
  matchRate: number | null
}

export type MajorSumAggregateOutputType = {
  aiRiskLevel: number | null
  employmentRate: number | null
  matchRate: number | null
}

export type MajorMinAggregateOutputType = {
  id: string | null
  code: string | null
  name: string | null
  degree: string | null
  category: string | null
  description: string | null
  courses: string | null
  hardPoints: string | null
  abilities: string | null
  relatedMajors: string | null
  aiRisk: string | null
  aiRiskLevel: number | null
  employmentRate: number | null
  matchRate: number | null
}

export type MajorMaxAggregateOutputType = {
  id: string | null
  code: string | null
  name: string | null
  degree: string | null
  category: string | null
  description: string | null
  courses: string | null
  hardPoints: string | null
  abilities: string | null
  relatedMajors: string | null
  aiRisk: string | null
  aiRiskLevel: number | null
  employmentRate: number | null
  matchRate: number | null
}

export type MajorCountAggregateOutputType = {
  id: number
  code: number
  name: number
  degree: number
  category: number
  description: number
  courses: number
  hardPoints: number
  abilities: number
  relatedMajors: number
  aiRisk: number
  aiRiskLevel: number
  employmentRate: number
  matchRate: number
  _all: number
}


export type MajorAvgAggregateInputType = {
  aiRiskLevel?: true
  employmentRate?: true
  matchRate?: true
}

export type MajorSumAggregateInputType = {
  aiRiskLevel?: true
  employmentRate?: true
  matchRate?: true
}

export type MajorMinAggregateInputType = {
  id?: true
  code?: true
  name?: true
  degree?: true
  category?: true
  description?: true
  courses?: true
  hardPoints?: true
  abilities?: true
  relatedMajors?: true
  aiRisk?: true
  aiRiskLevel?: true
  employmentRate?: true
  matchRate?: true
}

export type MajorMaxAggregateInputType = {
  id?: true
  code?: true
  name?: true
  degree?: true
  category?: true
  description?: true
  courses?: true
  hardPoints?: true
  abilities?: true
  relatedMajors?: true
  aiRisk?: true
  aiRiskLevel?: true
  employmentRate?: true
  matchRate?: true
}

export type MajorCountAggregateInputType = {
  id?: true
  code?: true
  name?: true
  degree?: true
  category?: true
  description?: true
  courses?: true
  hardPoints?: true
  abilities?: true
  relatedMajors?: true
  aiRisk?: true
  aiRiskLevel?: true
  employmentRate?: true
  matchRate?: true
  _all?: true
}

export type MajorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Major to aggregate.
   */
  where?: Prisma.MajorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Majors to fetch.
   */
  orderBy?: Prisma.MajorOrderByWithRelationInput | Prisma.MajorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MajorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Majors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Majors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Majors
  **/
  _count?: true | MajorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MajorAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MajorSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MajorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MajorMaxAggregateInputType
}

export type GetMajorAggregateType<T extends MajorAggregateArgs> = {
      [P in keyof T & keyof AggregateMajor]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMajor[P]>
    : Prisma.GetScalarType<T[P], AggregateMajor[P]>
}




export type MajorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MajorWhereInput
  orderBy?: Prisma.MajorOrderByWithAggregationInput | Prisma.MajorOrderByWithAggregationInput[]
  by: Prisma.MajorScalarFieldEnum[] | Prisma.MajorScalarFieldEnum
  having?: Prisma.MajorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MajorCountAggregateInputType | true
  _avg?: MajorAvgAggregateInputType
  _sum?: MajorSumAggregateInputType
  _min?: MajorMinAggregateInputType
  _max?: MajorMaxAggregateInputType
}

export type MajorGroupByOutputType = {
  id: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate: number | null
  matchRate: number | null
  _count: MajorCountAggregateOutputType | null
  _avg: MajorAvgAggregateOutputType | null
  _sum: MajorSumAggregateOutputType | null
  _min: MajorMinAggregateOutputType | null
  _max: MajorMaxAggregateOutputType | null
}

export type GetMajorGroupByPayload<T extends MajorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MajorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MajorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MajorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MajorGroupByOutputType[P]>
      }
    >
  >



export type MajorWhereInput = {
  AND?: Prisma.MajorWhereInput | Prisma.MajorWhereInput[]
  OR?: Prisma.MajorWhereInput[]
  NOT?: Prisma.MajorWhereInput | Prisma.MajorWhereInput[]
  id?: Prisma.StringFilter<"Major"> | string
  code?: Prisma.StringFilter<"Major"> | string
  name?: Prisma.StringFilter<"Major"> | string
  degree?: Prisma.StringFilter<"Major"> | string
  category?: Prisma.StringFilter<"Major"> | string
  description?: Prisma.StringFilter<"Major"> | string
  courses?: Prisma.StringFilter<"Major"> | string
  hardPoints?: Prisma.StringFilter<"Major"> | string
  abilities?: Prisma.StringFilter<"Major"> | string
  relatedMajors?: Prisma.StringFilter<"Major"> | string
  aiRisk?: Prisma.StringFilter<"Major"> | string
  aiRiskLevel?: Prisma.IntFilter<"Major"> | number
  employmentRate?: Prisma.FloatNullableFilter<"Major"> | number | null
  matchRate?: Prisma.FloatNullableFilter<"Major"> | number | null
  employmentStats?: Prisma.EmploymentStatListRelationFilter
  careerPaths?: Prisma.CareerPathListRelationFilter
  salaries?: Prisma.SalaryListRelationFilter
  careerDays?: Prisma.CareerDayListRelationFilter
  universityMajors?: Prisma.UniversityMajorListRelationFilter
  regrets?: Prisma.RegretListRelationFilter
}

export type MajorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  degree?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  courses?: Prisma.SortOrder
  hardPoints?: Prisma.SortOrder
  abilities?: Prisma.SortOrder
  relatedMajors?: Prisma.SortOrder
  aiRisk?: Prisma.SortOrder
  aiRiskLevel?: Prisma.SortOrder
  employmentRate?: Prisma.SortOrderInput | Prisma.SortOrder
  matchRate?: Prisma.SortOrderInput | Prisma.SortOrder
  employmentStats?: Prisma.EmploymentStatOrderByRelationAggregateInput
  careerPaths?: Prisma.CareerPathOrderByRelationAggregateInput
  salaries?: Prisma.SalaryOrderByRelationAggregateInput
  careerDays?: Prisma.CareerDayOrderByRelationAggregateInput
  universityMajors?: Prisma.UniversityMajorOrderByRelationAggregateInput
  regrets?: Prisma.RegretOrderByRelationAggregateInput
}

export type MajorWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  code?: string
  AND?: Prisma.MajorWhereInput | Prisma.MajorWhereInput[]
  OR?: Prisma.MajorWhereInput[]
  NOT?: Prisma.MajorWhereInput | Prisma.MajorWhereInput[]
  name?: Prisma.StringFilter<"Major"> | string
  degree?: Prisma.StringFilter<"Major"> | string
  category?: Prisma.StringFilter<"Major"> | string
  description?: Prisma.StringFilter<"Major"> | string
  courses?: Prisma.StringFilter<"Major"> | string
  hardPoints?: Prisma.StringFilter<"Major"> | string
  abilities?: Prisma.StringFilter<"Major"> | string
  relatedMajors?: Prisma.StringFilter<"Major"> | string
  aiRisk?: Prisma.StringFilter<"Major"> | string
  aiRiskLevel?: Prisma.IntFilter<"Major"> | number
  employmentRate?: Prisma.FloatNullableFilter<"Major"> | number | null
  matchRate?: Prisma.FloatNullableFilter<"Major"> | number | null
  employmentStats?: Prisma.EmploymentStatListRelationFilter
  careerPaths?: Prisma.CareerPathListRelationFilter
  salaries?: Prisma.SalaryListRelationFilter
  careerDays?: Prisma.CareerDayListRelationFilter
  universityMajors?: Prisma.UniversityMajorListRelationFilter
  regrets?: Prisma.RegretListRelationFilter
}, "id" | "code">

export type MajorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  degree?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  courses?: Prisma.SortOrder
  hardPoints?: Prisma.SortOrder
  abilities?: Prisma.SortOrder
  relatedMajors?: Prisma.SortOrder
  aiRisk?: Prisma.SortOrder
  aiRiskLevel?: Prisma.SortOrder
  employmentRate?: Prisma.SortOrderInput | Prisma.SortOrder
  matchRate?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.MajorCountOrderByAggregateInput
  _avg?: Prisma.MajorAvgOrderByAggregateInput
  _max?: Prisma.MajorMaxOrderByAggregateInput
  _min?: Prisma.MajorMinOrderByAggregateInput
  _sum?: Prisma.MajorSumOrderByAggregateInput
}

export type MajorScalarWhereWithAggregatesInput = {
  AND?: Prisma.MajorScalarWhereWithAggregatesInput | Prisma.MajorScalarWhereWithAggregatesInput[]
  OR?: Prisma.MajorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MajorScalarWhereWithAggregatesInput | Prisma.MajorScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Major"> | string
  code?: Prisma.StringWithAggregatesFilter<"Major"> | string
  name?: Prisma.StringWithAggregatesFilter<"Major"> | string
  degree?: Prisma.StringWithAggregatesFilter<"Major"> | string
  category?: Prisma.StringWithAggregatesFilter<"Major"> | string
  description?: Prisma.StringWithAggregatesFilter<"Major"> | string
  courses?: Prisma.StringWithAggregatesFilter<"Major"> | string
  hardPoints?: Prisma.StringWithAggregatesFilter<"Major"> | string
  abilities?: Prisma.StringWithAggregatesFilter<"Major"> | string
  relatedMajors?: Prisma.StringWithAggregatesFilter<"Major"> | string
  aiRisk?: Prisma.StringWithAggregatesFilter<"Major"> | string
  aiRiskLevel?: Prisma.IntWithAggregatesFilter<"Major"> | number
  employmentRate?: Prisma.FloatNullableWithAggregatesFilter<"Major"> | number | null
  matchRate?: Prisma.FloatNullableWithAggregatesFilter<"Major"> | number | null
}

export type MajorCreateInput = {
  id?: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate?: number | null
  matchRate?: number | null
  employmentStats?: Prisma.EmploymentStatCreateNestedManyWithoutMajorInput
  careerPaths?: Prisma.CareerPathCreateNestedManyWithoutMajorInput
  salaries?: Prisma.SalaryCreateNestedManyWithoutMajorInput
  careerDays?: Prisma.CareerDayCreateNestedManyWithoutMajorInput
  universityMajors?: Prisma.UniversityMajorCreateNestedManyWithoutMajorInput
  regrets?: Prisma.RegretCreateNestedManyWithoutMajorInput
}

export type MajorUncheckedCreateInput = {
  id?: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate?: number | null
  matchRate?: number | null
  employmentStats?: Prisma.EmploymentStatUncheckedCreateNestedManyWithoutMajorInput
  careerPaths?: Prisma.CareerPathUncheckedCreateNestedManyWithoutMajorInput
  salaries?: Prisma.SalaryUncheckedCreateNestedManyWithoutMajorInput
  careerDays?: Prisma.CareerDayUncheckedCreateNestedManyWithoutMajorInput
  universityMajors?: Prisma.UniversityMajorUncheckedCreateNestedManyWithoutMajorInput
  regrets?: Prisma.RegretUncheckedCreateNestedManyWithoutMajorInput
}

export type MajorUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  employmentStats?: Prisma.EmploymentStatUpdateManyWithoutMajorNestedInput
  careerPaths?: Prisma.CareerPathUpdateManyWithoutMajorNestedInput
  salaries?: Prisma.SalaryUpdateManyWithoutMajorNestedInput
  careerDays?: Prisma.CareerDayUpdateManyWithoutMajorNestedInput
  universityMajors?: Prisma.UniversityMajorUpdateManyWithoutMajorNestedInput
  regrets?: Prisma.RegretUpdateManyWithoutMajorNestedInput
}

export type MajorUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  employmentStats?: Prisma.EmploymentStatUncheckedUpdateManyWithoutMajorNestedInput
  careerPaths?: Prisma.CareerPathUncheckedUpdateManyWithoutMajorNestedInput
  salaries?: Prisma.SalaryUncheckedUpdateManyWithoutMajorNestedInput
  careerDays?: Prisma.CareerDayUncheckedUpdateManyWithoutMajorNestedInput
  universityMajors?: Prisma.UniversityMajorUncheckedUpdateManyWithoutMajorNestedInput
  regrets?: Prisma.RegretUncheckedUpdateManyWithoutMajorNestedInput
}

export type MajorCreateManyInput = {
  id?: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate?: number | null
  matchRate?: number | null
}

export type MajorUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type MajorUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type MajorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  degree?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  courses?: Prisma.SortOrder
  hardPoints?: Prisma.SortOrder
  abilities?: Prisma.SortOrder
  relatedMajors?: Prisma.SortOrder
  aiRisk?: Prisma.SortOrder
  aiRiskLevel?: Prisma.SortOrder
  employmentRate?: Prisma.SortOrder
  matchRate?: Prisma.SortOrder
}

export type MajorAvgOrderByAggregateInput = {
  aiRiskLevel?: Prisma.SortOrder
  employmentRate?: Prisma.SortOrder
  matchRate?: Prisma.SortOrder
}

export type MajorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  degree?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  courses?: Prisma.SortOrder
  hardPoints?: Prisma.SortOrder
  abilities?: Prisma.SortOrder
  relatedMajors?: Prisma.SortOrder
  aiRisk?: Prisma.SortOrder
  aiRiskLevel?: Prisma.SortOrder
  employmentRate?: Prisma.SortOrder
  matchRate?: Prisma.SortOrder
}

export type MajorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  code?: Prisma.SortOrder
  name?: Prisma.SortOrder
  degree?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  courses?: Prisma.SortOrder
  hardPoints?: Prisma.SortOrder
  abilities?: Prisma.SortOrder
  relatedMajors?: Prisma.SortOrder
  aiRisk?: Prisma.SortOrder
  aiRiskLevel?: Prisma.SortOrder
  employmentRate?: Prisma.SortOrder
  matchRate?: Prisma.SortOrder
}

export type MajorSumOrderByAggregateInput = {
  aiRiskLevel?: Prisma.SortOrder
  employmentRate?: Prisma.SortOrder
  matchRate?: Prisma.SortOrder
}

export type MajorScalarRelationFilter = {
  is?: Prisma.MajorWhereInput
  isNot?: Prisma.MajorWhereInput
}

export type MajorNullableScalarRelationFilter = {
  is?: Prisma.MajorWhereInput | null
  isNot?: Prisma.MajorWhereInput | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type MajorCreateNestedOneWithoutUniversityMajorsInput = {
  create?: Prisma.XOR<Prisma.MajorCreateWithoutUniversityMajorsInput, Prisma.MajorUncheckedCreateWithoutUniversityMajorsInput>
  connectOrCreate?: Prisma.MajorCreateOrConnectWithoutUniversityMajorsInput
  connect?: Prisma.MajorWhereUniqueInput
}

export type MajorUpdateOneRequiredWithoutUniversityMajorsNestedInput = {
  create?: Prisma.XOR<Prisma.MajorCreateWithoutUniversityMajorsInput, Prisma.MajorUncheckedCreateWithoutUniversityMajorsInput>
  connectOrCreate?: Prisma.MajorCreateOrConnectWithoutUniversityMajorsInput
  upsert?: Prisma.MajorUpsertWithoutUniversityMajorsInput
  connect?: Prisma.MajorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MajorUpdateToOneWithWhereWithoutUniversityMajorsInput, Prisma.MajorUpdateWithoutUniversityMajorsInput>, Prisma.MajorUncheckedUpdateWithoutUniversityMajorsInput>
}

export type MajorCreateNestedOneWithoutEmploymentStatsInput = {
  create?: Prisma.XOR<Prisma.MajorCreateWithoutEmploymentStatsInput, Prisma.MajorUncheckedCreateWithoutEmploymentStatsInput>
  connectOrCreate?: Prisma.MajorCreateOrConnectWithoutEmploymentStatsInput
  connect?: Prisma.MajorWhereUniqueInput
}

export type MajorUpdateOneRequiredWithoutEmploymentStatsNestedInput = {
  create?: Prisma.XOR<Prisma.MajorCreateWithoutEmploymentStatsInput, Prisma.MajorUncheckedCreateWithoutEmploymentStatsInput>
  connectOrCreate?: Prisma.MajorCreateOrConnectWithoutEmploymentStatsInput
  upsert?: Prisma.MajorUpsertWithoutEmploymentStatsInput
  connect?: Prisma.MajorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MajorUpdateToOneWithWhereWithoutEmploymentStatsInput, Prisma.MajorUpdateWithoutEmploymentStatsInput>, Prisma.MajorUncheckedUpdateWithoutEmploymentStatsInput>
}

export type MajorCreateNestedOneWithoutCareerPathsInput = {
  create?: Prisma.XOR<Prisma.MajorCreateWithoutCareerPathsInput, Prisma.MajorUncheckedCreateWithoutCareerPathsInput>
  connectOrCreate?: Prisma.MajorCreateOrConnectWithoutCareerPathsInput
  connect?: Prisma.MajorWhereUniqueInput
}

export type MajorUpdateOneRequiredWithoutCareerPathsNestedInput = {
  create?: Prisma.XOR<Prisma.MajorCreateWithoutCareerPathsInput, Prisma.MajorUncheckedCreateWithoutCareerPathsInput>
  connectOrCreate?: Prisma.MajorCreateOrConnectWithoutCareerPathsInput
  upsert?: Prisma.MajorUpsertWithoutCareerPathsInput
  connect?: Prisma.MajorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MajorUpdateToOneWithWhereWithoutCareerPathsInput, Prisma.MajorUpdateWithoutCareerPathsInput>, Prisma.MajorUncheckedUpdateWithoutCareerPathsInput>
}

export type MajorCreateNestedOneWithoutSalariesInput = {
  create?: Prisma.XOR<Prisma.MajorCreateWithoutSalariesInput, Prisma.MajorUncheckedCreateWithoutSalariesInput>
  connectOrCreate?: Prisma.MajorCreateOrConnectWithoutSalariesInput
  connect?: Prisma.MajorWhereUniqueInput
}

export type MajorUpdateOneRequiredWithoutSalariesNestedInput = {
  create?: Prisma.XOR<Prisma.MajorCreateWithoutSalariesInput, Prisma.MajorUncheckedCreateWithoutSalariesInput>
  connectOrCreate?: Prisma.MajorCreateOrConnectWithoutSalariesInput
  upsert?: Prisma.MajorUpsertWithoutSalariesInput
  connect?: Prisma.MajorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MajorUpdateToOneWithWhereWithoutSalariesInput, Prisma.MajorUpdateWithoutSalariesInput>, Prisma.MajorUncheckedUpdateWithoutSalariesInput>
}

export type MajorCreateNestedOneWithoutCareerDaysInput = {
  create?: Prisma.XOR<Prisma.MajorCreateWithoutCareerDaysInput, Prisma.MajorUncheckedCreateWithoutCareerDaysInput>
  connectOrCreate?: Prisma.MajorCreateOrConnectWithoutCareerDaysInput
  connect?: Prisma.MajorWhereUniqueInput
}

export type MajorUpdateOneWithoutCareerDaysNestedInput = {
  create?: Prisma.XOR<Prisma.MajorCreateWithoutCareerDaysInput, Prisma.MajorUncheckedCreateWithoutCareerDaysInput>
  connectOrCreate?: Prisma.MajorCreateOrConnectWithoutCareerDaysInput
  upsert?: Prisma.MajorUpsertWithoutCareerDaysInput
  disconnect?: Prisma.MajorWhereInput | boolean
  delete?: Prisma.MajorWhereInput | boolean
  connect?: Prisma.MajorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MajorUpdateToOneWithWhereWithoutCareerDaysInput, Prisma.MajorUpdateWithoutCareerDaysInput>, Prisma.MajorUncheckedUpdateWithoutCareerDaysInput>
}

export type MajorCreateNestedOneWithoutRegretsInput = {
  create?: Prisma.XOR<Prisma.MajorCreateWithoutRegretsInput, Prisma.MajorUncheckedCreateWithoutRegretsInput>
  connectOrCreate?: Prisma.MajorCreateOrConnectWithoutRegretsInput
  connect?: Prisma.MajorWhereUniqueInput
}

export type MajorUpdateOneWithoutRegretsNestedInput = {
  create?: Prisma.XOR<Prisma.MajorCreateWithoutRegretsInput, Prisma.MajorUncheckedCreateWithoutRegretsInput>
  connectOrCreate?: Prisma.MajorCreateOrConnectWithoutRegretsInput
  upsert?: Prisma.MajorUpsertWithoutRegretsInput
  disconnect?: Prisma.MajorWhereInput | boolean
  delete?: Prisma.MajorWhereInput | boolean
  connect?: Prisma.MajorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MajorUpdateToOneWithWhereWithoutRegretsInput, Prisma.MajorUpdateWithoutRegretsInput>, Prisma.MajorUncheckedUpdateWithoutRegretsInput>
}

export type MajorCreateWithoutUniversityMajorsInput = {
  id?: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate?: number | null
  matchRate?: number | null
  employmentStats?: Prisma.EmploymentStatCreateNestedManyWithoutMajorInput
  careerPaths?: Prisma.CareerPathCreateNestedManyWithoutMajorInput
  salaries?: Prisma.SalaryCreateNestedManyWithoutMajorInput
  careerDays?: Prisma.CareerDayCreateNestedManyWithoutMajorInput
  regrets?: Prisma.RegretCreateNestedManyWithoutMajorInput
}

export type MajorUncheckedCreateWithoutUniversityMajorsInput = {
  id?: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate?: number | null
  matchRate?: number | null
  employmentStats?: Prisma.EmploymentStatUncheckedCreateNestedManyWithoutMajorInput
  careerPaths?: Prisma.CareerPathUncheckedCreateNestedManyWithoutMajorInput
  salaries?: Prisma.SalaryUncheckedCreateNestedManyWithoutMajorInput
  careerDays?: Prisma.CareerDayUncheckedCreateNestedManyWithoutMajorInput
  regrets?: Prisma.RegretUncheckedCreateNestedManyWithoutMajorInput
}

export type MajorCreateOrConnectWithoutUniversityMajorsInput = {
  where: Prisma.MajorWhereUniqueInput
  create: Prisma.XOR<Prisma.MajorCreateWithoutUniversityMajorsInput, Prisma.MajorUncheckedCreateWithoutUniversityMajorsInput>
}

export type MajorUpsertWithoutUniversityMajorsInput = {
  update: Prisma.XOR<Prisma.MajorUpdateWithoutUniversityMajorsInput, Prisma.MajorUncheckedUpdateWithoutUniversityMajorsInput>
  create: Prisma.XOR<Prisma.MajorCreateWithoutUniversityMajorsInput, Prisma.MajorUncheckedCreateWithoutUniversityMajorsInput>
  where?: Prisma.MajorWhereInput
}

export type MajorUpdateToOneWithWhereWithoutUniversityMajorsInput = {
  where?: Prisma.MajorWhereInput
  data: Prisma.XOR<Prisma.MajorUpdateWithoutUniversityMajorsInput, Prisma.MajorUncheckedUpdateWithoutUniversityMajorsInput>
}

export type MajorUpdateWithoutUniversityMajorsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  employmentStats?: Prisma.EmploymentStatUpdateManyWithoutMajorNestedInput
  careerPaths?: Prisma.CareerPathUpdateManyWithoutMajorNestedInput
  salaries?: Prisma.SalaryUpdateManyWithoutMajorNestedInput
  careerDays?: Prisma.CareerDayUpdateManyWithoutMajorNestedInput
  regrets?: Prisma.RegretUpdateManyWithoutMajorNestedInput
}

export type MajorUncheckedUpdateWithoutUniversityMajorsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  employmentStats?: Prisma.EmploymentStatUncheckedUpdateManyWithoutMajorNestedInput
  careerPaths?: Prisma.CareerPathUncheckedUpdateManyWithoutMajorNestedInput
  salaries?: Prisma.SalaryUncheckedUpdateManyWithoutMajorNestedInput
  careerDays?: Prisma.CareerDayUncheckedUpdateManyWithoutMajorNestedInput
  regrets?: Prisma.RegretUncheckedUpdateManyWithoutMajorNestedInput
}

export type MajorCreateWithoutEmploymentStatsInput = {
  id?: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate?: number | null
  matchRate?: number | null
  careerPaths?: Prisma.CareerPathCreateNestedManyWithoutMajorInput
  salaries?: Prisma.SalaryCreateNestedManyWithoutMajorInput
  careerDays?: Prisma.CareerDayCreateNestedManyWithoutMajorInput
  universityMajors?: Prisma.UniversityMajorCreateNestedManyWithoutMajorInput
  regrets?: Prisma.RegretCreateNestedManyWithoutMajorInput
}

export type MajorUncheckedCreateWithoutEmploymentStatsInput = {
  id?: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate?: number | null
  matchRate?: number | null
  careerPaths?: Prisma.CareerPathUncheckedCreateNestedManyWithoutMajorInput
  salaries?: Prisma.SalaryUncheckedCreateNestedManyWithoutMajorInput
  careerDays?: Prisma.CareerDayUncheckedCreateNestedManyWithoutMajorInput
  universityMajors?: Prisma.UniversityMajorUncheckedCreateNestedManyWithoutMajorInput
  regrets?: Prisma.RegretUncheckedCreateNestedManyWithoutMajorInput
}

export type MajorCreateOrConnectWithoutEmploymentStatsInput = {
  where: Prisma.MajorWhereUniqueInput
  create: Prisma.XOR<Prisma.MajorCreateWithoutEmploymentStatsInput, Prisma.MajorUncheckedCreateWithoutEmploymentStatsInput>
}

export type MajorUpsertWithoutEmploymentStatsInput = {
  update: Prisma.XOR<Prisma.MajorUpdateWithoutEmploymentStatsInput, Prisma.MajorUncheckedUpdateWithoutEmploymentStatsInput>
  create: Prisma.XOR<Prisma.MajorCreateWithoutEmploymentStatsInput, Prisma.MajorUncheckedCreateWithoutEmploymentStatsInput>
  where?: Prisma.MajorWhereInput
}

export type MajorUpdateToOneWithWhereWithoutEmploymentStatsInput = {
  where?: Prisma.MajorWhereInput
  data: Prisma.XOR<Prisma.MajorUpdateWithoutEmploymentStatsInput, Prisma.MajorUncheckedUpdateWithoutEmploymentStatsInput>
}

export type MajorUpdateWithoutEmploymentStatsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  careerPaths?: Prisma.CareerPathUpdateManyWithoutMajorNestedInput
  salaries?: Prisma.SalaryUpdateManyWithoutMajorNestedInput
  careerDays?: Prisma.CareerDayUpdateManyWithoutMajorNestedInput
  universityMajors?: Prisma.UniversityMajorUpdateManyWithoutMajorNestedInput
  regrets?: Prisma.RegretUpdateManyWithoutMajorNestedInput
}

export type MajorUncheckedUpdateWithoutEmploymentStatsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  careerPaths?: Prisma.CareerPathUncheckedUpdateManyWithoutMajorNestedInput
  salaries?: Prisma.SalaryUncheckedUpdateManyWithoutMajorNestedInput
  careerDays?: Prisma.CareerDayUncheckedUpdateManyWithoutMajorNestedInput
  universityMajors?: Prisma.UniversityMajorUncheckedUpdateManyWithoutMajorNestedInput
  regrets?: Prisma.RegretUncheckedUpdateManyWithoutMajorNestedInput
}

export type MajorCreateWithoutCareerPathsInput = {
  id?: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate?: number | null
  matchRate?: number | null
  employmentStats?: Prisma.EmploymentStatCreateNestedManyWithoutMajorInput
  salaries?: Prisma.SalaryCreateNestedManyWithoutMajorInput
  careerDays?: Prisma.CareerDayCreateNestedManyWithoutMajorInput
  universityMajors?: Prisma.UniversityMajorCreateNestedManyWithoutMajorInput
  regrets?: Prisma.RegretCreateNestedManyWithoutMajorInput
}

export type MajorUncheckedCreateWithoutCareerPathsInput = {
  id?: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate?: number | null
  matchRate?: number | null
  employmentStats?: Prisma.EmploymentStatUncheckedCreateNestedManyWithoutMajorInput
  salaries?: Prisma.SalaryUncheckedCreateNestedManyWithoutMajorInput
  careerDays?: Prisma.CareerDayUncheckedCreateNestedManyWithoutMajorInput
  universityMajors?: Prisma.UniversityMajorUncheckedCreateNestedManyWithoutMajorInput
  regrets?: Prisma.RegretUncheckedCreateNestedManyWithoutMajorInput
}

export type MajorCreateOrConnectWithoutCareerPathsInput = {
  where: Prisma.MajorWhereUniqueInput
  create: Prisma.XOR<Prisma.MajorCreateWithoutCareerPathsInput, Prisma.MajorUncheckedCreateWithoutCareerPathsInput>
}

export type MajorUpsertWithoutCareerPathsInput = {
  update: Prisma.XOR<Prisma.MajorUpdateWithoutCareerPathsInput, Prisma.MajorUncheckedUpdateWithoutCareerPathsInput>
  create: Prisma.XOR<Prisma.MajorCreateWithoutCareerPathsInput, Prisma.MajorUncheckedCreateWithoutCareerPathsInput>
  where?: Prisma.MajorWhereInput
}

export type MajorUpdateToOneWithWhereWithoutCareerPathsInput = {
  where?: Prisma.MajorWhereInput
  data: Prisma.XOR<Prisma.MajorUpdateWithoutCareerPathsInput, Prisma.MajorUncheckedUpdateWithoutCareerPathsInput>
}

export type MajorUpdateWithoutCareerPathsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  employmentStats?: Prisma.EmploymentStatUpdateManyWithoutMajorNestedInput
  salaries?: Prisma.SalaryUpdateManyWithoutMajorNestedInput
  careerDays?: Prisma.CareerDayUpdateManyWithoutMajorNestedInput
  universityMajors?: Prisma.UniversityMajorUpdateManyWithoutMajorNestedInput
  regrets?: Prisma.RegretUpdateManyWithoutMajorNestedInput
}

export type MajorUncheckedUpdateWithoutCareerPathsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  employmentStats?: Prisma.EmploymentStatUncheckedUpdateManyWithoutMajorNestedInput
  salaries?: Prisma.SalaryUncheckedUpdateManyWithoutMajorNestedInput
  careerDays?: Prisma.CareerDayUncheckedUpdateManyWithoutMajorNestedInput
  universityMajors?: Prisma.UniversityMajorUncheckedUpdateManyWithoutMajorNestedInput
  regrets?: Prisma.RegretUncheckedUpdateManyWithoutMajorNestedInput
}

export type MajorCreateWithoutSalariesInput = {
  id?: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate?: number | null
  matchRate?: number | null
  employmentStats?: Prisma.EmploymentStatCreateNestedManyWithoutMajorInput
  careerPaths?: Prisma.CareerPathCreateNestedManyWithoutMajorInput
  careerDays?: Prisma.CareerDayCreateNestedManyWithoutMajorInput
  universityMajors?: Prisma.UniversityMajorCreateNestedManyWithoutMajorInput
  regrets?: Prisma.RegretCreateNestedManyWithoutMajorInput
}

export type MajorUncheckedCreateWithoutSalariesInput = {
  id?: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate?: number | null
  matchRate?: number | null
  employmentStats?: Prisma.EmploymentStatUncheckedCreateNestedManyWithoutMajorInput
  careerPaths?: Prisma.CareerPathUncheckedCreateNestedManyWithoutMajorInput
  careerDays?: Prisma.CareerDayUncheckedCreateNestedManyWithoutMajorInput
  universityMajors?: Prisma.UniversityMajorUncheckedCreateNestedManyWithoutMajorInput
  regrets?: Prisma.RegretUncheckedCreateNestedManyWithoutMajorInput
}

export type MajorCreateOrConnectWithoutSalariesInput = {
  where: Prisma.MajorWhereUniqueInput
  create: Prisma.XOR<Prisma.MajorCreateWithoutSalariesInput, Prisma.MajorUncheckedCreateWithoutSalariesInput>
}

export type MajorUpsertWithoutSalariesInput = {
  update: Prisma.XOR<Prisma.MajorUpdateWithoutSalariesInput, Prisma.MajorUncheckedUpdateWithoutSalariesInput>
  create: Prisma.XOR<Prisma.MajorCreateWithoutSalariesInput, Prisma.MajorUncheckedCreateWithoutSalariesInput>
  where?: Prisma.MajorWhereInput
}

export type MajorUpdateToOneWithWhereWithoutSalariesInput = {
  where?: Prisma.MajorWhereInput
  data: Prisma.XOR<Prisma.MajorUpdateWithoutSalariesInput, Prisma.MajorUncheckedUpdateWithoutSalariesInput>
}

export type MajorUpdateWithoutSalariesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  employmentStats?: Prisma.EmploymentStatUpdateManyWithoutMajorNestedInput
  careerPaths?: Prisma.CareerPathUpdateManyWithoutMajorNestedInput
  careerDays?: Prisma.CareerDayUpdateManyWithoutMajorNestedInput
  universityMajors?: Prisma.UniversityMajorUpdateManyWithoutMajorNestedInput
  regrets?: Prisma.RegretUpdateManyWithoutMajorNestedInput
}

export type MajorUncheckedUpdateWithoutSalariesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  employmentStats?: Prisma.EmploymentStatUncheckedUpdateManyWithoutMajorNestedInput
  careerPaths?: Prisma.CareerPathUncheckedUpdateManyWithoutMajorNestedInput
  careerDays?: Prisma.CareerDayUncheckedUpdateManyWithoutMajorNestedInput
  universityMajors?: Prisma.UniversityMajorUncheckedUpdateManyWithoutMajorNestedInput
  regrets?: Prisma.RegretUncheckedUpdateManyWithoutMajorNestedInput
}

export type MajorCreateWithoutCareerDaysInput = {
  id?: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate?: number | null
  matchRate?: number | null
  employmentStats?: Prisma.EmploymentStatCreateNestedManyWithoutMajorInput
  careerPaths?: Prisma.CareerPathCreateNestedManyWithoutMajorInput
  salaries?: Prisma.SalaryCreateNestedManyWithoutMajorInput
  universityMajors?: Prisma.UniversityMajorCreateNestedManyWithoutMajorInput
  regrets?: Prisma.RegretCreateNestedManyWithoutMajorInput
}

export type MajorUncheckedCreateWithoutCareerDaysInput = {
  id?: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate?: number | null
  matchRate?: number | null
  employmentStats?: Prisma.EmploymentStatUncheckedCreateNestedManyWithoutMajorInput
  careerPaths?: Prisma.CareerPathUncheckedCreateNestedManyWithoutMajorInput
  salaries?: Prisma.SalaryUncheckedCreateNestedManyWithoutMajorInput
  universityMajors?: Prisma.UniversityMajorUncheckedCreateNestedManyWithoutMajorInput
  regrets?: Prisma.RegretUncheckedCreateNestedManyWithoutMajorInput
}

export type MajorCreateOrConnectWithoutCareerDaysInput = {
  where: Prisma.MajorWhereUniqueInput
  create: Prisma.XOR<Prisma.MajorCreateWithoutCareerDaysInput, Prisma.MajorUncheckedCreateWithoutCareerDaysInput>
}

export type MajorUpsertWithoutCareerDaysInput = {
  update: Prisma.XOR<Prisma.MajorUpdateWithoutCareerDaysInput, Prisma.MajorUncheckedUpdateWithoutCareerDaysInput>
  create: Prisma.XOR<Prisma.MajorCreateWithoutCareerDaysInput, Prisma.MajorUncheckedCreateWithoutCareerDaysInput>
  where?: Prisma.MajorWhereInput
}

export type MajorUpdateToOneWithWhereWithoutCareerDaysInput = {
  where?: Prisma.MajorWhereInput
  data: Prisma.XOR<Prisma.MajorUpdateWithoutCareerDaysInput, Prisma.MajorUncheckedUpdateWithoutCareerDaysInput>
}

export type MajorUpdateWithoutCareerDaysInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  employmentStats?: Prisma.EmploymentStatUpdateManyWithoutMajorNestedInput
  careerPaths?: Prisma.CareerPathUpdateManyWithoutMajorNestedInput
  salaries?: Prisma.SalaryUpdateManyWithoutMajorNestedInput
  universityMajors?: Prisma.UniversityMajorUpdateManyWithoutMajorNestedInput
  regrets?: Prisma.RegretUpdateManyWithoutMajorNestedInput
}

export type MajorUncheckedUpdateWithoutCareerDaysInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  employmentStats?: Prisma.EmploymentStatUncheckedUpdateManyWithoutMajorNestedInput
  careerPaths?: Prisma.CareerPathUncheckedUpdateManyWithoutMajorNestedInput
  salaries?: Prisma.SalaryUncheckedUpdateManyWithoutMajorNestedInput
  universityMajors?: Prisma.UniversityMajorUncheckedUpdateManyWithoutMajorNestedInput
  regrets?: Prisma.RegretUncheckedUpdateManyWithoutMajorNestedInput
}

export type MajorCreateWithoutRegretsInput = {
  id?: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate?: number | null
  matchRate?: number | null
  employmentStats?: Prisma.EmploymentStatCreateNestedManyWithoutMajorInput
  careerPaths?: Prisma.CareerPathCreateNestedManyWithoutMajorInput
  salaries?: Prisma.SalaryCreateNestedManyWithoutMajorInput
  careerDays?: Prisma.CareerDayCreateNestedManyWithoutMajorInput
  universityMajors?: Prisma.UniversityMajorCreateNestedManyWithoutMajorInput
}

export type MajorUncheckedCreateWithoutRegretsInput = {
  id?: string
  code: string
  name: string
  degree: string
  category: string
  description: string
  courses: string
  hardPoints: string
  abilities: string
  relatedMajors: string
  aiRisk: string
  aiRiskLevel: number
  employmentRate?: number | null
  matchRate?: number | null
  employmentStats?: Prisma.EmploymentStatUncheckedCreateNestedManyWithoutMajorInput
  careerPaths?: Prisma.CareerPathUncheckedCreateNestedManyWithoutMajorInput
  salaries?: Prisma.SalaryUncheckedCreateNestedManyWithoutMajorInput
  careerDays?: Prisma.CareerDayUncheckedCreateNestedManyWithoutMajorInput
  universityMajors?: Prisma.UniversityMajorUncheckedCreateNestedManyWithoutMajorInput
}

export type MajorCreateOrConnectWithoutRegretsInput = {
  where: Prisma.MajorWhereUniqueInput
  create: Prisma.XOR<Prisma.MajorCreateWithoutRegretsInput, Prisma.MajorUncheckedCreateWithoutRegretsInput>
}

export type MajorUpsertWithoutRegretsInput = {
  update: Prisma.XOR<Prisma.MajorUpdateWithoutRegretsInput, Prisma.MajorUncheckedUpdateWithoutRegretsInput>
  create: Prisma.XOR<Prisma.MajorCreateWithoutRegretsInput, Prisma.MajorUncheckedCreateWithoutRegretsInput>
  where?: Prisma.MajorWhereInput
}

export type MajorUpdateToOneWithWhereWithoutRegretsInput = {
  where?: Prisma.MajorWhereInput
  data: Prisma.XOR<Prisma.MajorUpdateWithoutRegretsInput, Prisma.MajorUncheckedUpdateWithoutRegretsInput>
}

export type MajorUpdateWithoutRegretsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  employmentStats?: Prisma.EmploymentStatUpdateManyWithoutMajorNestedInput
  careerPaths?: Prisma.CareerPathUpdateManyWithoutMajorNestedInput
  salaries?: Prisma.SalaryUpdateManyWithoutMajorNestedInput
  careerDays?: Prisma.CareerDayUpdateManyWithoutMajorNestedInput
  universityMajors?: Prisma.UniversityMajorUpdateManyWithoutMajorNestedInput
}

export type MajorUncheckedUpdateWithoutRegretsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  degree?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.StringFieldUpdateOperationsInput | string
  hardPoints?: Prisma.StringFieldUpdateOperationsInput | string
  abilities?: Prisma.StringFieldUpdateOperationsInput | string
  relatedMajors?: Prisma.StringFieldUpdateOperationsInput | string
  aiRisk?: Prisma.StringFieldUpdateOperationsInput | string
  aiRiskLevel?: Prisma.IntFieldUpdateOperationsInput | number
  employmentRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  matchRate?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  employmentStats?: Prisma.EmploymentStatUncheckedUpdateManyWithoutMajorNestedInput
  careerPaths?: Prisma.CareerPathUncheckedUpdateManyWithoutMajorNestedInput
  salaries?: Prisma.SalaryUncheckedUpdateManyWithoutMajorNestedInput
  careerDays?: Prisma.CareerDayUncheckedUpdateManyWithoutMajorNestedInput
  universityMajors?: Prisma.UniversityMajorUncheckedUpdateManyWithoutMajorNestedInput
}


/**
 * Count Type MajorCountOutputType
 */

export type MajorCountOutputType = {
  employmentStats: number
  careerPaths: number
  salaries: number
  careerDays: number
  universityMajors: number
  regrets: number
}

export type MajorCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  employmentStats?: boolean | MajorCountOutputTypeCountEmploymentStatsArgs
  careerPaths?: boolean | MajorCountOutputTypeCountCareerPathsArgs
  salaries?: boolean | MajorCountOutputTypeCountSalariesArgs
  careerDays?: boolean | MajorCountOutputTypeCountCareerDaysArgs
  universityMajors?: boolean | MajorCountOutputTypeCountUniversityMajorsArgs
  regrets?: boolean | MajorCountOutputTypeCountRegretsArgs
}

/**
 * MajorCountOutputType without action
 */
export type MajorCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MajorCountOutputType
   */
  select?: Prisma.MajorCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MajorCountOutputType without action
 */
export type MajorCountOutputTypeCountEmploymentStatsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmploymentStatWhereInput
}

/**
 * MajorCountOutputType without action
 */
export type MajorCountOutputTypeCountCareerPathsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CareerPathWhereInput
}

/**
 * MajorCountOutputType without action
 */
export type MajorCountOutputTypeCountSalariesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SalaryWhereInput
}

/**
 * MajorCountOutputType without action
 */
export type MajorCountOutputTypeCountCareerDaysArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CareerDayWhereInput
}

/**
 * MajorCountOutputType without action
 */
export type MajorCountOutputTypeCountUniversityMajorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UniversityMajorWhereInput
}

/**
 * MajorCountOutputType without action
 */
export type MajorCountOutputTypeCountRegretsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RegretWhereInput
}


export type MajorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  degree?: boolean
  category?: boolean
  description?: boolean
  courses?: boolean
  hardPoints?: boolean
  abilities?: boolean
  relatedMajors?: boolean
  aiRisk?: boolean
  aiRiskLevel?: boolean
  employmentRate?: boolean
  matchRate?: boolean
  employmentStats?: boolean | Prisma.Major$employmentStatsArgs<ExtArgs>
  careerPaths?: boolean | Prisma.Major$careerPathsArgs<ExtArgs>
  salaries?: boolean | Prisma.Major$salariesArgs<ExtArgs>
  careerDays?: boolean | Prisma.Major$careerDaysArgs<ExtArgs>
  universityMajors?: boolean | Prisma.Major$universityMajorsArgs<ExtArgs>
  regrets?: boolean | Prisma.Major$regretsArgs<ExtArgs>
  _count?: boolean | Prisma.MajorCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["major"]>

export type MajorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  degree?: boolean
  category?: boolean
  description?: boolean
  courses?: boolean
  hardPoints?: boolean
  abilities?: boolean
  relatedMajors?: boolean
  aiRisk?: boolean
  aiRiskLevel?: boolean
  employmentRate?: boolean
  matchRate?: boolean
}, ExtArgs["result"]["major"]>

export type MajorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  code?: boolean
  name?: boolean
  degree?: boolean
  category?: boolean
  description?: boolean
  courses?: boolean
  hardPoints?: boolean
  abilities?: boolean
  relatedMajors?: boolean
  aiRisk?: boolean
  aiRiskLevel?: boolean
  employmentRate?: boolean
  matchRate?: boolean
}, ExtArgs["result"]["major"]>

export type MajorSelectScalar = {
  id?: boolean
  code?: boolean
  name?: boolean
  degree?: boolean
  category?: boolean
  description?: boolean
  courses?: boolean
  hardPoints?: boolean
  abilities?: boolean
  relatedMajors?: boolean
  aiRisk?: boolean
  aiRiskLevel?: boolean
  employmentRate?: boolean
  matchRate?: boolean
}

export type MajorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "code" | "name" | "degree" | "category" | "description" | "courses" | "hardPoints" | "abilities" | "relatedMajors" | "aiRisk" | "aiRiskLevel" | "employmentRate" | "matchRate", ExtArgs["result"]["major"]>
export type MajorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  employmentStats?: boolean | Prisma.Major$employmentStatsArgs<ExtArgs>
  careerPaths?: boolean | Prisma.Major$careerPathsArgs<ExtArgs>
  salaries?: boolean | Prisma.Major$salariesArgs<ExtArgs>
  careerDays?: boolean | Prisma.Major$careerDaysArgs<ExtArgs>
  universityMajors?: boolean | Prisma.Major$universityMajorsArgs<ExtArgs>
  regrets?: boolean | Prisma.Major$regretsArgs<ExtArgs>
  _count?: boolean | Prisma.MajorCountOutputTypeDefaultArgs<ExtArgs>
}
export type MajorIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type MajorIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $MajorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Major"
  objects: {
    employmentStats: Prisma.$EmploymentStatPayload<ExtArgs>[]
    careerPaths: Prisma.$CareerPathPayload<ExtArgs>[]
    salaries: Prisma.$SalaryPayload<ExtArgs>[]
    careerDays: Prisma.$CareerDayPayload<ExtArgs>[]
    universityMajors: Prisma.$UniversityMajorPayload<ExtArgs>[]
    regrets: Prisma.$RegretPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    code: string
    name: string
    degree: string
    category: string
    description: string
    courses: string
    hardPoints: string
    abilities: string
    relatedMajors: string
    aiRisk: string
    aiRiskLevel: number
    employmentRate: number | null
    matchRate: number | null
  }, ExtArgs["result"]["major"]>
  composites: {}
}

export type MajorGetPayload<S extends boolean | null | undefined | MajorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MajorPayload, S>

export type MajorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MajorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MajorCountAggregateInputType | true
  }

export interface MajorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Major'], meta: { name: 'Major' } }
  /**
   * Find zero or one Major that matches the filter.
   * @param {MajorFindUniqueArgs} args - Arguments to find a Major
   * @example
   * // Get one Major
   * const major = await prisma.major.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MajorFindUniqueArgs>(args: Prisma.SelectSubset<T, MajorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MajorClient<runtime.Types.Result.GetResult<Prisma.$MajorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Major that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MajorFindUniqueOrThrowArgs} args - Arguments to find a Major
   * @example
   * // Get one Major
   * const major = await prisma.major.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MajorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MajorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MajorClient<runtime.Types.Result.GetResult<Prisma.$MajorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Major that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MajorFindFirstArgs} args - Arguments to find a Major
   * @example
   * // Get one Major
   * const major = await prisma.major.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MajorFindFirstArgs>(args?: Prisma.SelectSubset<T, MajorFindFirstArgs<ExtArgs>>): Prisma.Prisma__MajorClient<runtime.Types.Result.GetResult<Prisma.$MajorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Major that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MajorFindFirstOrThrowArgs} args - Arguments to find a Major
   * @example
   * // Get one Major
   * const major = await prisma.major.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MajorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MajorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MajorClient<runtime.Types.Result.GetResult<Prisma.$MajorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Majors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MajorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Majors
   * const majors = await prisma.major.findMany()
   * 
   * // Get first 10 Majors
   * const majors = await prisma.major.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const majorWithIdOnly = await prisma.major.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MajorFindManyArgs>(args?: Prisma.SelectSubset<T, MajorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MajorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Major.
   * @param {MajorCreateArgs} args - Arguments to create a Major.
   * @example
   * // Create one Major
   * const Major = await prisma.major.create({
   *   data: {
   *     // ... data to create a Major
   *   }
   * })
   * 
   */
  create<T extends MajorCreateArgs>(args: Prisma.SelectSubset<T, MajorCreateArgs<ExtArgs>>): Prisma.Prisma__MajorClient<runtime.Types.Result.GetResult<Prisma.$MajorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Majors.
   * @param {MajorCreateManyArgs} args - Arguments to create many Majors.
   * @example
   * // Create many Majors
   * const major = await prisma.major.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MajorCreateManyArgs>(args?: Prisma.SelectSubset<T, MajorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Majors and returns the data saved in the database.
   * @param {MajorCreateManyAndReturnArgs} args - Arguments to create many Majors.
   * @example
   * // Create many Majors
   * const major = await prisma.major.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Majors and only return the `id`
   * const majorWithIdOnly = await prisma.major.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MajorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MajorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MajorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Major.
   * @param {MajorDeleteArgs} args - Arguments to delete one Major.
   * @example
   * // Delete one Major
   * const Major = await prisma.major.delete({
   *   where: {
   *     // ... filter to delete one Major
   *   }
   * })
   * 
   */
  delete<T extends MajorDeleteArgs>(args: Prisma.SelectSubset<T, MajorDeleteArgs<ExtArgs>>): Prisma.Prisma__MajorClient<runtime.Types.Result.GetResult<Prisma.$MajorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Major.
   * @param {MajorUpdateArgs} args - Arguments to update one Major.
   * @example
   * // Update one Major
   * const major = await prisma.major.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MajorUpdateArgs>(args: Prisma.SelectSubset<T, MajorUpdateArgs<ExtArgs>>): Prisma.Prisma__MajorClient<runtime.Types.Result.GetResult<Prisma.$MajorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Majors.
   * @param {MajorDeleteManyArgs} args - Arguments to filter Majors to delete.
   * @example
   * // Delete a few Majors
   * const { count } = await prisma.major.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MajorDeleteManyArgs>(args?: Prisma.SelectSubset<T, MajorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Majors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MajorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Majors
   * const major = await prisma.major.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MajorUpdateManyArgs>(args: Prisma.SelectSubset<T, MajorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Majors and returns the data updated in the database.
   * @param {MajorUpdateManyAndReturnArgs} args - Arguments to update many Majors.
   * @example
   * // Update many Majors
   * const major = await prisma.major.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Majors and only return the `id`
   * const majorWithIdOnly = await prisma.major.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MajorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MajorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MajorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Major.
   * @param {MajorUpsertArgs} args - Arguments to update or create a Major.
   * @example
   * // Update or create a Major
   * const major = await prisma.major.upsert({
   *   create: {
   *     // ... data to create a Major
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Major we want to update
   *   }
   * })
   */
  upsert<T extends MajorUpsertArgs>(args: Prisma.SelectSubset<T, MajorUpsertArgs<ExtArgs>>): Prisma.Prisma__MajorClient<runtime.Types.Result.GetResult<Prisma.$MajorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Majors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MajorCountArgs} args - Arguments to filter Majors to count.
   * @example
   * // Count the number of Majors
   * const count = await prisma.major.count({
   *   where: {
   *     // ... the filter for the Majors we want to count
   *   }
   * })
  **/
  count<T extends MajorCountArgs>(
    args?: Prisma.Subset<T, MajorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MajorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Major.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MajorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MajorAggregateArgs>(args: Prisma.Subset<T, MajorAggregateArgs>): Prisma.PrismaPromise<GetMajorAggregateType<T>>

  /**
   * Group by Major.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MajorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MajorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MajorGroupByArgs['orderBy'] }
      : { orderBy?: MajorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MajorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMajorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Major model
 */
readonly fields: MajorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Major.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MajorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  employmentStats<T extends Prisma.Major$employmentStatsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Major$employmentStatsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmploymentStatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  careerPaths<T extends Prisma.Major$careerPathsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Major$careerPathsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CareerPathPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  salaries<T extends Prisma.Major$salariesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Major$salariesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SalaryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  careerDays<T extends Prisma.Major$careerDaysArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Major$careerDaysArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CareerDayPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  universityMajors<T extends Prisma.Major$universityMajorsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Major$universityMajorsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UniversityMajorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  regrets<T extends Prisma.Major$regretsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Major$regretsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegretPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Major model
 */
export interface MajorFieldRefs {
  readonly id: Prisma.FieldRef<"Major", 'String'>
  readonly code: Prisma.FieldRef<"Major", 'String'>
  readonly name: Prisma.FieldRef<"Major", 'String'>
  readonly degree: Prisma.FieldRef<"Major", 'String'>
  readonly category: Prisma.FieldRef<"Major", 'String'>
  readonly description: Prisma.FieldRef<"Major", 'String'>
  readonly courses: Prisma.FieldRef<"Major", 'String'>
  readonly hardPoints: Prisma.FieldRef<"Major", 'String'>
  readonly abilities: Prisma.FieldRef<"Major", 'String'>
  readonly relatedMajors: Prisma.FieldRef<"Major", 'String'>
  readonly aiRisk: Prisma.FieldRef<"Major", 'String'>
  readonly aiRiskLevel: Prisma.FieldRef<"Major", 'Int'>
  readonly employmentRate: Prisma.FieldRef<"Major", 'Float'>
  readonly matchRate: Prisma.FieldRef<"Major", 'Float'>
}
    

// Custom InputTypes
/**
 * Major findUnique
 */
export type MajorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Major
   */
  select?: Prisma.MajorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Major
   */
  omit?: Prisma.MajorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorInclude<ExtArgs> | null
  /**
   * Filter, which Major to fetch.
   */
  where: Prisma.MajorWhereUniqueInput
}

/**
 * Major findUniqueOrThrow
 */
export type MajorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Major
   */
  select?: Prisma.MajorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Major
   */
  omit?: Prisma.MajorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorInclude<ExtArgs> | null
  /**
   * Filter, which Major to fetch.
   */
  where: Prisma.MajorWhereUniqueInput
}

/**
 * Major findFirst
 */
export type MajorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Major
   */
  select?: Prisma.MajorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Major
   */
  omit?: Prisma.MajorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorInclude<ExtArgs> | null
  /**
   * Filter, which Major to fetch.
   */
  where?: Prisma.MajorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Majors to fetch.
   */
  orderBy?: Prisma.MajorOrderByWithRelationInput | Prisma.MajorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Majors.
   */
  cursor?: Prisma.MajorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Majors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Majors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Majors.
   */
  distinct?: Prisma.MajorScalarFieldEnum | Prisma.MajorScalarFieldEnum[]
}

/**
 * Major findFirstOrThrow
 */
export type MajorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Major
   */
  select?: Prisma.MajorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Major
   */
  omit?: Prisma.MajorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorInclude<ExtArgs> | null
  /**
   * Filter, which Major to fetch.
   */
  where?: Prisma.MajorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Majors to fetch.
   */
  orderBy?: Prisma.MajorOrderByWithRelationInput | Prisma.MajorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Majors.
   */
  cursor?: Prisma.MajorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Majors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Majors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Majors.
   */
  distinct?: Prisma.MajorScalarFieldEnum | Prisma.MajorScalarFieldEnum[]
}

/**
 * Major findMany
 */
export type MajorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Major
   */
  select?: Prisma.MajorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Major
   */
  omit?: Prisma.MajorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorInclude<ExtArgs> | null
  /**
   * Filter, which Majors to fetch.
   */
  where?: Prisma.MajorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Majors to fetch.
   */
  orderBy?: Prisma.MajorOrderByWithRelationInput | Prisma.MajorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Majors.
   */
  cursor?: Prisma.MajorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Majors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Majors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Majors.
   */
  distinct?: Prisma.MajorScalarFieldEnum | Prisma.MajorScalarFieldEnum[]
}

/**
 * Major create
 */
export type MajorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Major
   */
  select?: Prisma.MajorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Major
   */
  omit?: Prisma.MajorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorInclude<ExtArgs> | null
  /**
   * The data needed to create a Major.
   */
  data: Prisma.XOR<Prisma.MajorCreateInput, Prisma.MajorUncheckedCreateInput>
}

/**
 * Major createMany
 */
export type MajorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Majors.
   */
  data: Prisma.MajorCreateManyInput | Prisma.MajorCreateManyInput[]
}

/**
 * Major createManyAndReturn
 */
export type MajorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Major
   */
  select?: Prisma.MajorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Major
   */
  omit?: Prisma.MajorOmit<ExtArgs> | null
  /**
   * The data used to create many Majors.
   */
  data: Prisma.MajorCreateManyInput | Prisma.MajorCreateManyInput[]
}

/**
 * Major update
 */
export type MajorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Major
   */
  select?: Prisma.MajorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Major
   */
  omit?: Prisma.MajorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorInclude<ExtArgs> | null
  /**
   * The data needed to update a Major.
   */
  data: Prisma.XOR<Prisma.MajorUpdateInput, Prisma.MajorUncheckedUpdateInput>
  /**
   * Choose, which Major to update.
   */
  where: Prisma.MajorWhereUniqueInput
}

/**
 * Major updateMany
 */
export type MajorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Majors.
   */
  data: Prisma.XOR<Prisma.MajorUpdateManyMutationInput, Prisma.MajorUncheckedUpdateManyInput>
  /**
   * Filter which Majors to update
   */
  where?: Prisma.MajorWhereInput
  /**
   * Limit how many Majors to update.
   */
  limit?: number
}

/**
 * Major updateManyAndReturn
 */
export type MajorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Major
   */
  select?: Prisma.MajorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Major
   */
  omit?: Prisma.MajorOmit<ExtArgs> | null
  /**
   * The data used to update Majors.
   */
  data: Prisma.XOR<Prisma.MajorUpdateManyMutationInput, Prisma.MajorUncheckedUpdateManyInput>
  /**
   * Filter which Majors to update
   */
  where?: Prisma.MajorWhereInput
  /**
   * Limit how many Majors to update.
   */
  limit?: number
}

/**
 * Major upsert
 */
export type MajorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Major
   */
  select?: Prisma.MajorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Major
   */
  omit?: Prisma.MajorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorInclude<ExtArgs> | null
  /**
   * The filter to search for the Major to update in case it exists.
   */
  where: Prisma.MajorWhereUniqueInput
  /**
   * In case the Major found by the `where` argument doesn't exist, create a new Major with this data.
   */
  create: Prisma.XOR<Prisma.MajorCreateInput, Prisma.MajorUncheckedCreateInput>
  /**
   * In case the Major was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MajorUpdateInput, Prisma.MajorUncheckedUpdateInput>
}

/**
 * Major delete
 */
export type MajorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Major
   */
  select?: Prisma.MajorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Major
   */
  omit?: Prisma.MajorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorInclude<ExtArgs> | null
  /**
   * Filter which Major to delete.
   */
  where: Prisma.MajorWhereUniqueInput
}

/**
 * Major deleteMany
 */
export type MajorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Majors to delete
   */
  where?: Prisma.MajorWhereInput
  /**
   * Limit how many Majors to delete.
   */
  limit?: number
}

/**
 * Major.employmentStats
 */
export type Major$employmentStatsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmploymentStat
   */
  select?: Prisma.EmploymentStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmploymentStat
   */
  omit?: Prisma.EmploymentStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmploymentStatInclude<ExtArgs> | null
  where?: Prisma.EmploymentStatWhereInput
  orderBy?: Prisma.EmploymentStatOrderByWithRelationInput | Prisma.EmploymentStatOrderByWithRelationInput[]
  cursor?: Prisma.EmploymentStatWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EmploymentStatScalarFieldEnum | Prisma.EmploymentStatScalarFieldEnum[]
}

/**
 * Major.careerPaths
 */
export type Major$careerPathsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerPath
   */
  select?: Prisma.CareerPathSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerPath
   */
  omit?: Prisma.CareerPathOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerPathInclude<ExtArgs> | null
  where?: Prisma.CareerPathWhereInput
  orderBy?: Prisma.CareerPathOrderByWithRelationInput | Prisma.CareerPathOrderByWithRelationInput[]
  cursor?: Prisma.CareerPathWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CareerPathScalarFieldEnum | Prisma.CareerPathScalarFieldEnum[]
}

/**
 * Major.salaries
 */
export type Major$salariesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Salary
   */
  select?: Prisma.SalarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Salary
   */
  omit?: Prisma.SalaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SalaryInclude<ExtArgs> | null
  where?: Prisma.SalaryWhereInput
  orderBy?: Prisma.SalaryOrderByWithRelationInput | Prisma.SalaryOrderByWithRelationInput[]
  cursor?: Prisma.SalaryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SalaryScalarFieldEnum | Prisma.SalaryScalarFieldEnum[]
}

/**
 * Major.careerDays
 */
export type Major$careerDaysArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CareerDay
   */
  select?: Prisma.CareerDaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CareerDay
   */
  omit?: Prisma.CareerDayOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CareerDayInclude<ExtArgs> | null
  where?: Prisma.CareerDayWhereInput
  orderBy?: Prisma.CareerDayOrderByWithRelationInput | Prisma.CareerDayOrderByWithRelationInput[]
  cursor?: Prisma.CareerDayWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CareerDayScalarFieldEnum | Prisma.CareerDayScalarFieldEnum[]
}

/**
 * Major.universityMajors
 */
export type Major$universityMajorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UniversityMajor
   */
  select?: Prisma.UniversityMajorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UniversityMajor
   */
  omit?: Prisma.UniversityMajorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UniversityMajorInclude<ExtArgs> | null
  where?: Prisma.UniversityMajorWhereInput
  orderBy?: Prisma.UniversityMajorOrderByWithRelationInput | Prisma.UniversityMajorOrderByWithRelationInput[]
  cursor?: Prisma.UniversityMajorWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UniversityMajorScalarFieldEnum | Prisma.UniversityMajorScalarFieldEnum[]
}

/**
 * Major.regrets
 */
export type Major$regretsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Regret
   */
  select?: Prisma.RegretSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Regret
   */
  omit?: Prisma.RegretOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegretInclude<ExtArgs> | null
  where?: Prisma.RegretWhereInput
  orderBy?: Prisma.RegretOrderByWithRelationInput | Prisma.RegretOrderByWithRelationInput[]
  cursor?: Prisma.RegretWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RegretScalarFieldEnum | Prisma.RegretScalarFieldEnum[]
}

/**
 * Major without action
 */
export type MajorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Major
   */
  select?: Prisma.MajorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Major
   */
  omit?: Prisma.MajorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorInclude<ExtArgs> | null
}
