
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Regret` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Regret
 * 
 */
export type RegretModel = runtime.Types.Result.DefaultSelection<Prisma.$RegretPayload>

export type AggregateRegret = {
  _count: RegretCountAggregateOutputType | null
  _min: RegretMinAggregateOutputType | null
  _max: RegretMaxAggregateOutputType | null
}

export type RegretMinAggregateOutputType = {
  id: string | null
  grade: string | null
  category: string | null
  content: string | null
  tags: string | null
  isLate: boolean | null
  remedy: string | null
  majorId: string | null
}

export type RegretMaxAggregateOutputType = {
  id: string | null
  grade: string | null
  category: string | null
  content: string | null
  tags: string | null
  isLate: boolean | null
  remedy: string | null
  majorId: string | null
}

export type RegretCountAggregateOutputType = {
  id: number
  grade: number
  category: number
  content: number
  tags: number
  isLate: number
  remedy: number
  majorId: number
  _all: number
}


export type RegretMinAggregateInputType = {
  id?: true
  grade?: true
  category?: true
  content?: true
  tags?: true
  isLate?: true
  remedy?: true
  majorId?: true
}

export type RegretMaxAggregateInputType = {
  id?: true
  grade?: true
  category?: true
  content?: true
  tags?: true
  isLate?: true
  remedy?: true
  majorId?: true
}

export type RegretCountAggregateInputType = {
  id?: true
  grade?: true
  category?: true
  content?: true
  tags?: true
  isLate?: true
  remedy?: true
  majorId?: true
  _all?: true
}

export type RegretAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Regret to aggregate.
   */
  where?: Prisma.RegretWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Regrets to fetch.
   */
  orderBy?: Prisma.RegretOrderByWithRelationInput | Prisma.RegretOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RegretWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Regrets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Regrets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Regrets
  **/
  _count?: true | RegretCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RegretMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RegretMaxAggregateInputType
}

export type GetRegretAggregateType<T extends RegretAggregateArgs> = {
      [P in keyof T & keyof AggregateRegret]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRegret[P]>
    : Prisma.GetScalarType<T[P], AggregateRegret[P]>
}




export type RegretGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RegretWhereInput
  orderBy?: Prisma.RegretOrderByWithAggregationInput | Prisma.RegretOrderByWithAggregationInput[]
  by: Prisma.RegretScalarFieldEnum[] | Prisma.RegretScalarFieldEnum
  having?: Prisma.RegretScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RegretCountAggregateInputType | true
  _min?: RegretMinAggregateInputType
  _max?: RegretMaxAggregateInputType
}

export type RegretGroupByOutputType = {
  id: string
  grade: string
  category: string
  content: string
  tags: string
  isLate: boolean
  remedy: string | null
  majorId: string | null
  _count: RegretCountAggregateOutputType | null
  _min: RegretMinAggregateOutputType | null
  _max: RegretMaxAggregateOutputType | null
}

export type GetRegretGroupByPayload<T extends RegretGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RegretGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RegretGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RegretGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RegretGroupByOutputType[P]>
      }
    >
  >



export type RegretWhereInput = {
  AND?: Prisma.RegretWhereInput | Prisma.RegretWhereInput[]
  OR?: Prisma.RegretWhereInput[]
  NOT?: Prisma.RegretWhereInput | Prisma.RegretWhereInput[]
  id?: Prisma.StringFilter<"Regret"> | string
  grade?: Prisma.StringFilter<"Regret"> | string
  category?: Prisma.StringFilter<"Regret"> | string
  content?: Prisma.StringFilter<"Regret"> | string
  tags?: Prisma.StringFilter<"Regret"> | string
  isLate?: Prisma.BoolFilter<"Regret"> | boolean
  remedy?: Prisma.StringNullableFilter<"Regret"> | string | null
  majorId?: Prisma.StringNullableFilter<"Regret"> | string | null
  major?: Prisma.XOR<Prisma.MajorNullableScalarRelationFilter, Prisma.MajorWhereInput> | null
  userSaves?: Prisma.UserRegretListRelationFilter
}

export type RegretOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  category?: Prisma.SortOrder
  content?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  isLate?: Prisma.SortOrder
  remedy?: Prisma.SortOrderInput | Prisma.SortOrder
  majorId?: Prisma.SortOrderInput | Prisma.SortOrder
  major?: Prisma.MajorOrderByWithRelationInput
  userSaves?: Prisma.UserRegretOrderByRelationAggregateInput
}

export type RegretWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RegretWhereInput | Prisma.RegretWhereInput[]
  OR?: Prisma.RegretWhereInput[]
  NOT?: Prisma.RegretWhereInput | Prisma.RegretWhereInput[]
  grade?: Prisma.StringFilter<"Regret"> | string
  category?: Prisma.StringFilter<"Regret"> | string
  content?: Prisma.StringFilter<"Regret"> | string
  tags?: Prisma.StringFilter<"Regret"> | string
  isLate?: Prisma.BoolFilter<"Regret"> | boolean
  remedy?: Prisma.StringNullableFilter<"Regret"> | string | null
  majorId?: Prisma.StringNullableFilter<"Regret"> | string | null
  major?: Prisma.XOR<Prisma.MajorNullableScalarRelationFilter, Prisma.MajorWhereInput> | null
  userSaves?: Prisma.UserRegretListRelationFilter
}, "id">

export type RegretOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  category?: Prisma.SortOrder
  content?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  isLate?: Prisma.SortOrder
  remedy?: Prisma.SortOrderInput | Prisma.SortOrder
  majorId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.RegretCountOrderByAggregateInput
  _max?: Prisma.RegretMaxOrderByAggregateInput
  _min?: Prisma.RegretMinOrderByAggregateInput
}

export type RegretScalarWhereWithAggregatesInput = {
  AND?: Prisma.RegretScalarWhereWithAggregatesInput | Prisma.RegretScalarWhereWithAggregatesInput[]
  OR?: Prisma.RegretScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RegretScalarWhereWithAggregatesInput | Prisma.RegretScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Regret"> | string
  grade?: Prisma.StringWithAggregatesFilter<"Regret"> | string
  category?: Prisma.StringWithAggregatesFilter<"Regret"> | string
  content?: Prisma.StringWithAggregatesFilter<"Regret"> | string
  tags?: Prisma.StringWithAggregatesFilter<"Regret"> | string
  isLate?: Prisma.BoolWithAggregatesFilter<"Regret"> | boolean
  remedy?: Prisma.StringNullableWithAggregatesFilter<"Regret"> | string | null
  majorId?: Prisma.StringNullableWithAggregatesFilter<"Regret"> | string | null
}

export type RegretCreateInput = {
  id?: string
  grade: string
  category: string
  content: string
  tags: string
  isLate: boolean
  remedy?: string | null
  major?: Prisma.MajorCreateNestedOneWithoutRegretsInput
  userSaves?: Prisma.UserRegretCreateNestedManyWithoutRegretInput
}

export type RegretUncheckedCreateInput = {
  id?: string
  grade: string
  category: string
  content: string
  tags: string
  isLate: boolean
  remedy?: string | null
  majorId?: string | null
  userSaves?: Prisma.UserRegretUncheckedCreateNestedManyWithoutRegretInput
}

export type RegretUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  isLate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remedy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  major?: Prisma.MajorUpdateOneWithoutRegretsNestedInput
  userSaves?: Prisma.UserRegretUpdateManyWithoutRegretNestedInput
}

export type RegretUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  isLate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remedy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  majorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userSaves?: Prisma.UserRegretUncheckedUpdateManyWithoutRegretNestedInput
}

export type RegretCreateManyInput = {
  id?: string
  grade: string
  category: string
  content: string
  tags: string
  isLate: boolean
  remedy?: string | null
  majorId?: string | null
}

export type RegretUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  isLate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remedy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RegretUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  isLate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remedy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  majorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RegretListRelationFilter = {
  every?: Prisma.RegretWhereInput
  some?: Prisma.RegretWhereInput
  none?: Prisma.RegretWhereInput
}

export type RegretOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RegretCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  category?: Prisma.SortOrder
  content?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  isLate?: Prisma.SortOrder
  remedy?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
}

export type RegretMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  category?: Prisma.SortOrder
  content?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  isLate?: Prisma.SortOrder
  remedy?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
}

export type RegretMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  grade?: Prisma.SortOrder
  category?: Prisma.SortOrder
  content?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  isLate?: Prisma.SortOrder
  remedy?: Prisma.SortOrder
  majorId?: Prisma.SortOrder
}

export type RegretScalarRelationFilter = {
  is?: Prisma.RegretWhereInput
  isNot?: Prisma.RegretWhereInput
}

export type RegretCreateNestedManyWithoutMajorInput = {
  create?: Prisma.XOR<Prisma.RegretCreateWithoutMajorInput, Prisma.RegretUncheckedCreateWithoutMajorInput> | Prisma.RegretCreateWithoutMajorInput[] | Prisma.RegretUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.RegretCreateOrConnectWithoutMajorInput | Prisma.RegretCreateOrConnectWithoutMajorInput[]
  createMany?: Prisma.RegretCreateManyMajorInputEnvelope
  connect?: Prisma.RegretWhereUniqueInput | Prisma.RegretWhereUniqueInput[]
}

export type RegretUncheckedCreateNestedManyWithoutMajorInput = {
  create?: Prisma.XOR<Prisma.RegretCreateWithoutMajorInput, Prisma.RegretUncheckedCreateWithoutMajorInput> | Prisma.RegretCreateWithoutMajorInput[] | Prisma.RegretUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.RegretCreateOrConnectWithoutMajorInput | Prisma.RegretCreateOrConnectWithoutMajorInput[]
  createMany?: Prisma.RegretCreateManyMajorInputEnvelope
  connect?: Prisma.RegretWhereUniqueInput | Prisma.RegretWhereUniqueInput[]
}

export type RegretUpdateManyWithoutMajorNestedInput = {
  create?: Prisma.XOR<Prisma.RegretCreateWithoutMajorInput, Prisma.RegretUncheckedCreateWithoutMajorInput> | Prisma.RegretCreateWithoutMajorInput[] | Prisma.RegretUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.RegretCreateOrConnectWithoutMajorInput | Prisma.RegretCreateOrConnectWithoutMajorInput[]
  upsert?: Prisma.RegretUpsertWithWhereUniqueWithoutMajorInput | Prisma.RegretUpsertWithWhereUniqueWithoutMajorInput[]
  createMany?: Prisma.RegretCreateManyMajorInputEnvelope
  set?: Prisma.RegretWhereUniqueInput | Prisma.RegretWhereUniqueInput[]
  disconnect?: Prisma.RegretWhereUniqueInput | Prisma.RegretWhereUniqueInput[]
  delete?: Prisma.RegretWhereUniqueInput | Prisma.RegretWhereUniqueInput[]
  connect?: Prisma.RegretWhereUniqueInput | Prisma.RegretWhereUniqueInput[]
  update?: Prisma.RegretUpdateWithWhereUniqueWithoutMajorInput | Prisma.RegretUpdateWithWhereUniqueWithoutMajorInput[]
  updateMany?: Prisma.RegretUpdateManyWithWhereWithoutMajorInput | Prisma.RegretUpdateManyWithWhereWithoutMajorInput[]
  deleteMany?: Prisma.RegretScalarWhereInput | Prisma.RegretScalarWhereInput[]
}

export type RegretUncheckedUpdateManyWithoutMajorNestedInput = {
  create?: Prisma.XOR<Prisma.RegretCreateWithoutMajorInput, Prisma.RegretUncheckedCreateWithoutMajorInput> | Prisma.RegretCreateWithoutMajorInput[] | Prisma.RegretUncheckedCreateWithoutMajorInput[]
  connectOrCreate?: Prisma.RegretCreateOrConnectWithoutMajorInput | Prisma.RegretCreateOrConnectWithoutMajorInput[]
  upsert?: Prisma.RegretUpsertWithWhereUniqueWithoutMajorInput | Prisma.RegretUpsertWithWhereUniqueWithoutMajorInput[]
  createMany?: Prisma.RegretCreateManyMajorInputEnvelope
  set?: Prisma.RegretWhereUniqueInput | Prisma.RegretWhereUniqueInput[]
  disconnect?: Prisma.RegretWhereUniqueInput | Prisma.RegretWhereUniqueInput[]
  delete?: Prisma.RegretWhereUniqueInput | Prisma.RegretWhereUniqueInput[]
  connect?: Prisma.RegretWhereUniqueInput | Prisma.RegretWhereUniqueInput[]
  update?: Prisma.RegretUpdateWithWhereUniqueWithoutMajorInput | Prisma.RegretUpdateWithWhereUniqueWithoutMajorInput[]
  updateMany?: Prisma.RegretUpdateManyWithWhereWithoutMajorInput | Prisma.RegretUpdateManyWithWhereWithoutMajorInput[]
  deleteMany?: Prisma.RegretScalarWhereInput | Prisma.RegretScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type RegretCreateNestedOneWithoutUserSavesInput = {
  create?: Prisma.XOR<Prisma.RegretCreateWithoutUserSavesInput, Prisma.RegretUncheckedCreateWithoutUserSavesInput>
  connectOrCreate?: Prisma.RegretCreateOrConnectWithoutUserSavesInput
  connect?: Prisma.RegretWhereUniqueInput
}

export type RegretUpdateOneRequiredWithoutUserSavesNestedInput = {
  create?: Prisma.XOR<Prisma.RegretCreateWithoutUserSavesInput, Prisma.RegretUncheckedCreateWithoutUserSavesInput>
  connectOrCreate?: Prisma.RegretCreateOrConnectWithoutUserSavesInput
  upsert?: Prisma.RegretUpsertWithoutUserSavesInput
  connect?: Prisma.RegretWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.RegretUpdateToOneWithWhereWithoutUserSavesInput, Prisma.RegretUpdateWithoutUserSavesInput>, Prisma.RegretUncheckedUpdateWithoutUserSavesInput>
}

export type RegretCreateWithoutMajorInput = {
  id?: string
  grade: string
  category: string
  content: string
  tags: string
  isLate: boolean
  remedy?: string | null
  userSaves?: Prisma.UserRegretCreateNestedManyWithoutRegretInput
}

export type RegretUncheckedCreateWithoutMajorInput = {
  id?: string
  grade: string
  category: string
  content: string
  tags: string
  isLate: boolean
  remedy?: string | null
  userSaves?: Prisma.UserRegretUncheckedCreateNestedManyWithoutRegretInput
}

export type RegretCreateOrConnectWithoutMajorInput = {
  where: Prisma.RegretWhereUniqueInput
  create: Prisma.XOR<Prisma.RegretCreateWithoutMajorInput, Prisma.RegretUncheckedCreateWithoutMajorInput>
}

export type RegretCreateManyMajorInputEnvelope = {
  data: Prisma.RegretCreateManyMajorInput | Prisma.RegretCreateManyMajorInput[]
}

export type RegretUpsertWithWhereUniqueWithoutMajorInput = {
  where: Prisma.RegretWhereUniqueInput
  update: Prisma.XOR<Prisma.RegretUpdateWithoutMajorInput, Prisma.RegretUncheckedUpdateWithoutMajorInput>
  create: Prisma.XOR<Prisma.RegretCreateWithoutMajorInput, Prisma.RegretUncheckedCreateWithoutMajorInput>
}

export type RegretUpdateWithWhereUniqueWithoutMajorInput = {
  where: Prisma.RegretWhereUniqueInput
  data: Prisma.XOR<Prisma.RegretUpdateWithoutMajorInput, Prisma.RegretUncheckedUpdateWithoutMajorInput>
}

export type RegretUpdateManyWithWhereWithoutMajorInput = {
  where: Prisma.RegretScalarWhereInput
  data: Prisma.XOR<Prisma.RegretUpdateManyMutationInput, Prisma.RegretUncheckedUpdateManyWithoutMajorInput>
}

export type RegretScalarWhereInput = {
  AND?: Prisma.RegretScalarWhereInput | Prisma.RegretScalarWhereInput[]
  OR?: Prisma.RegretScalarWhereInput[]
  NOT?: Prisma.RegretScalarWhereInput | Prisma.RegretScalarWhereInput[]
  id?: Prisma.StringFilter<"Regret"> | string
  grade?: Prisma.StringFilter<"Regret"> | string
  category?: Prisma.StringFilter<"Regret"> | string
  content?: Prisma.StringFilter<"Regret"> | string
  tags?: Prisma.StringFilter<"Regret"> | string
  isLate?: Prisma.BoolFilter<"Regret"> | boolean
  remedy?: Prisma.StringNullableFilter<"Regret"> | string | null
  majorId?: Prisma.StringNullableFilter<"Regret"> | string | null
}

export type RegretCreateWithoutUserSavesInput = {
  id?: string
  grade: string
  category: string
  content: string
  tags: string
  isLate: boolean
  remedy?: string | null
  major?: Prisma.MajorCreateNestedOneWithoutRegretsInput
}

export type RegretUncheckedCreateWithoutUserSavesInput = {
  id?: string
  grade: string
  category: string
  content: string
  tags: string
  isLate: boolean
  remedy?: string | null
  majorId?: string | null
}

export type RegretCreateOrConnectWithoutUserSavesInput = {
  where: Prisma.RegretWhereUniqueInput
  create: Prisma.XOR<Prisma.RegretCreateWithoutUserSavesInput, Prisma.RegretUncheckedCreateWithoutUserSavesInput>
}

export type RegretUpsertWithoutUserSavesInput = {
  update: Prisma.XOR<Prisma.RegretUpdateWithoutUserSavesInput, Prisma.RegretUncheckedUpdateWithoutUserSavesInput>
  create: Prisma.XOR<Prisma.RegretCreateWithoutUserSavesInput, Prisma.RegretUncheckedCreateWithoutUserSavesInput>
  where?: Prisma.RegretWhereInput
}

export type RegretUpdateToOneWithWhereWithoutUserSavesInput = {
  where?: Prisma.RegretWhereInput
  data: Prisma.XOR<Prisma.RegretUpdateWithoutUserSavesInput, Prisma.RegretUncheckedUpdateWithoutUserSavesInput>
}

export type RegretUpdateWithoutUserSavesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  isLate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remedy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  major?: Prisma.MajorUpdateOneWithoutRegretsNestedInput
}

export type RegretUncheckedUpdateWithoutUserSavesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  isLate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remedy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  majorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RegretCreateManyMajorInput = {
  id?: string
  grade: string
  category: string
  content: string
  tags: string
  isLate: boolean
  remedy?: string | null
}

export type RegretUpdateWithoutMajorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  isLate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remedy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userSaves?: Prisma.UserRegretUpdateManyWithoutRegretNestedInput
}

export type RegretUncheckedUpdateWithoutMajorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  isLate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remedy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userSaves?: Prisma.UserRegretUncheckedUpdateManyWithoutRegretNestedInput
}

export type RegretUncheckedUpdateManyWithoutMajorInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  grade?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  isLate?: Prisma.BoolFieldUpdateOperationsInput | boolean
  remedy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type RegretCountOutputType
 */

export type RegretCountOutputType = {
  userSaves: number
}

export type RegretCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  userSaves?: boolean | RegretCountOutputTypeCountUserSavesArgs
}

/**
 * RegretCountOutputType without action
 */
export type RegretCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegretCountOutputType
   */
  select?: Prisma.RegretCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RegretCountOutputType without action
 */
export type RegretCountOutputTypeCountUserSavesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserRegretWhereInput
}


export type RegretSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  grade?: boolean
  category?: boolean
  content?: boolean
  tags?: boolean
  isLate?: boolean
  remedy?: boolean
  majorId?: boolean
  major?: boolean | Prisma.Regret$majorArgs<ExtArgs>
  userSaves?: boolean | Prisma.Regret$userSavesArgs<ExtArgs>
  _count?: boolean | Prisma.RegretCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["regret"]>

export type RegretSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  grade?: boolean
  category?: boolean
  content?: boolean
  tags?: boolean
  isLate?: boolean
  remedy?: boolean
  majorId?: boolean
  major?: boolean | Prisma.Regret$majorArgs<ExtArgs>
}, ExtArgs["result"]["regret"]>

export type RegretSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  grade?: boolean
  category?: boolean
  content?: boolean
  tags?: boolean
  isLate?: boolean
  remedy?: boolean
  majorId?: boolean
  major?: boolean | Prisma.Regret$majorArgs<ExtArgs>
}, ExtArgs["result"]["regret"]>

export type RegretSelectScalar = {
  id?: boolean
  grade?: boolean
  category?: boolean
  content?: boolean
  tags?: boolean
  isLate?: boolean
  remedy?: boolean
  majorId?: boolean
}

export type RegretOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "grade" | "category" | "content" | "tags" | "isLate" | "remedy" | "majorId", ExtArgs["result"]["regret"]>
export type RegretInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  major?: boolean | Prisma.Regret$majorArgs<ExtArgs>
  userSaves?: boolean | Prisma.Regret$userSavesArgs<ExtArgs>
  _count?: boolean | Prisma.RegretCountOutputTypeDefaultArgs<ExtArgs>
}
export type RegretIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  major?: boolean | Prisma.Regret$majorArgs<ExtArgs>
}
export type RegretIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  major?: boolean | Prisma.Regret$majorArgs<ExtArgs>
}

export type $RegretPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Regret"
  objects: {
    major: Prisma.$MajorPayload<ExtArgs> | null
    userSaves: Prisma.$UserRegretPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    grade: string
    category: string
    content: string
    tags: string
    isLate: boolean
    remedy: string | null
    majorId: string | null
  }, ExtArgs["result"]["regret"]>
  composites: {}
}

export type RegretGetPayload<S extends boolean | null | undefined | RegretDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RegretPayload, S>

export type RegretCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RegretFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RegretCountAggregateInputType | true
  }

export interface RegretDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Regret'], meta: { name: 'Regret' } }
  /**
   * Find zero or one Regret that matches the filter.
   * @param {RegretFindUniqueArgs} args - Arguments to find a Regret
   * @example
   * // Get one Regret
   * const regret = await prisma.regret.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RegretFindUniqueArgs>(args: Prisma.SelectSubset<T, RegretFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RegretClient<runtime.Types.Result.GetResult<Prisma.$RegretPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Regret that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RegretFindUniqueOrThrowArgs} args - Arguments to find a Regret
   * @example
   * // Get one Regret
   * const regret = await prisma.regret.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RegretFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RegretFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RegretClient<runtime.Types.Result.GetResult<Prisma.$RegretPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Regret that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegretFindFirstArgs} args - Arguments to find a Regret
   * @example
   * // Get one Regret
   * const regret = await prisma.regret.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RegretFindFirstArgs>(args?: Prisma.SelectSubset<T, RegretFindFirstArgs<ExtArgs>>): Prisma.Prisma__RegretClient<runtime.Types.Result.GetResult<Prisma.$RegretPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Regret that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegretFindFirstOrThrowArgs} args - Arguments to find a Regret
   * @example
   * // Get one Regret
   * const regret = await prisma.regret.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RegretFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RegretFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RegretClient<runtime.Types.Result.GetResult<Prisma.$RegretPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Regrets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegretFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Regrets
   * const regrets = await prisma.regret.findMany()
   * 
   * // Get first 10 Regrets
   * const regrets = await prisma.regret.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const regretWithIdOnly = await prisma.regret.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RegretFindManyArgs>(args?: Prisma.SelectSubset<T, RegretFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegretPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Regret.
   * @param {RegretCreateArgs} args - Arguments to create a Regret.
   * @example
   * // Create one Regret
   * const Regret = await prisma.regret.create({
   *   data: {
   *     // ... data to create a Regret
   *   }
   * })
   * 
   */
  create<T extends RegretCreateArgs>(args: Prisma.SelectSubset<T, RegretCreateArgs<ExtArgs>>): Prisma.Prisma__RegretClient<runtime.Types.Result.GetResult<Prisma.$RegretPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Regrets.
   * @param {RegretCreateManyArgs} args - Arguments to create many Regrets.
   * @example
   * // Create many Regrets
   * const regret = await prisma.regret.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RegretCreateManyArgs>(args?: Prisma.SelectSubset<T, RegretCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Regrets and returns the data saved in the database.
   * @param {RegretCreateManyAndReturnArgs} args - Arguments to create many Regrets.
   * @example
   * // Create many Regrets
   * const regret = await prisma.regret.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Regrets and only return the `id`
   * const regretWithIdOnly = await prisma.regret.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RegretCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RegretCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegretPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Regret.
   * @param {RegretDeleteArgs} args - Arguments to delete one Regret.
   * @example
   * // Delete one Regret
   * const Regret = await prisma.regret.delete({
   *   where: {
   *     // ... filter to delete one Regret
   *   }
   * })
   * 
   */
  delete<T extends RegretDeleteArgs>(args: Prisma.SelectSubset<T, RegretDeleteArgs<ExtArgs>>): Prisma.Prisma__RegretClient<runtime.Types.Result.GetResult<Prisma.$RegretPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Regret.
   * @param {RegretUpdateArgs} args - Arguments to update one Regret.
   * @example
   * // Update one Regret
   * const regret = await prisma.regret.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RegretUpdateArgs>(args: Prisma.SelectSubset<T, RegretUpdateArgs<ExtArgs>>): Prisma.Prisma__RegretClient<runtime.Types.Result.GetResult<Prisma.$RegretPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Regrets.
   * @param {RegretDeleteManyArgs} args - Arguments to filter Regrets to delete.
   * @example
   * // Delete a few Regrets
   * const { count } = await prisma.regret.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RegretDeleteManyArgs>(args?: Prisma.SelectSubset<T, RegretDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Regrets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegretUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Regrets
   * const regret = await prisma.regret.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RegretUpdateManyArgs>(args: Prisma.SelectSubset<T, RegretUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Regrets and returns the data updated in the database.
   * @param {RegretUpdateManyAndReturnArgs} args - Arguments to update many Regrets.
   * @example
   * // Update many Regrets
   * const regret = await prisma.regret.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Regrets and only return the `id`
   * const regretWithIdOnly = await prisma.regret.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RegretUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RegretUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegretPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Regret.
   * @param {RegretUpsertArgs} args - Arguments to update or create a Regret.
   * @example
   * // Update or create a Regret
   * const regret = await prisma.regret.upsert({
   *   create: {
   *     // ... data to create a Regret
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Regret we want to update
   *   }
   * })
   */
  upsert<T extends RegretUpsertArgs>(args: Prisma.SelectSubset<T, RegretUpsertArgs<ExtArgs>>): Prisma.Prisma__RegretClient<runtime.Types.Result.GetResult<Prisma.$RegretPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Regrets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegretCountArgs} args - Arguments to filter Regrets to count.
   * @example
   * // Count the number of Regrets
   * const count = await prisma.regret.count({
   *   where: {
   *     // ... the filter for the Regrets we want to count
   *   }
   * })
  **/
  count<T extends RegretCountArgs>(
    args?: Prisma.Subset<T, RegretCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RegretCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Regret.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegretAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RegretAggregateArgs>(args: Prisma.Subset<T, RegretAggregateArgs>): Prisma.PrismaPromise<GetRegretAggregateType<T>>

  /**
   * Group by Regret.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegretGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RegretGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RegretGroupByArgs['orderBy'] }
      : { orderBy?: RegretGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RegretGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRegretGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Regret model
 */
readonly fields: RegretFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Regret.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RegretClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  major<T extends Prisma.Regret$majorArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Regret$majorArgs<ExtArgs>>): Prisma.Prisma__MajorClient<runtime.Types.Result.GetResult<Prisma.$MajorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  userSaves<T extends Prisma.Regret$userSavesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Regret$userSavesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserRegretPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Regret model
 */
export interface RegretFieldRefs {
  readonly id: Prisma.FieldRef<"Regret", 'String'>
  readonly grade: Prisma.FieldRef<"Regret", 'String'>
  readonly category: Prisma.FieldRef<"Regret", 'String'>
  readonly content: Prisma.FieldRef<"Regret", 'String'>
  readonly tags: Prisma.FieldRef<"Regret", 'String'>
  readonly isLate: Prisma.FieldRef<"Regret", 'Boolean'>
  readonly remedy: Prisma.FieldRef<"Regret", 'String'>
  readonly majorId: Prisma.FieldRef<"Regret", 'String'>
}
    

// Custom InputTypes
/**
 * Regret findUnique
 */
export type RegretFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Regret
   */
  select?: Prisma.RegretSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Regret
   */
  omit?: Prisma.RegretOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegretInclude<ExtArgs> | null
  /**
   * Filter, which Regret to fetch.
   */
  where: Prisma.RegretWhereUniqueInput
}

/**
 * Regret findUniqueOrThrow
 */
export type RegretFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Regret
   */
  select?: Prisma.RegretSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Regret
   */
  omit?: Prisma.RegretOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegretInclude<ExtArgs> | null
  /**
   * Filter, which Regret to fetch.
   */
  where: Prisma.RegretWhereUniqueInput
}

/**
 * Regret findFirst
 */
export type RegretFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Regret
   */
  select?: Prisma.RegretSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Regret
   */
  omit?: Prisma.RegretOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegretInclude<ExtArgs> | null
  /**
   * Filter, which Regret to fetch.
   */
  where?: Prisma.RegretWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Regrets to fetch.
   */
  orderBy?: Prisma.RegretOrderByWithRelationInput | Prisma.RegretOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Regrets.
   */
  cursor?: Prisma.RegretWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Regrets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Regrets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Regrets.
   */
  distinct?: Prisma.RegretScalarFieldEnum | Prisma.RegretScalarFieldEnum[]
}

/**
 * Regret findFirstOrThrow
 */
export type RegretFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Regret
   */
  select?: Prisma.RegretSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Regret
   */
  omit?: Prisma.RegretOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegretInclude<ExtArgs> | null
  /**
   * Filter, which Regret to fetch.
   */
  where?: Prisma.RegretWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Regrets to fetch.
   */
  orderBy?: Prisma.RegretOrderByWithRelationInput | Prisma.RegretOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Regrets.
   */
  cursor?: Prisma.RegretWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Regrets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Regrets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Regrets.
   */
  distinct?: Prisma.RegretScalarFieldEnum | Prisma.RegretScalarFieldEnum[]
}

/**
 * Regret findMany
 */
export type RegretFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Regret
   */
  select?: Prisma.RegretSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Regret
   */
  omit?: Prisma.RegretOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegretInclude<ExtArgs> | null
  /**
   * Filter, which Regrets to fetch.
   */
  where?: Prisma.RegretWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Regrets to fetch.
   */
  orderBy?: Prisma.RegretOrderByWithRelationInput | Prisma.RegretOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Regrets.
   */
  cursor?: Prisma.RegretWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Regrets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Regrets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Regrets.
   */
  distinct?: Prisma.RegretScalarFieldEnum | Prisma.RegretScalarFieldEnum[]
}

/**
 * Regret create
 */
export type RegretCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Regret
   */
  select?: Prisma.RegretSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Regret
   */
  omit?: Prisma.RegretOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegretInclude<ExtArgs> | null
  /**
   * The data needed to create a Regret.
   */
  data: Prisma.XOR<Prisma.RegretCreateInput, Prisma.RegretUncheckedCreateInput>
}

/**
 * Regret createMany
 */
export type RegretCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Regrets.
   */
  data: Prisma.RegretCreateManyInput | Prisma.RegretCreateManyInput[]
}

/**
 * Regret createManyAndReturn
 */
export type RegretCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Regret
   */
  select?: Prisma.RegretSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Regret
   */
  omit?: Prisma.RegretOmit<ExtArgs> | null
  /**
   * The data used to create many Regrets.
   */
  data: Prisma.RegretCreateManyInput | Prisma.RegretCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegretIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Regret update
 */
export type RegretUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Regret
   */
  select?: Prisma.RegretSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Regret
   */
  omit?: Prisma.RegretOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegretInclude<ExtArgs> | null
  /**
   * The data needed to update a Regret.
   */
  data: Prisma.XOR<Prisma.RegretUpdateInput, Prisma.RegretUncheckedUpdateInput>
  /**
   * Choose, which Regret to update.
   */
  where: Prisma.RegretWhereUniqueInput
}

/**
 * Regret updateMany
 */
export type RegretUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Regrets.
   */
  data: Prisma.XOR<Prisma.RegretUpdateManyMutationInput, Prisma.RegretUncheckedUpdateManyInput>
  /**
   * Filter which Regrets to update
   */
  where?: Prisma.RegretWhereInput
  /**
   * Limit how many Regrets to update.
   */
  limit?: number
}

/**
 * Regret updateManyAndReturn
 */
export type RegretUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Regret
   */
  select?: Prisma.RegretSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Regret
   */
  omit?: Prisma.RegretOmit<ExtArgs> | null
  /**
   * The data used to update Regrets.
   */
  data: Prisma.XOR<Prisma.RegretUpdateManyMutationInput, Prisma.RegretUncheckedUpdateManyInput>
  /**
   * Filter which Regrets to update
   */
  where?: Prisma.RegretWhereInput
  /**
   * Limit how many Regrets to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegretIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Regret upsert
 */
export type RegretUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Regret
   */
  select?: Prisma.RegretSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Regret
   */
  omit?: Prisma.RegretOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegretInclude<ExtArgs> | null
  /**
   * The filter to search for the Regret to update in case it exists.
   */
  where: Prisma.RegretWhereUniqueInput
  /**
   * In case the Regret found by the `where` argument doesn't exist, create a new Regret with this data.
   */
  create: Prisma.XOR<Prisma.RegretCreateInput, Prisma.RegretUncheckedCreateInput>
  /**
   * In case the Regret was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RegretUpdateInput, Prisma.RegretUncheckedUpdateInput>
}

/**
 * Regret delete
 */
export type RegretDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Regret
   */
  select?: Prisma.RegretSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Regret
   */
  omit?: Prisma.RegretOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegretInclude<ExtArgs> | null
  /**
   * Filter which Regret to delete.
   */
  where: Prisma.RegretWhereUniqueInput
}

/**
 * Regret deleteMany
 */
export type RegretDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Regrets to delete
   */
  where?: Prisma.RegretWhereInput
  /**
   * Limit how many Regrets to delete.
   */
  limit?: number
}

/**
 * Regret.major
 */
export type Regret$majorArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Major
   */
  select?: Prisma.MajorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Major
   */
  omit?: Prisma.MajorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MajorInclude<ExtArgs> | null
  where?: Prisma.MajorWhereInput
}

/**
 * Regret.userSaves
 */
export type Regret$userSavesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserRegret
   */
  select?: Prisma.UserRegretSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserRegret
   */
  omit?: Prisma.UserRegretOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserRegretInclude<ExtArgs> | null
  where?: Prisma.UserRegretWhereInput
  orderBy?: Prisma.UserRegretOrderByWithRelationInput | Prisma.UserRegretOrderByWithRelationInput[]
  cursor?: Prisma.UserRegretWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserRegretScalarFieldEnum | Prisma.UserRegretScalarFieldEnum[]
}

/**
 * Regret without action
 */
export type RegretDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Regret
   */
  select?: Prisma.RegretSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Regret
   */
  omit?: Prisma.RegretOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegretInclude<ExtArgs> | null
}
