
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Account: 'Account',
  Session: 'Session',
  VerificationToken: 'VerificationToken',
  Major: 'Major',
  University: 'University',
  UniversityMajor: 'UniversityMajor',
  EmploymentStat: 'EmploymentStat',
  CareerPath: 'CareerPath',
  Salary: 'Salary',
  CareerDay: 'CareerDay',
  Regret: 'Regret',
  UserRegret: 'UserRegret',
  GuideProgress: 'GuideProgress',
  Assessment: 'Assessment'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  image: 'image',
  grade: 'grade',
  province: 'province',
  score: 'score',
  subjectCombo: 'subjectCombo',
  targetPath: 'targetPath',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
} as const

export type VerificationTokenScalarFieldEnum = (typeof VerificationTokenScalarFieldEnum)[keyof typeof VerificationTokenScalarFieldEnum]


export const MajorScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  degree: 'degree',
  category: 'category',
  description: 'description',
  courses: 'courses',
  hardPoints: 'hardPoints',
  abilities: 'abilities',
  relatedMajors: 'relatedMajors',
  aiRisk: 'aiRisk',
  aiRiskLevel: 'aiRiskLevel',
  employmentRate: 'employmentRate',
  matchRate: 'matchRate'
} as const

export type MajorScalarFieldEnum = (typeof MajorScalarFieldEnum)[keyof typeof MajorScalarFieldEnum]


export const UniversityScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  level: 'level',
  type: 'type',
  province: 'province',
  city: 'city',
  baoYanRate: 'baoYanRate',
  description: 'description'
} as const

export type UniversityScalarFieldEnum = (typeof UniversityScalarFieldEnum)[keyof typeof UniversityScalarFieldEnum]


export const UniversityMajorScalarFieldEnum = {
  id: 'id',
  universityId: 'universityId',
  majorId: 'majorId',
  admissionScore: 'admissionScore',
  admissionRank: 'admissionRank',
  year: 'year',
  subjectReq: 'subjectReq'
} as const

export type UniversityMajorScalarFieldEnum = (typeof UniversityMajorScalarFieldEnum)[keyof typeof UniversityMajorScalarFieldEnum]


export const EmploymentStatScalarFieldEnum = {
  id: 'id',
  majorId: 'majorId',
  industry: 'industry',
  ratio: 'ratio',
  cityDistribution: 'cityDistribution'
} as const

export type EmploymentStatScalarFieldEnum = (typeof EmploymentStatScalarFieldEnum)[keyof typeof EmploymentStatScalarFieldEnum]


export const CareerPathScalarFieldEnum = {
  id: 'id',
  majorId: 'majorId',
  title: 'title',
  level: 'level',
  salary: 'salary',
  skills: 'skills'
} as const

export type CareerPathScalarFieldEnum = (typeof CareerPathScalarFieldEnum)[keyof typeof CareerPathScalarFieldEnum]


export const SalaryScalarFieldEnum = {
  id: 'id',
  majorId: 'majorId',
  cityTier: 'cityTier',
  year0: 'year0',
  year3: 'year3',
  year5: 'year5',
  year10: 'year10'
} as const

export type SalaryScalarFieldEnum = (typeof SalaryScalarFieldEnum)[keyof typeof SalaryScalarFieldEnum]


export const CareerDayScalarFieldEnum = {
  id: 'id',
  title: 'title',
  industry: 'industry',
  city: 'city',
  experience: 'experience',
  education: 'education',
  timeline: 'timeline',
  salary: 'salary',
  expense: 'expense',
  monthlyJoy: 'monthlyJoy',
  monthlyWorry: 'monthlyWorry',
  adviceToSelf: 'adviceToSelf',
  satisfaction: 'satisfaction',
  majorId: 'majorId'
} as const

export type CareerDayScalarFieldEnum = (typeof CareerDayScalarFieldEnum)[keyof typeof CareerDayScalarFieldEnum]


export const RegretScalarFieldEnum = {
  id: 'id',
  grade: 'grade',
  category: 'category',
  content: 'content',
  tags: 'tags',
  isLate: 'isLate',
  remedy: 'remedy',
  majorId: 'majorId'
} as const

export type RegretScalarFieldEnum = (typeof RegretScalarFieldEnum)[keyof typeof RegretScalarFieldEnum]


export const UserRegretScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  regretId: 'regretId',
  markedAt: 'markedAt'
} as const

export type UserRegretScalarFieldEnum = (typeof UserRegretScalarFieldEnum)[keyof typeof UserRegretScalarFieldEnum]


export const GuideProgressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  phase: 'phase',
  taskId: 'taskId',
  completed: 'completed',
  completedAt: 'completedAt'
} as const

export type GuideProgressScalarFieldEnum = (typeof GuideProgressScalarFieldEnum)[keyof typeof GuideProgressScalarFieldEnum]


export const AssessmentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  result: 'result',
  createdAt: 'createdAt'
} as const

export type AssessmentScalarFieldEnum = (typeof AssessmentScalarFieldEnum)[keyof typeof AssessmentScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

