
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Account
 * 
 */
export type Account = Prisma.AccountModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model VerificationToken
 * 
 */
export type VerificationToken = Prisma.VerificationTokenModel
/**
 * Model Major
 * 
 */
export type Major = Prisma.MajorModel
/**
 * Model University
 * 
 */
export type University = Prisma.UniversityModel
/**
 * Model UniversityMajor
 * 
 */
export type UniversityMajor = Prisma.UniversityMajorModel
/**
 * Model EmploymentStat
 * 
 */
export type EmploymentStat = Prisma.EmploymentStatModel
/**
 * Model CareerPath
 * 
 */
export type CareerPath = Prisma.CareerPathModel
/**
 * Model Salary
 * 
 */
export type Salary = Prisma.SalaryModel
/**
 * Model CareerDay
 * 
 */
export type CareerDay = Prisma.CareerDayModel
/**
 * Model Regret
 * 
 */
export type Regret = Prisma.RegretModel
/**
 * Model UserRegret
 * 
 */
export type UserRegret = Prisma.UserRegretModel
/**
 * Model GuideProgress
 * 
 */
export type GuideProgress = Prisma.GuideProgressModel
/**
 * Model Assessment
 * 
 */
export type Assessment = Prisma.AssessmentModel
