
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Account'
export type * from './models/Session'
export type * from './models/VerificationToken'
export type * from './models/Major'
export type * from './models/University'
export type * from './models/UniversityMajor'
export type * from './models/EmploymentStat'
export type * from './models/CareerPath'
export type * from './models/Salary'
export type * from './models/CareerDay'
export type * from './models/Regret'
export type * from './models/UserRegret'
export type * from './models/GuideProgress'
export type * from './models/Assessment'
export type * from './commonInputTypes'